package floats

import (
	"math"
	"math/bits"

	"github.com/shogo82148/ints"
)

const (
	uvnanbf16    = 0x7fc0     // NaN value for BFloat16
	uvinfbf16    = 0x7f80     // Infinity value for BFloat16
	uvneginfbf16 = 0xff80     // Negative Infinity value for BFloat16
	uvonebf16    = 0x3f80     // One value for BFloat16
	maskbf16     = 0xff       // mask for exponent
	shiftbf16    = 16 - 8 - 1 // shift for exponent
	biasbf16     = 127        // bias for exponent
	signMaskbf16 = 1 << 15    // mask for sign bit
	fracMaskbf16 = 1<<shiftbf16 - 1
)

// BFloat16 is a 16-bit floating-point number in the bfloat16 (Brain Floating Point) format.
// It has 1 sign bit, 8 exponent bits and 7 fraction bits;
// the exponent range is the same as Float32.
type BFloat16 uint16

// NewBFloat16 converts f to BFloat16.
func NewBFloat16(f float64) BFloat16 {
	return Float64(f).BFloat16()
}

// NewBFloat16FromBits converts the IEEE 754 binary representation b to BFloat16.
func NewBFloat16FromBits(b uint16) BFloat16 {
	return BFloat16(b)
}

// NewBFloat16NaN returns a NaN BFloat16 value.
func NewBFloat16NaN() BFloat16 {
	return uvnanbf16
}

// NewBFloat16Inf positive infinity if sign >= 0, negative infinity if sign < 0.
func NewBFloat16Inf(sign int) BFloat16 {
	if sign >= 0 {
		return uvinfbf16
	}
	return uvneginfbf16
}

// Bits returns the IEEE 754 binary representation of a.
func (a BFloat16) Bits() uint16 {
	return uint16(a)
}

// IsNaN reports whether a is an IEEE 754 “not-a-number” value.
func (a BFloat16) IsNaN() bool {
	return a&(maskbf16<<shiftbf16) == (maskbf16<<shiftbf16) && a&fracMaskbf16 != 0
}

// IsInf reports whether a is an infinity, according to sign.
// If sign > 0, IsInf reports whether a is positive infinity.
// If sign < 0, IsInf reports whether a is negative infinity.
// If sign == 0, IsInf reports whether a is either infinity.
func (a BFloat16) IsInf(sign int) bool {
	return sign >= 0 && a == uvinfbf16 || sign <= 0 && a == uvneginfbf16
}

// Signbit reports whether x is negative or negative zero.
func (a BFloat16) Signbit() bool {
	return a&signMaskbf16 != 0
}

// Copysign returns a value with the magnitude of a
// and the sign of sign.
func (a BFloat16) Copysign(sign BFloat16) BFloat16 {
	return (a &^ signMaskbf16) | (sign & signMaskbf16)
}

// Int64 returns the integer value of a, rounding towards zero.
// If a cannot be represented in an int64, the result is undefined.
func (a BFloat16) Int64() int64 {
	return int64(a.Float64())
}

// Uint64 returns the unsigned integer value of a, rounding towards zero.
// If a cannot be represented in a uint64, the result is undefined.
func (a BFloat16) Uint64() uint64 {
	return uint64(a.Float64())
}

// Int128 returns the signed 128-bit integer value of a, rounding towards zero.
// If a cannot be represented in a int128, the result is undefined.
func (a BFloat16) Int128() ints.Int128 {
	return a.Float32().Int128()
}

// Uint128 returns the unsigned 128-bit integer value of a, rounding towards zero.
// If a cannot be represented in a uint128, the result is undefined.
func (a BFloat16) Uint128() ints.Uint128 {
	return a.Float32().Uint128()
}

// Int256 returns the signed 256-bit integer value of a, rounding towards zero.
// If a cannot be represented in a int256, the result is undefined.
func (a BFloat16) Int256() ints.Int256 {
	return a.Float32().Int256()
}

// Uint256 returns the unsigned 256-bit integer value of a, rounding towards zero.
// If a cannot be represented in a uint256, the result is undefined.
func (a BFloat16) Uint256() ints.Uint256 {
	return a.Float32().Uint256()
}

// IsZero reports whether a is zero (+0 or -0).
func (a BFloat16) IsZero() bool {
	return a&^signMaskbf16 == 0
}

// Neg returns the negation of a.
func (a BFloat16) Neg() BFloat16 {
	return a ^ signMaskbf16
}

// Abs returns the absolute value of a.
//
// Special cases:
//
//	Abs(±Inf) = +Inf
//	Abs(NaN) = NaN
func (a BFloat16) Abs() BFloat16 {
	return a &^ signMaskbf16
}

// Mul returns the product of a and b.
func (a BFloat16) Mul(b BFloat16) BFloat16 {
	// The product of two BFloat16 values has 16 bits, so it is exact in float64.
	// Rounding it again to 8 bits is the same as rounding once, because 53 >= 2*8+2.
	r := Float64(float64(a.Float32()) * float64(b.Float32())).BFloat16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnanbf16
	}
	return r
}

// Quo returns the quotient of a and b.
func (a BFloat16) Quo(b BFloat16) BFloat16 {
	// Rounding the float64 quotient again to 8 bits is the same as rounding once,
	// because 53 >= 2*8+2.
	r := Float64(float64(a.Float32()) / float64(b.Float32())).BFloat16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnanbf16
	}
	return r
}

// Add returns the sum of a and b.
func (a BFloat16) Add(b BFloat16) BFloat16 {
	// Rounding the float64 sum again to 8 bits is the same as rounding once,
	// because 53 >= 2*8+2.
	r := Float64(float64(a.Float32()) + float64(b.Float32())).BFloat16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnanbf16
	}
	return r
}

// Sub returns the difference of a and b.
func (a BFloat16) Sub(b BFloat16) BFloat16 {
	return a.Add(b.Neg())
}

// Sqrt returns the square root of a.
//
// Special cases are:
//
//	Sqrt(+Inf) = +Inf
//	Sqrt(±0) = ±0
//	Sqrt(x < 0) = NaN
//	Sqrt(NaN) = NaN
func (a BFloat16) Sqrt() BFloat16 {
	// special cases
	switch {
	case a.IsZero() || a.IsNaN() || a.IsInf(1):
		return a
	case a&signMaskbf16 != 0:
		return uvnanbf16
	}

	// The square root in float64 is correctly rounded, and rounding it again to 8 bits
	// is the same as rounding once, because 53 >= 2*8+2.
	return Float64(math.Sqrt(float64(a.Float32()))).BFloat16()
}

// Eq returns a == b.
// NaNs are not equal to anything, including NaN.
// -0.0 and 0.0 are equal.
func (a BFloat16) Eq(b BFloat16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	if a == b {
		// a and b have the same bit pattern.
		return true
	}

	// check -0 == 0
	return (a|b)&^signMaskbf16 == 0
}

// Ne returns a != b.
// NaNs are not equal to anything, including NaN.
// -0.0 and 0.0 are equal.
func (a BFloat16) Ne(b BFloat16) bool {
	return !a.Eq(b)
}

// Lt returns a < b.
//
// Special cases are:
//
//	Lt(NaN, x) == false
//	Lt(x, NaN) == false
func (a BFloat16) Lt(b BFloat16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	return a.comparable() < b.comparable()
}

// Gt returns a > b.
//
// Special cases are:
//
//	Gt(x, NaN) == false
//	Gt(NaN, x) == false
func (a BFloat16) Gt(b BFloat16) bool {
	return b.Lt(a)
}

// Le returns a <= b.
//
// Special cases are:
//
//	Le(x, NaN) == false
//	Le(NaN, x) == false
func (a BFloat16) Le(b BFloat16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	return a.comparable() <= b.comparable()
}

// Ge returns a >= b.
//
// Special cases are:
//
//	Ge(x, NaN) == false
//	Ge(NaN, x) == false
func (a BFloat16) Ge(b BFloat16) bool {
	return b.Le(a)
}

// normalize returns the sign, exponent, and normalized fraction of a.
func (a BFloat16) normalize() (sign uint16, exp int, frac uint16) {
	sign = uint16(a & signMaskbf16)
	exp = int((a>>shiftbf16)&maskbf16) - biasbf16
	frac = uint16(a & fracMaskbf16)

	if exp == -biasbf16 {
		// a is subnormal
		// normalize
		l := bits.Len16(frac)
		frac <<= uint(shiftbf16 + 1 - l)
		exp = l - (biasbf16 + shiftbf16)
		return
	}

	// a is normal
	frac |= 1 << shiftbf16
	return
}

func (a BFloat16) split() (sign uint16, exp int, frac uint16) {
	sign = uint16(a & signMaskbf16)
	exp = int((a>>shiftbf16)&maskbf16) - biasbf16
	frac = uint16(a & fracMaskbf16)

	if exp == -biasbf16 {
		// a is subnormal
		exp++
	} else {
		// a is normal
		frac |= 1 << shiftbf16
	}
	return
}

// comparable converts a to a comparable form.
func (a BFloat16) comparable() int16 {
	i := int16(a)
	i ^= (i >> 15) & 0x7fff
	i += int16(a >> 15) // normalize -0 to 0
	return i
}

// FMABF16 returns x * y + z, computed with only one rounding.
// (That is, FMABF16 returns the fused multiply-add of x, y, and z.)
func FMABF16(x, y, z BFloat16) BFloat16 {
	// The product of two BFloat16 values is exact in float64,
	// and so is the error of the sum of two float64 values.
	p := float64(x.Float32()) * float64(y.Float32())
	zz := float64(z.Float32())
	s := p + zz
	bb := s - p
	e := (p - (s - bb)) + (zz - bb)

	// Round s to odd. Rounding to odd with more than 8+1 bits
	// and then to nearest even to 8 bits is the same as rounding once.
	// The error e is NaN if p or zz is Inf, and then s is not touched.
	if e != 0 && math.Abs(s) < math.MaxFloat64 {
		u := math.Float64bits(s)
		if u&1 == 0 {
			// move s toward the true value p + zz
			if (e > 0) == (s > 0) {
				u++
			} else {
				u--
			}
			s = math.Float64frombits(u)
		}
	}
	r := Float64(s).BFloat16()
	if r.IsNaN() {
		return uvnanbf16
	}
	return r
}

// Nextafter returns the next representable bfloat16 value after a towards b.
//
// Special cases are:
//
//	a.Nextafter(a)   = a
//	NaN.Nextafter(b) = NaN
//	a.Nextafter(NaN) = NaN
func (a BFloat16) Nextafter(b BFloat16) (r BFloat16) {
	switch {
	case a.IsNaN() || b.IsNaN(): // special case
		r = NewBFloat16NaN()
	case a.Eq(b): // special case, including +0 and -0
		r = a
	case a.IsZero():
		r = BFloat16(1).Copysign(b)
	case b.Gt(a) == a.Gt(0):
		r = a + 1
	default:
		r = a - 1
	}
	return
}

// Modf returns integer and fractional floating-point numbers
// that sum to f. Both values have the same sign as f.
//
// Special cases are:
//
//	Modf(±Inf) = ±Inf, NaN
//	Modf(NaN) = NaN, NaN
func (a BFloat16) Modf() (int BFloat16, frac BFloat16) {
	if a.Lt(BFloat16(uvonebf16)) { // a < 1
		switch {
		case a.Lt(BFloat16(0)): // a < 0
			int, frac = a.Neg().Modf()
			return int.Neg(), frac.Neg()
		case a.IsZero(): // a == 0
			return a, a
		default: // 0 < a < 1
			return BFloat16(0), a
		}
	}

	int = a
	e := uint(int>>shiftbf16&maskbf16) - biasbf16

	// Keep the top 6+e bits, the integer part; clear the rest.
	if e < shiftbf16 {
		int &^= 1<<(shiftbf16-e) - 1
	}
	frac = a.Sub(int)
	return
}

// Frexp breaks a into a normalized fraction
// and an integral power of two.
// It returns frac and exp satisfying f == frac × 2**exp,
// with the absolute value of frac in the interval [½, 1).
//
// Special cases are:
//
//	±0.Frexp() = ±0, 0
//	±Inf.Frexp() = ±Inf, 0
//	NaN.Frexp() = NaN, 0
func (a BFloat16) Frexp() (frac BFloat16, exp int) {
	f, e := math.Frexp(a.Float64().BuiltIn())
	return NewBFloat16(f), e
}

// Ldexp is the inverse of [Frexp].
// It returns a × 2**exp.
//
// Special cases are:
//
//	±0.Ldexp(exp) = ±0
//	±Inf.Ldexp(exp) = ±Inf
//	NaN.Ldexp(exp) = NaN
func (a BFloat16) Ldexp(exp int) BFloat16 {
	f := math.Ldexp(a.Float64().BuiltIn(), exp)
	return NewBFloat16(f)
}

// Mod returns the floating-point remainder of a/b.
// The magnitude of the result is less than b and its
// sign agrees with that of a.
//
// Special cases are:
//
//	±Inf.Mod(b) = NaN
//	NaN.Mod(b) = NaN
//	a.Mod(0) = NaN
//	a.Mod(±Inf) = a
//	a.Mod(NaN) = NaN
func (a BFloat16) Mod(b BFloat16) BFloat16 {
	return NewBFloat16(math.Mod(a.Float64().BuiltIn(), b.Float64().BuiltIn()))
}

// Remainder returns the IEEE 754 floating-point remainder of a/b.
//
// Special cases are:
//
//	±Inf.Remainder(b) = NaN
//	NaN.Remainder(b) = NaN
//	a.Remainder(0) = NaN
//	a.Remainder(±Inf) = a
//	a.Remainder(NaN) = NaN
func (a BFloat16) Remainder(b BFloat16) BFloat16 {
	return NewBFloat16(math.Remainder(a.Float64().BuiltIn(), b.Float64().BuiltIn()))
}
