// Code generated by scripts/gen_erf16_table.py; DO NOT EDIT.

package floats

// erf16Coeffs[s-8160] are the coefficients c0, c1, ..., c6 of the polynomial c0 + c1 t + ... + c6 t**6,
// which approximates erf(x) for x in the segment s, where t = x - the center of the segment.
// The segment s of x is the exponent and the upper three bits of the fraction of the float64 representation of x,
// s = 8160, ..., 8194.
// The relative error is less than 2**-35.
var erf16Coeffs = [...][7]float64{
	{0x1.311fc15f56d14p-3, 0x1.1bd07cdd189aap+0, -0x1.2d8d84aaea242p-3, -0x1.6d11b7f092463p-2, 0x1.2a01b7f789787p-4, 0x1.a63db94ab7efap-4, -0x1.88a31d055f287p-6},
	{0x1.548642321d7c6p-3, 0x1.1a91e5a748163p+0, -0x1.4f8d40b6a59a3p-3, -0x1.682834ff643f6p-2, 0x1.4a9f70348067bp-4, 0x1.9c8c38c9beb35p-4, -0x1.b24e117e1005dp-6},
	{0x1.77c2d2a765f9ep-3, 0x1.19318bae53a01p+0, -0x1.71110754cdc1fp-3, -0x1.62bdcbd5e6216p-2, 0x1.6a71a119888d7p-4, 0x1.91e508badab2ap-4, -0x1.da82cb26ae70dp-6},
	{0x1.9ad142662e14dp-3, 0x1.17aff0e56ec0ep+0, -0x1.920cea49cf350p-3, -0x1.5cd5d07da460ep-2, 0x1.8965731d11566p-4, 0x1.865153160248fp-4, -0x1.0090041212b0dp-5},
	{0x1.bdad72110a648p-3, 0x1.160da304ed92cp+0, -0x1.b2754eb7b3352p-3, -0x1.5673e0e57c682p-2, 0x1.a768cda80d22ep-4, 0x1.79db042982b9ap-4, -0x1.13032430f7971p-5},
	{0x1.e05354b96ff36p-3, 0x1.144b3b337c90ap+0, -0x1.d23ef3e6e233cp-3, -0x1.4f9be1c803e91p-2, 0x1.c46a65d8d0893p-4, 0x1.6c8cbfab6ae65p-4, -0x1.248bf73dfaaf5p-5},
	{0x1.015f78a3dcf3dp-2, 0x1.12695da8b5bdcp+0, -0x1.f15ef9c1c967ap-3, -0x1.4851fb58a4170p-2, 0x1.e059cc63c5da0p-4, 0x1.5e71d50d00cbbp-4, -0x1.351caf0fff36ep-5},
	{0x1.127631eb8de32p-2, 0x1.1068b94962e5cp+0, -0x1.07e5737f17ce7p-2, -0x1.409a95bb0e581p-2, 0x1.fb277a83b8934p-4, 0x1.4f96331fe7f02p-4, -0x1.44a88be06a1cbp-5},
	{0x1.2bd9db0f7827fp-2, 0x1.0d2fa5a70c0fdp+0, -0x1.1e02a0017cc5fp-2, -0x1.344465d116b9ep-2, 0x1.108e95a8c2042p-3, 0x1.37f9e3b14b171p-4, -0x1.59f1545c61ee8p-5},
	{0x1.4d35ef3e5372ep-2, 0x1.087ee4d9ad1efp+0, -0x1.3a16afc27d885p-2, -0x1.227f5e4e037e1p-2, 0x1.27a2451bc4304p-3, 0x1.165cc5a661be1p-4, -0x1.72670a9927bcdp-5},
	{0x1.6df50a8dff772p-2, 0x1.03613f2812d6ap+0, -0x1.546fa2e498abbp-2, -0x1.0f5e933574136p-2, 0x1.3c001f7fbbe96p-3, 0x1.e55a46bb1edd5p-5, -0x1.861e2a2832873p-5},
	{0x1.8e0a01cab516bp-2, 0x1.fbbbbef34b450p-1, -0x1.6ceef13ede09fp-2, -0x1.f61d2af4a2f5dp-3, 0x1.4d8333cffe799p-3, 0x1.9abe35fdc3441p-5, -0x1.94e9f65091766p-5},
	{0x1.ad68966569a87p-2, 0x1.eff8c4b1375a1p-1, -0x1.837a59aa732d1p-2, -0x1.cb7bf786ea9dfp-3, 0x1.5c0fc761ebc44p-3, 0x1.4dd411382098bp-5, -0x1.9eb20adbc477fp-5},
	{0x1.cc058392a6d2dp-2, 0x1.e38988fc46e60p-1, -0x1.97fc0b94dbbf2p-2, -0x1.9f399aca62daap-3, 0x1.679383a12c062p-3, 0x1.ff1a74ea4d5d6p-6, -0x1.a37259caf3a5cp-5},
	{0x1.e9d68931ae650p-2, 0x1.d67ea1a8b537dp-1, -0x1.aa62c280e4261p-2, -0x1.71b7d760668dbp-3, 0x1.70057db87b54cp-3, 0x1.61b3eb3877a9ap-6, -0x1.a33ac4cfb50f3p-5},
	{0x1.03693a371519cp-1, 0x1.c8e91c4d013a3p-1, -0x1.baa1d36a991a5p-2, -0x1.4358f7e3e56b9p-3, 0x1.756618e69d4f4p-3, 0x1.8a96f2bc3f80ap-7, -0x1.9e2e5705eb369p-5},
	{0x1.1855a5fd3dd50p-1, 0x1.b3aafcc276c3fp-1, -0x1.cee5ac8e98208p-2, -0x1.fa0299fd97067p-4, 0x1.77cd74dfce077p-3, -0x1.f6ed4323bf77ep-10, -0x1.8dec203148f31p-5},
	{0x1.32a54cb8db67bp-1, 0x1.96164fafdb948p-1, -0x1.e23a7ea0ce182p-2, -0x1.3f5ee40ca25dbp-4, 0x1.70e469021550cp-3, -0x1.3d4fba78b1c4cp-6, -0x1.69f188e22b950p-5},
	{0x1.4b13713ad3513p-1, 0x1.7791b886eab5ep-1, -0x1.ecef42310cfe0p-2, -0x1.15c3ccb9d371dp-5, 0x1.5f68900e6b14cp-3, -0x1.1d6ee6992838ap-5, -0x1.38455f096a05ap-5},
	{0x1.61955607dd15dp-1, 0x1.58a445da806c8p-1, -0x1.ef6c246a115f5p-2, 0x1.e83dce240422cp-8, 0x1.44cc657d67523p-3, -0x1.87944b59feee6p-5, -0x1.f90e9145f3444p-6},
	{0x1.762870f720c6fp-1, 0x1.39ccc1b13b0f7p-1, -0x1.ea4feea4e5247p-2, 0x1.715e50df9215fp-5, 0x1.22cdbd9276723p-3, -0x1.da0d0f7e22743p-5, -0x1.754ef9e56b884p-6},
	{0x1.88d1cd474a2e0p-1, 0x1.1b7e98fe2a5f3p-1, -0x1.de65a22ce0bebp-2, 0x1.406866017d10bp-4, 0x1.f6b0cb9c47af3p-4, -0x1.09a5dc5021422p-4, -0x1.da7358c207f33p-7},
	{0x1.999d4192a5715p-1, 0x1.fc3ee5d15a5d7p-2, -0x1.cc990045b3cbdp-2, 0x1.b37334dd6d232p-4, 0x1.a0d12085ab02cp-4, -0x1.199ae229726f7p-4, -0x1.a105d4af4c157p-8},
	{0x1.a89c850b7d54dp-1, 0x1.c40b0729f49efp-2, -0x1.b5eaaef09fca9p-2, 0x1.0847c60837f66p-3, 0x1.47de0b3fd8374p-4, -0x1.1d80be4cb8f1cp-4, 0x1.3144645f738efp-10},
	{0x1.bbef0fbde6221p-1, 0x1.75a91a80b46f5p-2, -0x1.8d03ac27e2e64p-2, 0x1.3954611922b61p-3, 0x1.88e11febc1025p-5, -0x1.0f2241dd53d3dp-4, 0x1.5ce0e32feae3ap-7},
	{0x1.d0580b2cfd249p-1, 0x1.1a0dc51b55bd9p-2, -0x1.4ef05a1042e52p-2, 0x1.5648aa13ccca8p-3, 0x1.40fc589e46ceap-7, -0x1.c07d47ace9ac4p-5, 0x1.37df3a0343814p-6},
	{0x1.df85ea8db188ep-1, 0x1.9cb5bd54d074ap-3, -0x1.0ed74440173f0p-2, 0x1.5066cbfd7991fp-3, -0x1.419f584c8379ep-6, -0x1.3f342688ac8abp-5, 0x1.6c8bee6cd97a6p-6},
	{0x1.ea7730ed0bbb9p-1, 0x1.24a7b84c7ae25p-3, -0x1.a4b118efc0434p-3, 0x1.319c8064012aep-3, -0x1.3db5a6f72631dp-5, -0x1.7078b08381468p-6, 0x1.597433c461609p-6},
	{0x1.f21c9f12f0677p-1, 0x1.92470a5f2b825p-4, -0x1.3a47801ca890ep-3, 0x1.04540339e797ep-3, -0x1.8a7c5fe65d374p-5, -0x1.08a1c0621c5f8p-7, 0x1.16d0d7936b600p-6},
	{0x1.f74a6d9a38383p-1, 0x1.0bf97e9322bb9p-4, -0x1.c435059cf8989p-4, 0x1.a368929e8a0b9p-4, -0x1.9647a41975cbfp-5, 0x1.63e0ab21e7d60p-9, 0x1.7e8fd1dabac95p-7},
	{0x1.fab0dd89d1309p-1, 0x1.5a08e855f3554p-5, -0x1.39981291e7938p-4, 0x1.414103b4040b2p-4, -0x1.7535ae5d8f976p-5, 0x1.360cacce9e65dp-7, 0x1.a48b513bfa42dp-8},
	{0x1.fcdacca0bfb73p-1, 0x1.b116098a85662p-6, -0x1.a38d5944081e5p-5, 0x1.d5bdaf9f049f6p-5, -0x1.3b35e7f797f22p-5, 0x1.9c876b0c39f2cp-7, 0x1.16300727287c7p-9},
	{0x1.fea4218d6594ap-1, 0x1.94624cca4f67ep-7, -0x1.ada872c22aa25p-6, 0x1.0ea54d128d747p-5, -0x1.afe69091361f7p-6, 0x1.97c5a6cc74529p-7, -0x1.d392e399d20f8p-10},
	{0x1.ff9960f3eb327p-1, 0x1.06918b97a853bp-8, -0x1.37ccd4fd57d6cp-7, 0x1.c1ebdb8e0bfe6p-7, -0x1.ae5a728e3f8fap-7, 0x1.11f5a8650cca9p-7, -0x1.9609147ed21bfp-9},
	{0x1.ffe514bbdc197p-1, 0x1.2ce89d5a4d86fp-10, -0x1.8af148071c72fp-9, 0x1.407d4ff52db98p-8, -0x1.62d4e8564c0cap-8, 0x1.15a3464ebbc72p-8, -0x1.265e1fa24c76bp-9},
}

// erf16SmallCoeffs are the coefficients of the polynomial of u = x**2, which approximates erf(x)/x for 0 <= x < 1/8.
// The relative error is less than 2**-56.
var erf16SmallCoeffs = [...]float64{
	0x1.20dd750429b6dp+0, -0x1.812746b0379a0p-2, 0x1.ce2f21a00f2fcp-4, -0x1.b82ce2367f627p-6, 0x1.565a247787ddap-8, -0x1.bd39fdb90fa3ap-11,
}
