package floats

import (
	"bufio"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat128_Exp(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(-1), "0.3678794411714423215955237701614608674458111310317678345078368016974614957449"},
		{exact128(0), "1"},
		{exact128(1), "2.71828182845904523536028747135266249775724709369995957496696762772407663035355"},
		{exact128(2), "7.38905609893065022723042746057500781318031557055184732408712782252257379607906"},
		{exact128(3), "20.085536923187667740928529654581717896987907838554150144378934229698845878092"},
		{exact128(4), "54.5981500331442390781102612028608784027907370386140687258265939585536620999359"},
	}

	for _, tt := range tests {
		got := tt.x.Exp()
		if !close128(got, tt.want) {
			t.Errorf("Exp(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		{exact128(0), exact128(1)},
		{exact128(math.Copysign(0, -1)), exact128(1)},

		// tiny values
		{exact128(0x1p-115), exact128(1)},
		{exact128(-0x1p-115), exact128(1)},
		{exact128(0x1p-114), exact128(1)},
		{exact128(-0x1p-114), exact128(1)},
		{exact128(0x1p-113), Float128{0x3fff_0000_0000_0000, 0x0000_0000_0000_0001}},                                     // 1 + 2**-113 + 2**-227 rounds up
		{exact128(-0x1p-113), Float128{0x3ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}},                                    // 1 - 2**-113 + 2**-227
		{Float128{0xbf8d_0000_0000_0000, 0x0000_0000_0000_0001}, Float128{0x3ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}}, // -2**-114 × (1 + 2**-112)

		// overflow and underflow
		{exact128(11357), exact128(math.Inf(1))},
		{exact128(-11434), exact128(0)},
		{exact128(-11430), Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0010}},

		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(0)},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Exp()
		if !eq128(got, tt.want) {
			t.Errorf("Exp(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func TestFloat128_Exp2(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(-1), "0.5"},
		{exact128(0), "1"},
		{exact128(1), "2"},
		{exact128(1.5), "2.828427124746190097603377448419396157139343750753896146353359822541"},
	}

	for _, tt := range tests {
		got := tt.x.Exp2()
		if !close128(got, tt.want) {
			t.Errorf("Exp2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		{exact128(0), exact128(1)},
		{exact128(math.Copysign(0, -1)), exact128(1)},
		{exact128(10), exact128(1024)},
		{exact128(-1022), exact128(0x1p-1022)},

		// tiny values
		{exact128(0x1p-115), exact128(1)},
		{exact128(-0x1p-115), exact128(1)},
		{exact128(0x1p-113), exact128(1)},                                                                                // 1 + 0.69 × 2**-113 rounds down
		{exact128(0x1p-112), Float128{0x3fff_0000_0000_0000, 0x0000_0000_0000_0001}},                                     // 1 + 1.39 × 2**-113 rounds up
		{exact128(-0x1p-113), Float128{0x3ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}},                                    // 1 - 1.39 × 2**-114 rounds down
		{Float128{0xbf8d_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}, Float128{0x3ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}}, // -(2**-113 - 2**-227)

		// overflow and underflow
		{Float128{0x400c_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}, Float128{0x7ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_d3a3}}, // 16384 - 2**-99
		{exact128(16383), Float128{0x7ffe_0000_0000_0000, 0}},
		{exact128(16384), exact128(math.Inf(1))},
		{exact128(16385), exact128(math.Inf(1))},
		{exact128(-16382), Float128{0x0001_0000_0000_0000, 0}},
		{exact128(-16494), Float128{0, 1}},
		{exact128(-16495), exact128(0)}, // tie, round to even
		{exact128(-16494.5), Float128{0, 1}},
		{exact128(-16495.5), exact128(0)},
		{exact128(-16496), exact128(0)},

		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(0)},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Exp2()
		if !eq128(got, tt.want) {
			t.Errorf("Exp2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat128_ExpAccuracy checks that the error of Exp is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_exp_testdata.py.
func TestFloat128_ExpAccuracy(t *testing.T) {
	testFloat128Accuracy(t, "testdata/exp128.txt", "Exp", Float128.Exp)
}

// TestFloat128_Exp2Accuracy checks that the error of Exp2 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_exp_testdata.py.
func TestFloat128_Exp2Accuracy(t *testing.T) {
	testFloat128Accuracy(t, "testdata/exp2_128.txt", "Exp2", Float128.Exp2)
}

func testFloat128Accuracy(t *testing.T, name, fname string, fn func(Float128) Float128) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float128 {
		var x Float128
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float128) bool {
		inf := NewFloat128Inf(1)
		return eq128(got, want) || eq128(got, want.Nextafter(inf)) || eq128(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := fn(x)
		total++
		if !eq128(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("%s(%v) = %v; want %v", fname, x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	// The error bound is about 0.5 ulp + 2**-130 relative,
	// so the result may be misrounded if the exact value is very close to a midpoint.
	if misrounded*100 > total {
		t.Errorf("%s: %d of %d results are not correctly rounded; want at most 1%%", fname, misrounded, total)
	}
}

// benchFloat128 runs fn for each input as a sub-benchmark.
func benchFloat128(b *testing.B, fn func(Float128) Float128, inputs []struct {
	name string
	x    Float128
}) {
	for _, in := range inputs {
		b.Run(in.name, func(b *testing.B) {
			x := in.x
			for b.Loop() {
				runtime.KeepAlive(fn(x))
			}
		})
	}
}

func BenchmarkFloat128_Exp(b *testing.B) {
	benchFloat128(b, Float128.Exp, []struct {
		name string
		x    Float128
	}{
		{"tiny", exact128(0x1p-120)},      // rounds to 1
		{"small", exact128(0x1p-10)},      // |x| < ln(2)/128
		{"medium", exact128(1.5)},         // |x| < 16
		{"negative", exact128(-10.3)},     // the result is less than 1
		{"large", exact128(1000.7)},       // the reduction needs many bits of ln(2)
		{"subnormal", exact128(-11400.3)}, // the result is subnormal
	})
}

func BenchmarkFloat128_Exp2(b *testing.B) {
	benchFloat128(b, Float128.Exp2, []struct {
		name string
		x    Float128
	}{
		{"tiny", exact128(0x1p-120)},      // rounds to 1
		{"small", exact128(0x1p-10)},      // |x| < 1/128
		{"medium", exact128(1.5)},         // |x| < 16
		{"negative", exact128(-10.3)},     // the result is less than 1
		{"large", exact128(1000.7)},       // large exponent
		{"subnormal", exact128(-16400.3)}, // the result is subnormal
		{"integer", exact128(10)},         // the result is exact
	})
}
