package floats

import (
	"bufio"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat256_Exp(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(-1), "0.3678794411714423215955237701614608674458111310317678345078368016974614957448998033571472743459196437466273252768439952082469757928"},
		{exact256(0), "1"},
		{exact256(1), "2.718281828459045235360287471352662497757247093699959574966967627724076630353547594571382178525166427427466391932003059921817413597"},
		{exact256(2), "7.389056098930650227230427460575007813180315570551847324087127822522573796079057763384312485079121794773753161265478866123884603693"},
		{exact256(3), "20.08553692318766774092852965458171789698790783855415014437893422969884587809197373120449716025301770215360761585194900288181101248"},
		{exact256(4), "54.59815003314423907811026120286087840279073703861406872582659395855366209993586948167698056194473414278411544577108742781175710394"},
	}

	for _, tt := range tests {
		got := tt.x.Exp()
		if !close256(got, tt.want) {
			t.Errorf("Exp(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(1)},
		{exact256(math.Copysign(0, -1)), exact256(1)},

		// tiny values
		{Float256(uvone256).Ldexp(-239), exact256(1)},
		{Float256(uvone256).Ldexp(-239).Neg(), exact256(1)},
		{Float256(uvone256).Ldexp(-238), exact256(1)},
		{Float256(uvone256).Ldexp(-238).Neg(), exact256(1)},
		{Float256(uvone256).Ldexp(-237), Float256{0x3ffff00000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001}},
		{Float256(uvone256).Ldexp(-237).Neg(), Float256{0x3fffefffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff}},

		// overflow and underflow
		{exact256(181705), exact256(math.Inf(1))},
		{exact256(-181868), exact256(0)},
		{exact256(-181864), Float256{0, 0, 0, 0xd}},

		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(math.Inf(-1)), exact256(0)},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Exp()
		if !eq256(got, tt.want) {
			t.Errorf("Exp(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_ExpAccuracy checks that the error of Exp is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_exp_testdata.py.
func TestFloat256_ExpAccuracy(t *testing.T) {
	t.Parallel()
	testFloat256ExpAccuracy(t, "testdata/exp256.txt", "Exp", Float256.Exp)
}

func BenchmarkFloat256_Exp(b *testing.B) {
	benchFloat256Exp(b, Float256.Exp, []struct {
		name string
		x    Float256
	}{
		{"tiny", Float256(uvone256).Ldexp(-250)}, // rounds to 1
		{"small", exact256(0x1p-10)},             // |x| < ln(2)/128
		{"medium", exact256(1.5)},                // |x| < 16
		{"negative", exact256(-10.3)},            // the result is less than 1
		{"large", exact256(1000.7)},              // the reduction needs many bits of ln(2)
		{"subnormal", exact256(-181800.3)},       // the result is subnormal
	})
}

func TestFloat256_Exp2(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(-1), "0.5"},
		{exact256(0), "1"},
		{exact256(1), "2"},
		{exact256(1.5), "2.828427124746190097603377448419396157139343750753896146353359475981464956924214077700775068655283145470027692461824594049849672112"},
	}

	for _, tt := range tests {
		got := tt.x.Exp2()
		if !close256(got, tt.want) {
			t.Errorf("Exp2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(1)},
		{exact256(math.Copysign(0, -1)), exact256(1)},
		{exact256(10), exact256(1024)},

		// tiny values
		{Float256(uvone256).Ldexp(-239), exact256(1)},
		{Float256(uvone256).Ldexp(-239).Neg(), exact256(1)},
		{Float256(uvone256).Ldexp(-238), exact256(1)},
		{Float256(uvone256).Ldexp(-238).Neg(), exact256(1)},
		{Float256(uvone256).Ldexp(-237), exact256(1)},
		{Float256(uvone256).Ldexp(-237).Neg(), Float256{0x3fffefffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff}},
		{Float256(uvone256).Ldexp(-236), Float256{0x3ffff00000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001}},
		{Float256(uvone256).Ldexp(-236).Neg(), Float256{0x3fffefffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff}},

		// overflow and underflow
		{exact256(262143), Float256{0x7fffe00000000000, 0, 0, 0}},
		{exact256(262144), exact256(math.Inf(1))},
		{exact256(262145), exact256(math.Inf(1))},
		{exact256(-262142), Float256{0x0000100000000000, 0, 0, 0}},
		{exact256(-262378), Float256{0, 0, 0, 1}},
		{exact256(-262379), exact256(0)}, // tie, round to even
		{exact256(-262378.5), Float256{0, 0, 0, 1}},
		{exact256(-262379.5), exact256(0)},
		{exact256(-262380), exact256(0)},

		// near the overflow boundary, stressing the general reduction path
		{
			Float256{0x40010fffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff},
			Float256{0x7fffefffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xfffffffffffd3a38},
		},

		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(math.Inf(-1)), exact256(0)},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Exp2()
		if !eq256(got, tt.want) {
			t.Errorf("Exp2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_Exp2Accuracy checks that the error of Exp2 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_exp_testdata.py.
func TestFloat256_Exp2Accuracy(t *testing.T) {
	t.Parallel()
	testFloat256ExpAccuracy(t, "testdata/exp2_256.txt", "Exp2", Float256.Exp2)
}

func testFloat256ExpAccuracy(t *testing.T, name, fname string, fn func(Float256) Float256) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float256) bool {
		inf := NewFloat256Inf(1)
		return eq256(got, want) || eq256(got, want.Nextafter(inf)) || eq256(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := fn(x)
		total++
		if !eq256(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("%s(%v) = %v; want %v", fname, x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	// The error bound is about 0.5 ulp + 2**-258 relative,
	// so the result may be misrounded if the exact value is very close to a midpoint.
	if misrounded*100 > total {
		t.Errorf("%s: %d of %d results are not correctly rounded; want at most 1%%", fname, misrounded, total)
	}
}

// benchFloat256Exp runs fn for each input as a sub-benchmark.
func benchFloat256Exp(b *testing.B, fn func(Float256) Float256, inputs []struct {
	name string
	x    Float256
}) {
	for _, in := range inputs {
		b.Run(in.name, func(b *testing.B) {
			x := in.x
			for b.Loop() {
				runtime.KeepAlive(fn(x))
			}
		})
	}
}

func BenchmarkFloat256_Exp2(b *testing.B) {
	benchFloat256Exp(b, Float256.Exp2, []struct {
		name string
		x    Float256
	}{
		{"tiny", Float256(uvone256).Ldexp(-250)}, // rounds to 1
		{"small", exact256(0x1p-10)},             // |x| < 1/128
		{"medium", exact256(1.5)},                // |x| < 16
		{"negative", exact256(-10.3)},            // the result is less than 1
		{"large", exact256(1000.7)},              // large exponent
		{"subnormal", exact256(-262300.3)},       // the result is subnormal
		{"integer", exact256(10)},                // the result is exact
	})
}
