package floats

import (
	"bufio"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat128_Expm1(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(-0x1p24), "-1"},
		{exact128(-1), "-0.6321205588285576784044762298385391325541888689682321654921631983025385042551001966"},
		{exact128(-0x1p-24), "-5.96046429990338208927884783441062475300635261015299376854993634082159971776677455E-8"},
		{exact128(-0x1p-25), "-2.980232194360610706156728457749074378475050447510024450735796644104588740223894263E-8"},
		{exact128(0), "0"},
		{exact128(0x1p-25), "2.980232283178452676169258265480484667505915170034780254106203474178642385993634061E-8"},
		{exact128(0x1p-24), "5.960464655174749969329045951426788010322030160311252070356772304688050582038483484E-8"},
		{exact128(0.25), "0.2840254166877414840734205680624364583362808652814630892175072968722077658672380028"},
		{exact128(1), "1.718281828459045235360287471352662497757247093699959574966967627724076630353547595"},
		{exact128(10), "22025.46579480671651695790064528424436635351261855678107423542635522520281857079258"},
		{exact128(36), "4311231547115194.227113422292856925390788863616780347730770167843912372047055558563"},
		{exact128(62), "843835666874145448907332947.0373117960080692679667410404618178186988225756502453424"},
	}

	for _, tt := range tests {
		got := tt.x.Expm1()
		if !close128(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		{exact128(0), exact128(0)},
		{exact128(math.Copysign(0, -1)), exact128(math.Copysign(0, -1))},

		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(-1)},
		{exact128(math.NaN()), exact128(math.NaN())},

		// tiny values
		{exact128(0x1p-114), exact128(0x1p-114)},
		{exact128(-0x1p-114), exact128(-0x1p-114)},
		{Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}, Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}},

		// large values
		{exact128(-80), exact128(-1)},
		{exact128(-1000), exact128(-1)},
		{exact128(11357), exact128(math.Inf(1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Expm1()
		if !eq128(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat128_Expm1Accuracy checks that the error of Expm1 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_expm1_testdata.py.
func TestFloat128_Expm1Accuracy(t *testing.T) {
	f, err := os.Open("testdata/expm1_128.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float128 {
		var x Float128
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float128) bool {
		inf := NewFloat128Inf(1)
		return eq128(got, want) || eq128(got, want.Nextafter(inf)) || eq128(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := x.Expm1()
		total++
		if !eq128(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("Expm1(%v) = %v; want %v", x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	// The error bound is about 0.5 ulp + 2**-120 relative,
	// so the result may be misrounded if the exact value is very close to a midpoint.
	if misrounded*100 > total {
		t.Errorf("%d of %d results are not correctly rounded; want at most 1%%", misrounded, total)
	}
}

func BenchmarkFloat128_Expm1(b *testing.B) {
	b.Run("small", func(b *testing.B) {
		x := exact128(0x1p-10)
		for b.Loop() {
			runtime.KeepAlive(x.Expm1())
		}
	})
	b.Run("large", func(b *testing.B) {
		x := exact128(1.5)
		for b.Loop() {
			runtime.KeepAlive(x.Expm1())
		}
	})
}
