package floats

import (
	"bufio"
	"math"
	"math/big"
	"math/rand/v2"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/shogo82148/ints"
)

func TestFloat256_Expm1(t *testing.T) {
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(-0x1p24), "-1"},
		{exact256(-1), "-0.6321205588285576784044762298385391325541888689682321654921631983025385042551001966"},
		{exact256(-0x1p-24), "-5.96046429990338208927884783441062475300635261015299376854993634082159971776677455E-8"},
		{exact256(-0x1p-25), "-2.980232194360610706156728457749074378475050447510024450735796644104588740223894263E-8"},
		{exact256(-0x1p-238), "-2.263919769706678091877279822721947945170632799534784547395653722483875332210877641E-72"},
		{exact256(0), "0"},
		{exact256(0x1p-238), "2.263919769706678091877279822721947945170632799534784547395653722483875332210877641E-72"},
		{exact256(0x1p-25), "2.980232283178452676169258265480484667505915170034780254106203474178642385993634061E-8"},
		{exact256(0x1p-24), "5.960464655174749969329045951426788010322030160311252070356772304688050582038483484E-8"},
		{exact256(0.25), "0.2840254166877414840734205680624364583362808652814630892175072968722077658672380028"},
		{exact256(1), "1.718281828459045235360287471352662497757247093699959574966967627724076630353547595"},
		{exact256(10), "22025.46579480671651695790064528424436635351261855678107423542635522520281857079258"},
		{exact256(36), "4311231547115194.227113422292856925390788863616780347730770167843912372047055558563"},
		{exact256(62), "843835666874145448907332947.0373117960080692679667410404618178186988225756502453424"},
	}

	for _, tt := range tests {
		got := tt.x.Expm1()
		if !close256(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(0)},
		{exact256(math.Copysign(0, -1)), exact256(math.Copysign(0, -1))},

		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(math.Inf(-1)), exact256(-1)},
		{exact256(math.NaN()), exact256(math.NaN())},

		// tiny values
		{exact256(0x1p-238), exact256(0x1p-238)},
		{exact256(-0x1p-238), exact256(-0x1p-238)},
		{Float256{0, 0, 0, 1}, Float256{0, 0, 0, 1}},

		// large values
		{exact256(-166), exact256(-1)},
		{exact256(-1000), exact256(-1)},
		{exact256(181705), exact256(math.Inf(1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Expm1()
		if !eq256(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_Expm1Accuracy checks that the error of Expm1 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_expm1_testdata.py.
func TestFloat256_Expm1Accuracy(t *testing.T) {
	testFloat256Accuracy(t, "testdata/expm1_256.txt", "Expm1", Float256.Expm1)
}

func testFloat256Accuracy(t *testing.T, name, fname string, fn func(Float256) Float256) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float256) bool {
		inf := NewFloat256Inf(1)
		return eq256(got, want) || eq256(got, want.Nextafter(inf)) || eq256(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := fn(x)
		total++
		if !eq256(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("%s(%v) = %v; want %v", fname, x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	// The error bound is about 0.5 ulp + 2**-250 relative,
	// so the result may be misrounded if the exact value is very close to a midpoint.
	if misrounded*100 > total {
		t.Errorf("%s: %d of %d results are not correctly rounded; want at most 1%%", fname, misrounded, total)
	}
}

func BenchmarkFloat256_Expm1(b *testing.B) {
	benchFloat256(b, Float256.Expm1, []struct {
		name string
		x    Float256
	}{
		{"tiny", exact256(0x1p-240)},  // returns x
		{"small", exact256(0x1p-10)},  // |x| < ln(2)/128
		{"medium", exact256(1.5)},     // |x| < 16
		{"negative", exact256(-10.3)}, // the result is close to -1
		{"large", exact256(1000.7)},   // the reduction needs many bits of ln(2)
	})
}

// benchFloat256 runs fn for each input as a sub-benchmark.
func benchFloat256(b *testing.B, fn func(Float256) Float256, inputs []struct {
	name string
	x    Float256
}) {
	for _, in := range inputs {
		b.Run(in.name, func(b *testing.B) {
			x := in.x
			for b.Loop() {
				runtime.KeepAlive(fn(x))
			}
		})
	}
}

func TestFixToFloat256(t *testing.T) {
	const ones = 0xffff_ffff_ffff_ffff
	one := ints.Uint512{0, 0, 0, 0, 0, 0, 0, 1}
	all := ints.Uint512{ones, ones, ones, ones, ones, ones, ones, ones}
	tests := []struct {
		v      ints.Uint512
		sticky bool
		exp    int
		want   Float256
	}{
		// normal
		{one, false, 0, Float256(uvone256)},
		{one.Lsh(500), false, -500, Float256(uvone256)},
		{one.Lsh(500).Add(one.Lsh(263)), false, -500, Float256(uvone256)},                                         // tie, round to even
		{one.Lsh(500).Add(one.Lsh(263)), true, -500, Float256{0x3fff_f000_0000_0000, 0, 0, 1}},                    // above the tie
		{one.Lsh(500).Add(one.Lsh(263)).Add(one), false, -500, Float256{0x3fff_f000_0000_0000, 0, 0, 1}},          // above the tie
		{one.Lsh(500).Add(one.Lsh(263)).Add(one.Lsh(260)), false, -500, Float256{0x3fff_f000_0000_0000, 0, 0, 1}}, // above the tie
		{one.Lsh(500).Add(one.Lsh(263)).Add(one.Lsh(262)), false, -500, Float256{0x3fff_f000_0000_0000, 0, 0, 1}}, // above the tie
		{one.Lsh(500).Add(one.Lsh(264)).Add(one.Lsh(263)), false, -500, Float256{0x3fff_f000_0000_0000, 0, 0, 2}}, // tie, round to even
		{all, false, -511, Float256{0x4000_0000_0000_0000, 0, 0, 0}},                                              // carry to the exponent
		{all, false, 262144 - 512, Float256{0x7fff_f000_0000_0000, 0, 0, 0}},                                      // overflow
		{all.Rsh(275).Lsh(275), false, 262144 - 511, Float256{0x7fff_f000_0000_0000, 0, 0, 0}},                    // overflow
		{all.Rsh(275).Lsh(275), false, 262143 - 511, Float256{0x7fff_efff_ffff_ffff, ones, ones, ones}},           // max finite

		// subnormal
		{all, false, -262142 - 512, Float256{0x0000_1000_0000_0000, 0, 0, 0}}, // rounded up to the smallest normal number
		{one.Lsh(511), false, -262378 - 511, Float256{0, 0, 0, 1}},
		{one.Lsh(511), false, -262379 - 511, Float256{0, 0, 0, 0}}, // tie, round to even
		{one.Lsh(511).Add(one), false, -262379 - 511, Float256{0, 0, 0, 1}},
		{one.Lsh(511).Add(one.Lsh(200)), false, -262379 - 511, Float256{0, 0, 0, 1}},
		{one.Lsh(511), true, -262379 - 511, Float256{0, 0, 0, 1}},
		{one.Lsh(511).Add(one.Lsh(510)), false, -262378 - 511, Float256{0, 0, 0, 2}}, // 1.5 ulp, round to even
		{one.Lsh(511), false, -262380 - 511, Float256{0, 0, 0, 0}},
		{one, true, -263000, Float256{0, 0, 0, 0}},
	}
	for _, tt := range tests {
		got := fixToFloat256(0, tt.v, tt.sticky, tt.exp)
		if got != tt.want {
			t.Errorf("fixToFloat256(%x, %v, %d) = %#x; want %#x", tt.v, tt.sticky, tt.exp, got, tt.want)
		}
	}
}

func TestMul192x192(t *testing.T) {
	r := rand.New(rand.NewPCG(1, 2))
	toBig := func(x []uint64) *big.Int {
		v := new(big.Int)
		for _, w := range x {
			v.Lsh(v, 64)
			v.Or(v, new(big.Int).SetUint64(w))
		}
		return v
	}
	for range 10000 {
		var a, b [3]uint64
		for i := range a {
			// many all-one limbs to exercise the carries
			if r.IntN(2) == 0 {
				a[i] = ^uint64(0)
			} else {
				a[i] = r.Uint64()
			}
			if r.IntN(2) == 0 {
				b[i] = ^uint64(0)
			} else {
				b[i] = r.Uint64()
			}
		}
		got := mul192x192(a, b)
		want := new(big.Int).Mul(toBig(a[:]), toBig(b[:]))
		if toBig(got[:]).Cmp(want) != 0 {
			t.Errorf("mul192x192(%x, %x) = %x; want %x", a, b, got, want)
		}
	}
}
