package floats

import (
	"bufio"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestFloat128_Expm1(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(-0x1p24), "-1"},
		{exact128(-1), "-0.6321205588285576784044762298385391325541888689682321654921631983025385042551001966"},
		{exact128(-0x1p-24), "-5.96046429990338208927884783441062475300635261015299376854993634082159971776677455E-8"},
		{exact128(-0x1p-25), "-2.980232194360610706156728457749074378475050447510024450735796644104588740223894263E-8"},
		{exact128(0), "0"},
		{exact128(0x1p-25), "2.980232283178452676169258265480484667505915170034780254106203474178642385993634061E-8"},
		{exact128(0x1p-24), "5.960464655174749969329045951426788010322030160311252070356772304688050582038483484E-8"},
		{exact128(0.25), "0.2840254166877414840734205680624364583362808652814630892175072968722077658672380028"},
		{exact128(1), "1.718281828459045235360287471352662497757247093699959574966967627724076630353547595"},
		{exact128(10), "22025.46579480671651695790064528424436635351261855678107423542635522520281857079258"},
		{exact128(36), "4311231547115194.227113422292856925390788863616780347730770167843912372047055558563"},
		{exact128(62), "843835666874145448907332947.0373117960080692679667410404618178186988225756502453424"},
	}

	for _, tt := range tests {
		got := tt.x.Expm1()
		if !close128(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		{exact128(0), exact128(0)},
		{exact128(math.Copysign(0, -1)), exact128(math.Copysign(0, -1))},

		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(-1)},
		{exact128(math.NaN()), exact128(math.NaN())},

		// tiny values
		{exact128(0x1p-114), exact128(0x1p-114)},
		{exact128(-0x1p-114), exact128(-0x1p-114)},
		{Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}, Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}},

		// large values
		{exact128(-80), exact128(-1)},
		{exact128(-1000), exact128(-1)},
		{exact128(11357), exact128(math.Inf(1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Expm1()
		if !eq128(got, tt.want) {
			t.Errorf("Expm1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat128_Expm1Accuracy checks that the error of Expm1 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_expm1_testdata.py.
func TestFloat128_Expm1Accuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/expm1_128.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float128 {
		var x Float128
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float128) bool {
		inf := NewFloat128Inf(1)
		return eq128(got, want) || eq128(got, want.Nextafter(inf)) || eq128(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := x.Expm1()
		total++
		if !eq128(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("Expm1(%v) = %v; want %v", x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	// The error bound is about 0.5 ulp + 2**-120 relative,
	// so the result may be misrounded if the exact value is very close to a midpoint.
	if misrounded*100 > total {
		t.Errorf("%d of %d results are not correctly rounded; want at most 1%%", misrounded, total)
	}
}

func BenchmarkFloat128_Expm1(b *testing.B) {
	benchFloat128(b, Float128.Expm1, []struct {
		name string
		x    Float128
	}{
		{"tiny", exact128(0x1p-120)},  // returns x
		{"small", exact128(0x1p-10)},  // |x| < ln(2)/128
		{"medium", exact128(1.5)},     // |x| < 16
		{"negative", exact128(-10.3)}, // the result is close to -1
		{"large", exact128(1000.7)},   // the reduction needs many bits of ln(2)
	})
}

func TestFixToFloat128(t *testing.T) {
	t.Parallel()
	const ones = 0xffff_ffff_ffff_ffff
	tests := []struct {
		v2, v1, v0 uint64
		sticky     bool
		exp        int
		want       Float128
	}{
		// normal
		{1 << 63, 0, 0, false, -191, Float128(uvone128)},
		{1 << 63, 1 << 14, 0, false, -191, Float128(uvone128)},                                                       // tie, round to even
		{1 << 63, 1 << 14, 0, true, -191, Float128{0x3fff_0000_0000_0000, 1}},                                        // above the tie
		{1 << 63, 3 << 14, 0, false, -191, Float128{0x3fff_0000_0000_0000, 2}},                                       // tie, round to even
		{ones, ones, ones, false, -191, Float128{0x4000_0000_0000_0000, 0}},                                          // carry to the exponent
		{ones, ones, ones, false, 16384 - 192, Float128{0x7fff_0000_0000_0000, 0}},                                   // overflow
		{ones, 0xffff_ffff_ffff_8000, 0, false, 16383 - 191, Float128{0x7ffe_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}}, // max finite

		// subnormal
		{ones, ones, ones, false, -16382 - 192, Float128{0x0001_0000_0000_0000, 0}}, // rounded up to the smallest normal number
		{1 << 63, 0, 0, false, -16494 - 191, Float128{0, 1}},
		{1 << 63, 0, 0, false, -16495 - 191, Float128{0, 0}}, // tie, round to even
		{1 << 63, 0, 1, false, -16495 - 191, Float128{0, 1}},
		{1 << 63, 0, 0, true, -16495 - 191, Float128{0, 1}},
		{1 << 63, 1, 0, false, -16495 - 191, Float128{0, 1}},
		{3 << 62, 0, 0, false, -16494 - 191, Float128{0, 2}}, // 1.5 ulp, round to even
		{1 << 63, 0, 0, false, -16496 - 191, Float128{0, 0}},
	}
	for _, tt := range tests {
		got := fixToFloat128(0, tt.v2, tt.v1, tt.v0, tt.sticky, tt.exp)
		if got != tt.want {
			t.Errorf("fixToFloat128(%#x, %#x, %#x, %v, %d) = %#x; want %#x", tt.v2, tt.v1, tt.v0, tt.sticky, tt.exp, got, tt.want)
		}
	}
}
