package floats

import (
	"math"
	"math/bits"

	"github.com/shogo82148/ints"
)

const (
	uvnan16    = 0x7e00     // NaN value for Float16
	uvinf16    = 0x7c00     // Infinity value for Float16
	uvneginf16 = 0xfc00     // Negative Infinity value for Float16
	uvone16    = 0x3c00     // One value for Float16
	mask16     = 0x1f       // mask for exponent
	shift16    = 16 - 5 - 1 // shift for exponent
	bias16     = 15         // bias for exponent
	signMask16 = 1 << 15    // mask for sign bit
	fracMask16 = 1<<shift16 - 1
)

// Float16 is a 16-bit floating-point number.
type Float16 uint16

// NewFloat16 converts f to Float16.
func NewFloat16(f float64) Float16 {
	return Float64(f).Float16()
}

// NewFloat16FromBits converts the IEEE 754 binary representation b to Float16.
func NewFloat16FromBits(b uint16) Float16 {
	return Float16(b)
}

// NewFloat16NaN returns a NaN Float16 value.
func NewFloat16NaN() Float16 {
	return uvnan16
}

// NewFloat16Inf positive infinity if sign >= 0, negative infinity if sign < 0.
func NewFloat16Inf(sign int) Float16 {
	if sign >= 0 {
		return uvinf16
	}
	return uvneginf16
}

// Bits returns the IEEE 754 binary representation of a.
func (a Float16) Bits() uint16 {
	return uint16(a)
}

// IsNaN reports whether a is an IEEE 754 “not-a-number” value.
func (a Float16) IsNaN() bool {
	return a&(mask16<<shift16) == (mask16<<shift16) && a&fracMask16 != 0
}

// IsInf reports whether a is an infinity, according to sign.
// If sign > 0, IsInf reports whether a is positive infinity.
// If sign < 0, IsInf reports whether a is negative infinity.
// If sign == 0, IsInf reports whether a is either infinity.
func (a Float16) IsInf(sign int) bool {
	return sign >= 0 && a == uvinf16 || sign <= 0 && a == uvneginf16
}

// Signbit reports whether x is negative or negative zero.
func (a Float16) Signbit() bool {
	return a&signMask16 != 0
}

// Copysign returns a value with the magnitude of a
// and the sign of sign.
func (a Float16) Copysign(sign Float16) Float16 {
	return (a &^ signMask16) | (sign & signMask16)
}

// Int64 returns the integer value of a, rounding towards zero.
// If a cannot be represented in an int64, the result is undefined.
func (a Float16) Int64() int64 {
	return int64(a.Float64())
}

// Uint64 returns the unsigned integer value of a, rounding towards zero.
// If a cannot be represented in a uint64, the result is undefined.
func (a Float16) Uint64() uint64 {
	return uint64(a.Float64())
}

// Int128 returns the signed 128-bit integer value of a, rounding towards zero.
// If a cannot be represented in a int128, the result is undefined.
func (a Float16) Int128() ints.Int128 {
	// The maximum value of Float16 is 65504, so it will not exceed the range of Int64.
	// Therefore, this conversion is safe.
	ret := ints.Int64(a.Int64())

	return ret.Int128()
}

// Uint128 returns the unsigned 128-bit integer value of a, rounding towards zero.
// If a cannot be represented in a uint128, the result is undefined.
func (a Float16) Uint128() ints.Uint128 {
	// The maximum value of Float16 is 65504, so it will not exceed the range of Uint64.
	// Therefore, this conversion is safe.
	ret := ints.Uint64(a.Uint64())

	return ret.Uint128()
}

// Int256 returns the signed 256-bit integer value of a, rounding towards zero.
// If a cannot be represented in a int256, the result is undefined.
func (a Float16) Int256() ints.Int256 {
	// The maximum value of Float16 is 65504, so it will not exceed the range of Int64.
	// Therefore, this conversion is safe.
	ret := ints.Int64(a.Int64())

	return ret.Int256()
}

// Uint256 returns the unsigned 256-bit integer value of a, rounding towards zero.
// If a cannot be represented in a uint256, the result is undefined.
func (a Float16) Uint256() ints.Uint256 {
	// The maximum value of Float16 is 65504, so it will not exceed the range of Uint64.
	// Therefore, this conversion is safe.
	ret := ints.Uint64(a.Uint64())

	return ret.Uint256()
}

// IsZero reports whether a is zero (+0 or -0).
func (a Float16) IsZero() bool {
	return a&^signMask16 == 0
}

// Neg returns the negation of a.
func (a Float16) Neg() Float16 {
	return a ^ signMask16
}

// Abs returns the absolute value of a.
//
// Special cases:
//
//	Abs(±Inf) = +Inf
//	Abs(NaN) = NaN
func (a Float16) Abs() Float16 {
	return a &^ signMask16
}

// Mul returns the product of a and b.
func (a Float16) Mul(b Float16) Float16 {
	// The product of two Float16 values has 22 bits, so it is exact in float32.
	// Rounding it again to 11 bits is the same as rounding once, because 24 >= 2*11+2.
	r := Float32(float32(a.Float32()) * float32(b.Float32())).Float16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnan16
	}
	return r
}

// Quo returns the quotient of a and b.
func (a Float16) Quo(b Float16) Float16 {
	// Rounding the float32 quotient again to 11 bits is the same as rounding once,
	// because 24 >= 2*11+2.
	r := Float32(float32(a.Float32()) / float32(b.Float32())).Float16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnan16
	}
	return r
}

// Add returns the sum of a and b.
func (a Float16) Add(b Float16) Float16 {
	// Rounding the float32 sum again to 11 bits is the same as rounding once,
	// because 24 >= 2*11+2.
	r := Float32(float32(a.Float32()) + float32(b.Float32())).Float16()
	if r.IsNaN() {
		// The sign and the payload of the NaN generated by the FPU depend on the architecture.
		return uvnan16
	}
	return r
}

// Sub returns the difference of a and b.
func (a Float16) Sub(b Float16) Float16 {
	return a.Add(b.Neg())
}

// Sqrt returns the square root of a.
//
// Special cases are:
//
//	Sqrt(+Inf) = +Inf
//	Sqrt(±0) = ±0
//	Sqrt(x < 0) = NaN
//	Sqrt(NaN) = NaN
func (a Float16) Sqrt() Float16 {
	// special cases
	switch {
	case a.IsZero() || a.IsNaN() || a.IsInf(1):
		return a
	case a&signMask16 != 0:
		return uvnan16
	}

	// The square root in float64 is correctly rounded, and rounding it again to 11 bits
	// is the same as rounding once, because 53 >= 2*11+2.
	return Float64(math.Sqrt(float64(a.Float32()))).Float16()
}

// Eq returns a == b.
// NaNs are not equal to anything, including NaN.
// -0.0 and 0.0 are equal.
func (a Float16) Eq(b Float16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	if a == b {
		// a and b have the same bit pattern.
		return true
	}

	// check -0 == 0
	return (a|b)&^signMask16 == 0
}

// Ne returns a != b.
// NaNs are not equal to anything, including NaN.
// -0.0 and 0.0 are equal.
func (a Float16) Ne(b Float16) bool {
	return !a.Eq(b)
}

// Lt returns a < b.
//
// Special cases are:
//
//	Lt(NaN, x) == false
//	Lt(x, NaN) == false
func (a Float16) Lt(b Float16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	return a.comparable() < b.comparable()
}

// Gt returns a > b.
//
// Special cases are:
//
//	Gt(x, NaN) == false
//	Gt(NaN, x) == false
func (a Float16) Gt(b Float16) bool {
	return b.Lt(a)
}

// Le returns a <= b.
//
// Special cases are:
//
//	Le(x, NaN) == false
//	Le(NaN, x) == false
func (a Float16) Le(b Float16) bool {
	if a.IsNaN() || b.IsNaN() {
		return false
	}
	return a.comparable() <= b.comparable()
}

// Ge returns a >= b.
//
// Special cases are:
//
//	Ge(x, NaN) == false
//	Ge(NaN, x) == false
func (a Float16) Ge(b Float16) bool {
	return b.Le(a)
}

// normalize returns the sign, exponent, and normalized fraction of a.
func (a Float16) normalize() (sign uint16, exp int, frac uint16) {
	sign = uint16(a & signMask16)
	exp = int((a>>shift16)&mask16) - bias16
	frac = uint16(a & fracMask16)

	if exp == -bias16 {
		// a is subnormal
		// normalize
		l := bits.Len16(frac)
		frac <<= uint(shift16 + 1 - l)
		exp = l - (bias16 + shift16)
		return
	}

	// a is normal
	frac |= 1 << shift16
	return
}

func (a Float16) split() (sign uint16, exp int, frac uint16) {
	sign = uint16(a & signMask16)
	exp = int((a>>shift16)&mask16) - bias16
	frac = uint16(a & fracMask16)

	if exp == -bias16 {
		// a is subnormal
		exp++
	} else {
		// a is normal
		frac |= 1 << shift16
	}
	return
}

// comparable converts a to a comparable form.
func (a Float16) comparable() int16 {
	i := int16(a)
	i ^= (i >> 15) & 0x7fff
	i += int16(a >> 15) // normalize -0 to 0
	return i
}

// FMA16 returns x * y + z, computed with only one rounding.
// (That is, FMA16 returns the fused multiply-add of x, y, and z.)
func FMA16(x, y, z Float16) Float16 {
	// The product of two float16 values has 22 bits, and it is exact in float64.
	// The sum p + z is exact unless the exponents of p and z are very different:
	// then either |p| >= 2^19 and the result overflows whatever z is,
	// or |p| < 2^-32 |z| and the result is z, which is on the float16 grid,
	// so the sum never rounds twice in a way that changes the result.
	p := float64(x.Float32()) * float64(y.Float32())
	return Float64(p + float64(z.Float32())).Float16()
}

// Nextafter returns the next representable float16 value after a towards b.
//
// Special cases are:
//
//	a.Nextafter(a)   = a
//	NaN.Nextafter(b) = NaN
//	a.Nextafter(NaN) = NaN
func (a Float16) Nextafter(b Float16) (r Float16) {
	switch {
	case a.IsNaN() || b.IsNaN(): // special case
		r = NewFloat16NaN()
	case a == b: // special case
		r = a
	case a.IsZero():
		r = Float16(1).Copysign(b)
	case b.Gt(a) == a.Gt(0):
		r = a + 1
	default:
		r = a - 1
	}
	return
}

// Modf returns integer and fractional floating-point numbers
// that sum to f. Both values have the same sign as f.
//
// Special cases are:
//
//	Modf(±Inf) = ±Inf, NaN
//	Modf(NaN) = NaN, NaN
func (a Float16) Modf() (int Float16, frac Float16) {
	if optimized {
		fint, ffrac := math.Modf(a.Float64().BuiltIn())
		return NewFloat16(fint), NewFloat16(ffrac)
	}

	if a.Lt(Float16(uvone16)) { // a < 1
		switch {
		case a.Lt(Float16(0)): // a < 0
			int, frac = a.Neg().Modf()
			return int.Neg(), frac.Neg()
		case a.IsZero(): // a == 0
			return a, a
		default: // 0 < a < 1
			return Float16(0), a
		}
	}

	int = a
	e := uint(int>>shift16&mask16) - bias16

	// Keep the top 6+e bits, the integer part; clear the rest.
	if e < shift16 {
		int &^= 1<<(shift16-e) - 1
	}
	frac = a.Sub(int)
	return
}

// Frexp breaks a into a normalized fraction
// and an integral power of two.
// It returns frac and exp satisfying f == frac × 2**exp,
// with the absolute value of frac in the interval [½, 1).
//
// Special cases are:
//
//	±0.Frexp() = ±0, 0
//	±Inf.Frexp() = ±Inf, 0
//	NaN.Frexp() = NaN, 0
func (a Float16) Frexp() (frac Float16, exp int) {
	f, e := math.Frexp(a.Float64().BuiltIn())
	return NewFloat16(f), e
}

// Ldexp is the inverse of [Frexp].
// It returns a × 2**exp.
//
// Special cases are:
//
//	±0.Ldexp(exp) = ±0
//	±Inf.Ldexp(exp) = ±Inf
//	NaN.Ldexp(exp) = NaN
func (a Float16) Ldexp(exp int) Float16 {
	f := math.Ldexp(a.Float64().BuiltIn(), exp)
	return NewFloat16(f)
}

// Mod returns the floating-point remainder of a/b.
// The magnitude of the result is less than b and its
// sign agrees with that of a.
//
// Special cases are:
//
//	±Inf.Mod(b) = NaN
//	NaN.Mod(b) = NaN
//	a.Mod(0) = NaN
//	a.Mod(±Inf) = a
//	a.Mod(NaN) = NaN
func (a Float16) Mod(b Float16) Float16 {
	return NewFloat16(math.Mod(a.Float64().BuiltIn(), b.Float64().BuiltIn()))
}

// Remainder returns the IEEE 754 floating-point remainder of a/b.
//
// Special cases are:
//
//	±Inf.Remainder(b) = NaN
//	NaN.Remainder(b) = NaN
//	a.Remainder(0) = NaN
//	a.Remainder(±Inf) = a
//	a.Remainder(NaN) = NaN
func (a Float16) Remainder(b Float16) Float16 {
	return NewFloat16(math.Remainder(a.Float64().BuiltIn(), b.Float64().BuiltIn()))
}
