// Code generated by scripts/gen_gamma256_mul.py; DO NOT EDIT.

package floats

import "math/bits"

// gammaMul256n2 returns about a × b from the upper 2 words of a and b, that is, with 64 fractional bits.
func gammaMul256n2(a, b *gammaFix256) gammaFix256 {
	var r gammaFix256
	var c0, c1, c2, cy uint64
	// the position 2
	h11, l11 := bits.Mul64(a[1], b[1])
	c0, cy = bits.Add64(c0, l11, 0)
	c1, cy = bits.Add64(c1, h11, cy)
	c2 += cy
	c0, c1, c2 = c1, c2, 0
	// the position 1
	h01, l01 := bits.Mul64(a[0], b[1])
	c0, cy = bits.Add64(c0, l01, 0)
	c1, cy = bits.Add64(c1, h01, cy)
	c2 += cy
	h10, l10 := bits.Mul64(a[1], b[0])
	c0, cy = bits.Add64(c0, l10, 0)
	c1, cy = bits.Add64(c1, h10, cy)
	c2 += cy
	r[1] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 0
	h00, l00 := bits.Mul64(a[0], b[0])
	c0, cy = bits.Add64(c0, l00, 0)
	c1, cy = bits.Add64(c1, h00, cy)
	c2 += cy
	r[0] = c0
	c0, c1, c2 = c1, c2, 0
	return r
}

// gammaMul256n3 returns about a × b from the upper 3 words of a and b, that is, with 128 fractional bits.
func gammaMul256n3(a, b *gammaFix256) gammaFix256 {
	var r gammaFix256
	var c0, c1, c2, cy uint64
	h22, _ := bits.Mul64(a[2], b[2])
	c0, cy = bits.Add64(c0, h22, 0)
	c1 += cy
	// the position 3
	h12, l12 := bits.Mul64(a[1], b[2])
	c0, cy = bits.Add64(c0, l12, 0)
	c1, cy = bits.Add64(c1, h12, cy)
	c2 += cy
	h21, l21 := bits.Mul64(a[2], b[1])
	c0, cy = bits.Add64(c0, l21, 0)
	c1, cy = bits.Add64(c1, h21, cy)
	c2 += cy
	c0, c1, c2 = c1, c2, 0
	// the position 2
	h02, l02 := bits.Mul64(a[0], b[2])
	c0, cy = bits.Add64(c0, l02, 0)
	c1, cy = bits.Add64(c1, h02, cy)
	c2 += cy
	h11, l11 := bits.Mul64(a[1], b[1])
	c0, cy = bits.Add64(c0, l11, 0)
	c1, cy = bits.Add64(c1, h11, cy)
	c2 += cy
	h20, l20 := bits.Mul64(a[2], b[0])
	c0, cy = bits.Add64(c0, l20, 0)
	c1, cy = bits.Add64(c1, h20, cy)
	c2 += cy
	r[2] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 1
	h01, l01 := bits.Mul64(a[0], b[1])
	c0, cy = bits.Add64(c0, l01, 0)
	c1, cy = bits.Add64(c1, h01, cy)
	c2 += cy
	h10, l10 := bits.Mul64(a[1], b[0])
	c0, cy = bits.Add64(c0, l10, 0)
	c1, cy = bits.Add64(c1, h10, cy)
	c2 += cy
	r[1] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 0
	h00, l00 := bits.Mul64(a[0], b[0])
	c0, cy = bits.Add64(c0, l00, 0)
	c1, cy = bits.Add64(c1, h00, cy)
	c2 += cy
	r[0] = c0
	c0, c1, c2 = c1, c2, 0
	return r
}

// gammaMul256n4 returns about a × b from the upper 4 words of a and b, that is, with 192 fractional bits.
func gammaMul256n4(a, b *gammaFix256) gammaFix256 {
	var r gammaFix256
	var c0, c1, c2, cy uint64
	h23, _ := bits.Mul64(a[2], b[3])
	c0, cy = bits.Add64(c0, h23, 0)
	c1 += cy
	h32, _ := bits.Mul64(a[3], b[2])
	c0, cy = bits.Add64(c0, h32, 0)
	c1 += cy
	// the position 4
	h13, l13 := bits.Mul64(a[1], b[3])
	c0, cy = bits.Add64(c0, l13, 0)
	c1, cy = bits.Add64(c1, h13, cy)
	c2 += cy
	h22, l22 := bits.Mul64(a[2], b[2])
	c0, cy = bits.Add64(c0, l22, 0)
	c1, cy = bits.Add64(c1, h22, cy)
	c2 += cy
	h31, l31 := bits.Mul64(a[3], b[1])
	c0, cy = bits.Add64(c0, l31, 0)
	c1, cy = bits.Add64(c1, h31, cy)
	c2 += cy
	c0, c1, c2 = c1, c2, 0
	// the position 3
	h03, l03 := bits.Mul64(a[0], b[3])
	c0, cy = bits.Add64(c0, l03, 0)
	c1, cy = bits.Add64(c1, h03, cy)
	c2 += cy
	h12, l12 := bits.Mul64(a[1], b[2])
	c0, cy = bits.Add64(c0, l12, 0)
	c1, cy = bits.Add64(c1, h12, cy)
	c2 += cy
	h21, l21 := bits.Mul64(a[2], b[1])
	c0, cy = bits.Add64(c0, l21, 0)
	c1, cy = bits.Add64(c1, h21, cy)
	c2 += cy
	h30, l30 := bits.Mul64(a[3], b[0])
	c0, cy = bits.Add64(c0, l30, 0)
	c1, cy = bits.Add64(c1, h30, cy)
	c2 += cy
	r[3] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 2
	h02, l02 := bits.Mul64(a[0], b[2])
	c0, cy = bits.Add64(c0, l02, 0)
	c1, cy = bits.Add64(c1, h02, cy)
	c2 += cy
	h11, l11 := bits.Mul64(a[1], b[1])
	c0, cy = bits.Add64(c0, l11, 0)
	c1, cy = bits.Add64(c1, h11, cy)
	c2 += cy
	h20, l20 := bits.Mul64(a[2], b[0])
	c0, cy = bits.Add64(c0, l20, 0)
	c1, cy = bits.Add64(c1, h20, cy)
	c2 += cy
	r[2] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 1
	h01, l01 := bits.Mul64(a[0], b[1])
	c0, cy = bits.Add64(c0, l01, 0)
	c1, cy = bits.Add64(c1, h01, cy)
	c2 += cy
	h10, l10 := bits.Mul64(a[1], b[0])
	c0, cy = bits.Add64(c0, l10, 0)
	c1, cy = bits.Add64(c1, h10, cy)
	c2 += cy
	r[1] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 0
	h00, l00 := bits.Mul64(a[0], b[0])
	c0, cy = bits.Add64(c0, l00, 0)
	c1, cy = bits.Add64(c1, h00, cy)
	c2 += cy
	r[0] = c0
	c0, c1, c2 = c1, c2, 0
	return r
}

// gammaMul256n5 returns about a × b from the upper 5 words of a and b, that is, with 256 fractional bits.
func gammaMul256n5(a, b *gammaFix256) gammaFix256 {
	var r gammaFix256
	var c0, c1, c2, cy uint64
	h24, _ := bits.Mul64(a[2], b[4])
	c0, cy = bits.Add64(c0, h24, 0)
	c1 += cy
	h33, _ := bits.Mul64(a[3], b[3])
	c0, cy = bits.Add64(c0, h33, 0)
	c1 += cy
	h42, _ := bits.Mul64(a[4], b[2])
	c0, cy = bits.Add64(c0, h42, 0)
	c1 += cy
	// the position 5
	h14, l14 := bits.Mul64(a[1], b[4])
	c0, cy = bits.Add64(c0, l14, 0)
	c1, cy = bits.Add64(c1, h14, cy)
	c2 += cy
	h23, l23 := bits.Mul64(a[2], b[3])
	c0, cy = bits.Add64(c0, l23, 0)
	c1, cy = bits.Add64(c1, h23, cy)
	c2 += cy
	h32, l32 := bits.Mul64(a[3], b[2])
	c0, cy = bits.Add64(c0, l32, 0)
	c1, cy = bits.Add64(c1, h32, cy)
	c2 += cy
	h41, l41 := bits.Mul64(a[4], b[1])
	c0, cy = bits.Add64(c0, l41, 0)
	c1, cy = bits.Add64(c1, h41, cy)
	c2 += cy
	c0, c1, c2 = c1, c2, 0
	// the position 4
	h04, l04 := bits.Mul64(a[0], b[4])
	c0, cy = bits.Add64(c0, l04, 0)
	c1, cy = bits.Add64(c1, h04, cy)
	c2 += cy
	h13, l13 := bits.Mul64(a[1], b[3])
	c0, cy = bits.Add64(c0, l13, 0)
	c1, cy = bits.Add64(c1, h13, cy)
	c2 += cy
	h22, l22 := bits.Mul64(a[2], b[2])
	c0, cy = bits.Add64(c0, l22, 0)
	c1, cy = bits.Add64(c1, h22, cy)
	c2 += cy
	h31, l31 := bits.Mul64(a[3], b[1])
	c0, cy = bits.Add64(c0, l31, 0)
	c1, cy = bits.Add64(c1, h31, cy)
	c2 += cy
	h40, l40 := bits.Mul64(a[4], b[0])
	c0, cy = bits.Add64(c0, l40, 0)
	c1, cy = bits.Add64(c1, h40, cy)
	c2 += cy
	r[4] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 3
	h03, l03 := bits.Mul64(a[0], b[3])
	c0, cy = bits.Add64(c0, l03, 0)
	c1, cy = bits.Add64(c1, h03, cy)
	c2 += cy
	h12, l12 := bits.Mul64(a[1], b[2])
	c0, cy = bits.Add64(c0, l12, 0)
	c1, cy = bits.Add64(c1, h12, cy)
	c2 += cy
	h21, l21 := bits.Mul64(a[2], b[1])
	c0, cy = bits.Add64(c0, l21, 0)
	c1, cy = bits.Add64(c1, h21, cy)
	c2 += cy
	h30, l30 := bits.Mul64(a[3], b[0])
	c0, cy = bits.Add64(c0, l30, 0)
	c1, cy = bits.Add64(c1, h30, cy)
	c2 += cy
	r[3] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 2
	h02, l02 := bits.Mul64(a[0], b[2])
	c0, cy = bits.Add64(c0, l02, 0)
	c1, cy = bits.Add64(c1, h02, cy)
	c2 += cy
	h11, l11 := bits.Mul64(a[1], b[1])
	c0, cy = bits.Add64(c0, l11, 0)
	c1, cy = bits.Add64(c1, h11, cy)
	c2 += cy
	h20, l20 := bits.Mul64(a[2], b[0])
	c0, cy = bits.Add64(c0, l20, 0)
	c1, cy = bits.Add64(c1, h20, cy)
	c2 += cy
	r[2] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 1
	h01, l01 := bits.Mul64(a[0], b[1])
	c0, cy = bits.Add64(c0, l01, 0)
	c1, cy = bits.Add64(c1, h01, cy)
	c2 += cy
	h10, l10 := bits.Mul64(a[1], b[0])
	c0, cy = bits.Add64(c0, l10, 0)
	c1, cy = bits.Add64(c1, h10, cy)
	c2 += cy
	r[1] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 0
	h00, l00 := bits.Mul64(a[0], b[0])
	c0, cy = bits.Add64(c0, l00, 0)
	c1, cy = bits.Add64(c1, h00, cy)
	c2 += cy
	r[0] = c0
	c0, c1, c2 = c1, c2, 0
	return r
}

// gammaMul256n6 returns about a × b from the upper 6 words of a and b, that is, with 320 fractional bits.
func gammaMul256n6(a, b *gammaFix256) gammaFix256 {
	var r gammaFix256
	var c0, c1, c2, cy uint64
	h25, _ := bits.Mul64(a[2], b[5])
	c0, cy = bits.Add64(c0, h25, 0)
	c1 += cy
	h34, _ := bits.Mul64(a[3], b[4])
	c0, cy = bits.Add64(c0, h34, 0)
	c1 += cy
	h43, _ := bits.Mul64(a[4], b[3])
	c0, cy = bits.Add64(c0, h43, 0)
	c1 += cy
	h52, _ := bits.Mul64(a[5], b[2])
	c0, cy = bits.Add64(c0, h52, 0)
	c1 += cy
	// the position 6
	h15, l15 := bits.Mul64(a[1], b[5])
	c0, cy = bits.Add64(c0, l15, 0)
	c1, cy = bits.Add64(c1, h15, cy)
	c2 += cy
	h24, l24 := bits.Mul64(a[2], b[4])
	c0, cy = bits.Add64(c0, l24, 0)
	c1, cy = bits.Add64(c1, h24, cy)
	c2 += cy
	h33, l33 := bits.Mul64(a[3], b[3])
	c0, cy = bits.Add64(c0, l33, 0)
	c1, cy = bits.Add64(c1, h33, cy)
	c2 += cy
	h42, l42 := bits.Mul64(a[4], b[2])
	c0, cy = bits.Add64(c0, l42, 0)
	c1, cy = bits.Add64(c1, h42, cy)
	c2 += cy
	h51, l51 := bits.Mul64(a[5], b[1])
	c0, cy = bits.Add64(c0, l51, 0)
	c1, cy = bits.Add64(c1, h51, cy)
	c2 += cy
	c0, c1, c2 = c1, c2, 0
	// the position 5
	h05, l05 := bits.Mul64(a[0], b[5])
	c0, cy = bits.Add64(c0, l05, 0)
	c1, cy = bits.Add64(c1, h05, cy)
	c2 += cy
	h14, l14 := bits.Mul64(a[1], b[4])
	c0, cy = bits.Add64(c0, l14, 0)
	c1, cy = bits.Add64(c1, h14, cy)
	c2 += cy
	h23, l23 := bits.Mul64(a[2], b[3])
	c0, cy = bits.Add64(c0, l23, 0)
	c1, cy = bits.Add64(c1, h23, cy)
	c2 += cy
	h32, l32 := bits.Mul64(a[3], b[2])
	c0, cy = bits.Add64(c0, l32, 0)
	c1, cy = bits.Add64(c1, h32, cy)
	c2 += cy
	h41, l41 := bits.Mul64(a[4], b[1])
	c0, cy = bits.Add64(c0, l41, 0)
	c1, cy = bits.Add64(c1, h41, cy)
	c2 += cy
	h50, l50 := bits.Mul64(a[5], b[0])
	c0, cy = bits.Add64(c0, l50, 0)
	c1, cy = bits.Add64(c1, h50, cy)
	c2 += cy
	r[5] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 4
	h04, l04 := bits.Mul64(a[0], b[4])
	c0, cy = bits.Add64(c0, l04, 0)
	c1, cy = bits.Add64(c1, h04, cy)
	c2 += cy
	h13, l13 := bits.Mul64(a[1], b[3])
	c0, cy = bits.Add64(c0, l13, 0)
	c1, cy = bits.Add64(c1, h13, cy)
	c2 += cy
	h22, l22 := bits.Mul64(a[2], b[2])
	c0, cy = bits.Add64(c0, l22, 0)
	c1, cy = bits.Add64(c1, h22, cy)
	c2 += cy
	h31, l31 := bits.Mul64(a[3], b[1])
	c0, cy = bits.Add64(c0, l31, 0)
	c1, cy = bits.Add64(c1, h31, cy)
	c2 += cy
	h40, l40 := bits.Mul64(a[4], b[0])
	c0, cy = bits.Add64(c0, l40, 0)
	c1, cy = bits.Add64(c1, h40, cy)
	c2 += cy
	r[4] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 3
	h03, l03 := bits.Mul64(a[0], b[3])
	c0, cy = bits.Add64(c0, l03, 0)
	c1, cy = bits.Add64(c1, h03, cy)
	c2 += cy
	h12, l12 := bits.Mul64(a[1], b[2])
	c0, cy = bits.Add64(c0, l12, 0)
	c1, cy = bits.Add64(c1, h12, cy)
	c2 += cy
	h21, l21 := bits.Mul64(a[2], b[1])
	c0, cy = bits.Add64(c0, l21, 0)
	c1, cy = bits.Add64(c1, h21, cy)
	c2 += cy
	h30, l30 := bits.Mul64(a[3], b[0])
	c0, cy = bits.Add64(c0, l30, 0)
	c1, cy = bits.Add64(c1, h30, cy)
	c2 += cy
	r[3] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 2
	h02, l02 := bits.Mul64(a[0], b[2])
	c0, cy = bits.Add64(c0, l02, 0)
	c1, cy = bits.Add64(c1, h02, cy)
	c2 += cy
	h11, l11 := bits.Mul64(a[1], b[1])
	c0, cy = bits.Add64(c0, l11, 0)
	c1, cy = bits.Add64(c1, h11, cy)
	c2 += cy
	h20, l20 := bits.Mul64(a[2], b[0])
	c0, cy = bits.Add64(c0, l20, 0)
	c1, cy = bits.Add64(c1, h20, cy)
	c2 += cy
	r[2] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 1
	h01, l01 := bits.Mul64(a[0], b[1])
	c0, cy = bits.Add64(c0, l01, 0)
	c1, cy = bits.Add64(c1, h01, cy)
	c2 += cy
	h10, l10 := bits.Mul64(a[1], b[0])
	c0, cy = bits.Add64(c0, l10, 0)
	c1, cy = bits.Add64(c1, h10, cy)
	c2 += cy
	r[1] = c0
	c0, c1, c2 = c1, c2, 0
	// the position 0
	h00, l00 := bits.Mul64(a[0], b[0])
	c0, cy = bits.Add64(c0, l00, 0)
	c1, cy = bits.Add64(c1, h00, cy)
	c2 += cy
	r[0] = c0
	c0, c1, c2 = c1, c2, 0
	return r
}
