// Code generated by scripts/gen_lgamma128_table.py; DO NOT EDIT.

package floats

// lgamma128Taylor[k-1] is |c_k|, the coefficient of the Taylor series of Lgamma(1+x) = sum c_k x**k,
// in fixed point with 192 fractional bits. c_1 = -gamma, c_k = (-1)**k zeta(k)/k.
var lgamma128Taylor = [...][4]uint64{
	{0x0000000000000000, 0x93c467e37db0c7a4, 0xd1be3f810152cb56, 0xa1cecc3af65cc019}, // k = 1
	{0x0000000000000000, 0xd28d3312983e9918, 0x73d8912200bace5e, 0xb5c88daa81162d8b}, // k = 2
	{0x0000000000000000, 0x6693556faacb5bd6, 0x7b25c9734cdad509, 0x0803d4907c311575}, // k = 3
}

// lgamma128Ln1p5 is log(3/2) in fixed point with 192 fractional bits.
var lgamma128Ln1p5 = [4]uint64{0x0000000000000000, 0x67cc8fb2fe612fca, 0xda35d9bd01488606, 0x7d20ffb34547d7c3}

// lgamma128HalfLn2Pi256 is log(2 pi)/2 in Float256.
var lgamma128HalfLn2Pi256 = Float256{0x3fffed67f1c864be, 0xb4a6929792002883, 0x240479f611f1a268, 0xb169bbd8d46267b5}

// lgamma128LnPi256 is log(pi) in Float256.
var lgamma128LnPi256 = Float256{0x3ffff250d048e7a1, 0xbd0bd5f956c6a843, 0xf49985e6ddbf3b3f, 0x2606e33802ecaefb}

// lgamma128Pi256 is pi in Float256.
var lgamma128Pi256 = Float256{0x40000921fb54442d, 0x18469898cc51701b, 0x839a252049c1114c, 0xf98e804177d4c762}

// lgamma128Stirling256[k-1] is |B(2k)| / (2k (2k-1)) in Float256, the coefficient of the Stirling series.
var lgamma128Stirling256 = [...]Float256{
	{0x3fffb55555555555, 0x5555555555555555, 0x5555555555555555, 0x5555555555555555}, // k = 1
	{0x3fff66c16c16c16c, 0x16c16c16c16c16c1, 0x6c16c16c16c16c16, 0xc16c16c16c16c16c}, // k = 2
	{0x3fff4a01a01a01a0, 0x1a01a01a01a01a01, 0xa01a01a01a01a01a, 0x01a01a01a01a01a0}, // k = 3
	{0x3fff438138138138, 0x1381381381381381, 0x3813813813813813, 0x8138138138138138}, // k = 4
}
