// Code generated by scripts/gen_lgamma32_table.py; DO NOT EDIT.

package floats

// lgamma32SincCoeffs are the coefficients of the polynomial of u = r**2, which approximates sin(pi r)/(pi r) for |r| <= 1/2.
// The relative error is less than 2**-44.
var lgamma32SincCoeffs = [...]float64{
	0x1.ffffffffffeffp-1, -0x1.a51a66252878bp+0, 0x1.9f9cb4001a6a7p-1, -0x1.86a8e3c965f32p-3, 0x1.ac67dc51f9580p-6, -0x1.337bde0c5aff9p-9, 0x1.3674156ce5451p-13, -0x1.b34f18876b5ddp-18,
}
