package floats

import (
	"bufio"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestFloat128_Log(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0.25), "-1.3862943611198906188344642429163531361510002687205"},
		{exact128(0.5), "-0.69314718055994530941723212145817656807550013436026"},
		{exact128(1), "0"},
		{exact128(2), "0.69314718055994530941723212145817656807550013436026"},
		{exact128(3), "1.0986122886681096913952452369225257046474905578228"},
		{exact128(4), "1.3862943611198906188344642429163531361510002687205"},
		{exact128(100), "4.6051701859880913680359829093687284152022029772575"},
	}

	for _, tt := range tests {
		got := tt.x.Log()
		if !close128(got, tt.want) {
			t.Errorf("Log(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(0), exact128(math.Inf(-1))},
		{exact128(math.Copysign(0, -1)), exact128(math.Inf(-1))},
		{exact128(-1), exact128(math.NaN())},
		{exact128(math.NaN()), exact128(math.NaN())},

		// subnormals, mpmath-verified: the table-driven reduction reads the
		// exponent field directly, so a subnormal (with no implicit leading
		// bit) must be normalized first or it decodes to the wrong exponent.
		{Float128{0x0000000000000000, 0x0000000000000001}, Float128{0xc00c654628220780, 0x2c89d24d65e96274}}, // smallest subnormal
		{Float128{0x0000ffffffffffff, 0xffffffffffffffff}, Float128{0xc00c62d918ce2421, 0xd65ff90ac8f4ce66}}, // largest subnormal
		{Float128{0x0001000000000000, 0x0000000000000000}, Float128{0xc00c62d918ce2421, 0xd65ff90ac8f4ce66}}, // smallest normal

		// close to 1 from both sides, mpmath-verified: buckets 0 and 255 (which
		// border a = 1 and a = 2) must not round log(c), or that rounding error
		// would dominate log(a) for a this close to a power of two.
		{Float128{0x3fff000000000000, 0x0000000000000001}, Float128{0x3f8effffffffffff, 0xffffffffffffffff}}, // 1+1ulp
		{Float128{0x3ffeffffffffffff, 0xffffffffffffffff}, Float128{0xbf8e000000000000, 0x0000000000000000}}, // 1-1ulp
		{Float128{0x3fffffffffffffff, 0xffffffffffffffff}, Float128{0x3ffe62e42fefa39e, 0xf35793c7673007e5}}, // 2-1ulp
	}

	for _, tt := range strictTests {
		got := tt.x.Log()
		if !eq128(got, tt.want) {
			t.Errorf("Log(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat128_LogAccuracy checks that the error of Log is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat128_LogAccuracy(t *testing.T) {
	t.Parallel()
	testFloat128LogAccuracy(t, "testdata/log128.txt", "Log", Float128.Log)
}

// TestFloat128_Log2Accuracy checks that the error of Log2 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat128_Log2Accuracy(t *testing.T) {
	t.Parallel()
	testFloat128LogAccuracy(t, "testdata/log2_128.txt", "Log2", Float128.Log2)
}

// TestFloat128_Log10Accuracy checks that the error of Log10 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat128_Log10Accuracy(t *testing.T) {
	t.Parallel()
	testFloat128LogAccuracy(t, "testdata/log10_128.txt", "Log10", Float128.Log10)
}

func testFloat128LogAccuracy(t *testing.T, name, fname string, fn func(Float128) Float128) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	parse := func(s string) Float128 {
		var x Float128
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float128) bool {
		inf := NewFloat128Inf(1)
		return eq128(got, want) || eq128(got, want.Nextafter(inf)) || eq128(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := fn(x)
		total++
		if !eq128(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("%s(%v) = %v; want %v", fname, x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	if total == 0 {
		t.Fatalf("%s has no test cases", name)
	}
	if misrounded*100 > total {
		t.Errorf("%s: %d of %d results are not correctly rounded; want at most 1%%", fname, misrounded, total)
	}
}

func BenchmarkFloat128_Log(b *testing.B) {
	benchFloat128(b, Float128.Log, []struct {
		name string
		x    Float128
	}{
		{"subnormal", Float128{0, 1}},
		{"near_one", Float128{0x3fff000000000000, 0x0000000000000001}},
		{"small", exact128(0.001)},
		{"medium", exact128(1.5)},
		{"large", exact128(1e300)},
	})
}

func TestFloat128_Log10(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0.25), "-0.602059991327962390427477789448986053536379762924217082620854922254216378548849019"},
		{exact128(0.5), "-0.3010299956639811952137388947244930267681898814621085413104274611271081892744245095"},
		{exact128(1), "0"},
		{exact128(2), "0.3010299956639811952137388947244930267681898814621085413104274611271081892744245095"},
		{exact128(3), "0.477121254719662437295027903255115309200128864190695864829865640305229152783661123"},
		{exact128(4), "0.602059991327962390427477789448986053536379762924217082620854922254216378548849019"},
		{exact128(100), "2"},
	}

	for _, tt := range tests {
		got := tt.x.Log10()
		if !close128(got, tt.want) {
			t.Errorf("Log10(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(0), exact128(math.Inf(-1))},
		{exact128(math.Copysign(0, -1)), exact128(math.Inf(-1))},
		{exact128(-1), exact128(math.NaN())},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Log10()
		if !eq128(got, tt.want) {
			t.Errorf("Log10(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat128_Log10(b *testing.B) {
	benchFloat128(b, Float128.Log10, []struct {
		name string
		x    Float128
	}{
		{"subnormal", Float128{0, 1}},
		{"near_one", Float128{0x3fff000000000000, 0x0000000000000001}},
		{"small", exact128(0.001)},
		{"medium", exact128(1.5)},
		{"large", exact128(1e300)},
	})
}

func TestFloat128_Log2(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0.25), "-2"},
		{exact128(0.5), "-1"},
		{exact128(1), "0"},
		{exact128(2), "1"},
		{exact128(3), "1.584962500721156181453738943947816508759814407692481060455752654541098227794358563"},
		{exact128(4), "2"},
		{exact128(100), "6.643856189774724695740638858978780351729662786049161224109512791631869553217250432"},
	}

	for _, tt := range tests {
		got := tt.x.Log2()
		if !close128(got, tt.want) {
			t.Errorf("Log2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(0), exact128(math.Inf(-1))},
		{exact128(math.Copysign(0, -1)), exact128(math.Inf(-1))},
		{exact128(-1), exact128(math.NaN())},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Log2()
		if !eq128(got, tt.want) {
			t.Errorf("Log2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat128_Log2(b *testing.B) {
	benchFloat128(b, Float128.Log2, []struct {
		name string
		x    Float128
	}{
		{"subnormal", Float128{0, 1}},
		{"near_one", Float128{0x3fff000000000000, 0x0000000000000001}},
		{"small", exact128(0.001)},
		{"medium", exact128(1.5)},
		{"large", exact128(1e300)},
	})
}
