package floats

import (
	"bufio"
	"math"
	"math/rand/v2"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/shogo82148/ints"
)

func TestFloat256_Log(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.25), "-1.386294361119890618834464242916353136151000268720510508241360018986787243939389431211726653992837375084002962041141371467371040472"},
		{exact256(0.5), "-0.6931471805599453094172321214581765680755001343602552541206800094933936219696947156058633269964186875420014810205706857336855202358"},
		{exact256(1), "0"},
		{exact256(2), "0.6931471805599453094172321214581765680755001343602552541206800094933936219696947156058633269964186875420014810205706857336855202358"},
		{exact256(3), "1.098612288668109691395245236922525704647490557822749451734694333637494293218608966873615754813732088787970029065957865742368004226"},
		{exact256(4), "1.386294361119890618834464242916353136151000268720510508241360018986787243939389431211726653992837375084002962041141371467371040472"},
		{exact256(100), "4.60517018598809136803598290936872841520220297725754595206665580193514521935470496047199441017919659668393556808457249726681905093"},
	}

	for _, tt := range tests {
		got := tt.x.Log()
		if !close256(got, tt.want) {
			t.Errorf("Log(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(0), exact256(math.Inf(-1))},
		{exact256(math.Copysign(0, -1)), exact256(math.Inf(-1))},
		{exact256(-1), exact256(math.NaN())},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Log()
		if !eq256(got, tt.want) {
			t.Errorf("Log(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_LogAccuracy checks that the error of Log is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat256_LogAccuracy(t *testing.T) {
	t.Parallel()
	testFloat256LogAccuracy(t, "testdata/log256.txt", "Log", Float256.Log)
}

// TestFloat256_Log2Accuracy checks that the error of Log2 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat256_Log2Accuracy(t *testing.T) {
	t.Parallel()
	testFloat256LogAccuracy(t, "testdata/log2_256.txt", "Log2", Float256.Log2)
}

// TestFloat256_Log10Accuracy checks that the error of Log10 is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_log_testdata.py.
func TestFloat256_Log10Accuracy(t *testing.T) {
	t.Parallel()
	testFloat256LogAccuracy(t, "testdata/log10_256.txt", "Log10", Float256.Log10)
}

func testFloat256LogAccuracy(t *testing.T, name, fname string, fn func(Float256) Float256) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}
	within1ulp := func(got, want Float256) bool {
		inf := NewFloat256Inf(1)
		return eq256(got, want) || eq256(got, want.Nextafter(inf)) || eq256(got, want.Nextafter(inf.Neg()))
	}

	var total, misrounded int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		got := fn(x)
		total++
		if !eq256(got, want) {
			misrounded++
		}
		if !within1ulp(got, want) {
			t.Errorf("%s(%v) = %v; want %v", fname, x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	if total == 0 {
		t.Fatalf("%s has no test cases", name)
	}
	if misrounded*100 > total {
		t.Errorf("%s: %d of %d results are not correctly rounded; want at most 1%%", fname, misrounded, total)
	}
}

func BenchmarkFloat256_Log(b *testing.B) {
	benchFloat256Exp(b, Float256.Log, []struct {
		name string
		x    Float256
	}{
		{"subnormal", Float256{0, 0, 0, 1}},
		{"near_one", Float256{0x3fffe00000000000, 0, 0, 1}},
		{"small", exact256(0.001)},
		{"medium", exact256(1.5)},
		{"large", exact256(1e300)},
	})
}

func TestFloat256_Log10(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.25), "-0.602059991327962390427477789448986053536379762924217082620854922254216378548849019"},
		{exact256(0.5), "-0.3010299956639811952137388947244930267681898814621085413104274611271081892744245095"},
		{exact256(1), "0"},
		{exact256(2), "0.3010299956639811952137388947244930267681898814621085413104274611271081892744245095"},
		{exact256(3), "0.477121254719662437295027903255115309200128864190695864829865640305229152783661123"},
		{exact256(4), "0.602059991327962390427477789448986053536379762924217082620854922254216378548849019"},
		{exact256(100), "2"},
	}

	for _, tt := range tests {
		got := tt.x.Log10()
		if !close256(got, tt.want) {
			t.Errorf("Log10(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(0), exact256(math.Inf(-1))},
		{exact256(math.Copysign(0, -1)), exact256(math.Inf(-1))},
		{exact256(-1), exact256(math.NaN())},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Log10()
		if !eq256(got, tt.want) {
			t.Errorf("Log10(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat256_Log10(b *testing.B) {
	benchFloat256Exp(b, Float256.Log10, []struct {
		name string
		x    Float256
	}{
		{"subnormal", Float256{0, 0, 0, 1}},
		{"near_one", Float256{0x3fffe00000000000, 0, 0, 1}},
		{"small", exact256(0.001)},
		{"medium", exact256(1.5)},
		{"large", exact256(1e300)},
	})
}

func TestFloat256_Log2(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.25), "-2"},
		{exact256(0.5), "-1"},
		{exact256(1), "0"},
		{exact256(2), "1"},
		{exact256(3), "1.584962500721156181453738943947816508759814407692481060455752654541098227794358563"},
		{exact256(4), "2"},
		{exact256(100), "6.643856189774724695740638858978780351729662786049161224109512791631869553217250432"},
	}

	for _, tt := range tests {
		got := tt.x.Log2()
		if !close256(got, tt.want) {
			t.Errorf("Log2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(0), exact256(math.Inf(-1))},
		{exact256(math.Copysign(0, -1)), exact256(math.Inf(-1))},
		{exact256(-1), exact256(math.NaN())},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Log2()
		if !eq256(got, tt.want) {
			t.Errorf("Log2(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat256_Log2(b *testing.B) {
	benchFloat256Exp(b, Float256.Log2, []struct {
		name string
		x    Float256
	}{
		{"subnormal", Float256{0, 0, 0, 1}},
		{"near_one", Float256{0x3fffe00000000000, 0, 0, 1}},
		{"small", exact256(0.001)},
		{"medium", exact256(1.5)},
		{"large", exact256(1e300)},
	})
}

// TestLog256G compares log256G, which evaluates the polynomial with the mixed precision,
// with the plain evaluation with 256 bits. Their results may differ by one unit in the last place.
func TestLog256G(t *testing.T) {
	t.Parallel()
	rnd := rand.New(rand.NewPCG(5, 6))
	var differ int
	for i := range 200000 {
		var w ints.Uint256
		for j := range w {
			w[j] = rnd.Uint64()
		}
		switch i % 3 {
		case 0:
			w = w.Rsh(uint(rnd.IntN(250))) // |w| from 2**-8 to tiny
		case 1:
			w = w.Rsh(uint(rnd.IntN(3))) // |w| close to 2**-8
		}
		wneg := rnd.IntN(2) == 0

		want := log256G256(w, wneg)
		got := log256G(w, wneg)
		var diff ints.Uint256
		if got.Cmp(want) >= 0 {
			diff = got.Sub(want)
		} else {
			diff = want.Sub(got)
		}
		if diff.BitLen() > 1 {
			t.Fatalf("log256G(%v, %v) = %v; want %v", w, wneg, got, want)
		}
		if !diff.IsZero() {
			differ++
		}
	}
	if differ > 2000 {
		t.Errorf("%d of 200000 results differ from the plain evaluation", differ)
	}
}

// log256G256 is the plain evaluation of log256G with 256 bits.
func log256G256(w ints.Uint256, wneg bool) ints.Uint256 {
	g := ints.Uint256(log256Coeffs[0])
	for _, c := range log256Coeffs[1:] {
		t := shr512to256(g.Mul512(w), 264)
		if wneg {
			g = ints.Uint256(c).Sub(t)
		} else {
			g = ints.Uint256(c).Add(t)
		}
	}
	return g
}
