package floats

import (
	"bufio"
	"math"
	"math/rand/v2"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat16_Pow(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float16
		y    Float16
		want float64
	}{
		{exact16(2), exact16(3), math.Pow(2, 3)},
		{exact16(5), exact16(0.5), math.Pow(5, 0.5)},
		{exact16(5), exact16(1.5), math.Pow(5, 1.5)},
		{exact16(5), exact16(-1.5), math.Pow(5, -1.5)},
	}

	for _, tt := range tests {
		got := tt.x.Pow(tt.y)
		if !close16(got, tt.want) {
			t.Errorf("Pow(%v, %v) = %v; want %v", tt.x, tt.y, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float16
		y    Float16
		want Float16
	}{
		// special cases
		// a.Pow(±0) = 1 for any a
		{exact16(2), exact16(0), exact16(1)},
		{exact16(2), exact16(math.Copysign(0, -1)), exact16(1)},
		{exact16(-2), exact16(0), exact16(1)},
		{exact16(-2), exact16(math.Copysign(0, -1)), exact16(1)},
		{exact16(math.Inf(1)), exact16(0), exact16(1)},
		{exact16(math.Inf(1)), exact16(math.Copysign(0, -1)), exact16(1)},
		{exact16(math.NaN()), exact16(0), exact16(1)},
		{exact16(math.NaN()), exact16(math.Copysign(0, -1)), exact16(1)},

		// 1.Pow(b) = 1 for any b
		{exact16(1), exact16(3), exact16(1)},
		{exact16(1), exact16(-3), exact16(1)},
		{exact16(1), exact16(math.Inf(1)), exact16(1)},
		{exact16(1), exact16(math.Inf(-1)), exact16(1)},
		{exact16(1), exact16(math.NaN()), exact16(1)},

		// a.Pow(1) = a for any a
		{exact16(2), exact16(1), exact16(2)},
		{exact16(-2), exact16(1), exact16(-2)},
		{exact16(math.Inf(1)), exact16(1), exact16(math.Inf(1))},
		{exact16(math.NaN()), exact16(1), exact16(math.NaN())},

		// NaN.Pow(b) = NaN
		{exact16(math.NaN()), exact16(3), exact16(math.NaN())},
		{exact16(math.NaN()), exact16(-3), exact16(math.NaN())},
		{exact16(math.NaN()), exact16(math.Inf(1)), exact16(math.NaN())},
		{exact16(math.NaN()), exact16(math.Inf(-1)), exact16(math.NaN())},

		// a.Pow(NaN) = NaN
		{exact16(2), exact16(math.NaN()), exact16(math.NaN())},
		{exact16(-2), exact16(math.NaN()), exact16(math.NaN())},
		{exact16(math.Inf(1)), exact16(math.NaN()), exact16(math.NaN())},
		{exact16(math.Inf(-1)), exact16(math.NaN()), exact16(math.NaN())},

		// ±0.Pow(b) = ±Inf for b an odd integer < 0
		{exact16(0), exact16(-3), exact16(math.Inf(1))},
		{exact16(math.Copysign(0, -1)), exact16(-3), exact16(math.Inf(-1))},

		// ±0.Pow(-Inf) = +Inf
		{exact16(0), exact16(math.Inf(-1)), exact16(math.Inf(1))},
		{exact16(math.Copysign(0, -1)), exact16(math.Inf(-1)), exact16(math.Inf(1))},

		// ±0.Pow(+Inf) = +0
		{exact16(0), exact16(math.Inf(1)), exact16(0)},
		{exact16(math.Copysign(0, -1)), exact16(math.Inf(1)), exact16(0)},

		// ±0.Pow(b) = +Inf for finite b < 0 and not an odd integer
		{exact16(0), exact16(-2), exact16(math.Inf(1))},
		{exact16(math.Copysign(0, -1)), exact16(-2), exact16(math.Inf(1))},
		{exact16(math.Copysign(0, -1)), exact16(-0.5), exact16(math.Inf(1))},

		// ±0.Pow(b) = ±0 for b an odd integer > 0
		{exact16(0), exact16(3), exact16(0)},
		{exact16(math.Copysign(0, -1)), exact16(3), exact16(math.Copysign(0, -1))},

		// ±0.Pow(b) = +0 for finite b > 0 and not an odd integer
		{exact16(0), exact16(2), exact16(0)},
		{exact16(math.Copysign(0, -1)), exact16(2), exact16(0)},

		// -1.Pow(±Inf) = 1
		{exact16(-1), exact16(math.Inf(1)), exact16(1)},
		{exact16(-1), exact16(math.Inf(-1)), exact16(1)},

		// a.Pow(+Inf) = +Inf for |a| > 1
		{exact16(2), exact16(math.Inf(1)), exact16(math.Inf(1))},
		{exact16(-2), exact16(math.Inf(1)), exact16(math.Inf(1))},

		// a.Pow(-Inf) = +0 for |a| > 1
		{exact16(2), exact16(math.Inf(-1)), exact16(0)},
		{exact16(-2), exact16(math.Inf(-1)), exact16(0)},

		// a.Pow(+Inf) = +0 for |a| < 1
		{exact16(0.5), exact16(math.Inf(1)), exact16(0)},
		{exact16(-0.5), exact16(math.Inf(1)), exact16(0)},

		// a.Pow(-Inf) = +Inf for |a| < 1
		{exact16(0.5), exact16(math.Inf(-1)), exact16(math.Inf(1))},
		{exact16(-0.5), exact16(math.Inf(-1)), exact16(math.Inf(1))},

		// +Inf.Pow(b) = +Inf for b > 0
		{exact16(math.Inf(1)), exact16(2), exact16(math.Inf(1))},

		// +Inf.Pow(b) = +0 for b < 0
		{exact16(math.Inf(1)), exact16(-2), exact16(0)},

		// -Inf.Pow(b) = (-0).Pow(-b)
		{exact16(math.Inf(-1)), exact16(3), exact16(math.Inf(-1))},
		{exact16(math.Inf(-1)), exact16(2), exact16(math.Inf(1))},

		// a.Pow(b) = NaN for finite a < 0 and finite non-integer b
		{exact16(-2), exact16(0.5), exact16(math.NaN())},
		{exact16(-2), exact16(-0.5), exact16(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Pow(tt.y)
		if !eq16(got, tt.want) {
			t.Errorf("Pow(%v, %v) = %v; want %v", tt.x, tt.y, got, tt.want)
		}
	}
}

// TestFloat16_PowAccuracy checks that Pow is correctly rounded.
// The test data is generated by scripts/gen_pow16_testdata.py,
// and contains all exact results on the midpoint of two adjacent Float16 values.
// Checking all pairs of Float16 values, Pow is correctly rounded.
func TestFloat16_PowAccuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/pow16.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float16 {
		v, err := strconv.ParseUint(s, 16, 16)
		if err != nil {
			t.Fatal(err)
		}
		return NewFloat16FromBits(uint16(v))
	}

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, y, want := parse(fields[0]), parse(fields[1]), parse(fields[2])
		if got := x.Pow(y); !eq16(got, want) {
			t.Errorf("Pow(%v, %v) = %v; want %v", x, y, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
}

// TestFloat16_PowRandom compares Pow with math.Pow on random inputs.
// math.Pow rounded to Float16 is correctly rounded except for 7 pairs of Float16 values,
// so the results should almost always match.
func TestFloat16_PowRandom(t *testing.T) {
	t.Parallel()
	r := rand.New(rand.NewPCG(1, 2))
	var mismatch int
	for range 1000000 {
		x := NewFloat16FromBits(uint16(r.Uint32()))
		y := NewFloat16FromBits(uint16(r.Uint32()))
		got := x.Pow(y)
		want := NewFloat16(math.Pow(x.Float64().BuiltIn(), y.Float64().BuiltIn()))
		if !eq16(got, want) {
			mismatch++
			t.Logf("Pow(%v, %v) = %v; math.Pow gives %v", x, y, got, want)
		}
	}
	if mismatch > 3 {
		t.Errorf("%d results are different from math.Pow", mismatch)
	}
}

func BenchmarkFloat16_Pow(b *testing.B) {
	x := exact16(1.5)
	for b.Loop() {
		runtime.KeepAlive(x.Pow(x))
	}
}
