package floats

import (
	"bufio"
	"math"
	"math/rand/v2"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat32_Sin(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float32
		want float64
	}{
		{exact32(-3), math.Sin(-3)},
		{exact32(-2), math.Sin(-2)},
		{exact32(-1), math.Sin(-1)},
		{exact32(1), math.Sin(1)},
		{exact32(2), math.Sin(2)},
		{exact32(3), math.Sin(3)},
		{exact32(0x1p28), math.Sin(0x1p28)},
	}

	for _, tt := range tests {
		got := tt.x.Sin()
		if !close32(got, tt.want) {
			t.Errorf("Sin(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float32
		want Float32
	}{
		// special cases
		{exact32(0), exact32(0)},
		{exact32(math.Copysign(0, -1)), exact32(math.Copysign(0, -1))},
		{exact32(math.Inf(1)), exact32(math.NaN())},
		{exact32(math.Inf(-1)), exact32(math.NaN())},
		{exact32(math.NaN()), exact32(math.NaN())},

		// tiny arguments
		{NewFloat32FromBits(0x00000001), NewFloat32FromBits(0x00000001)},
		{NewFloat32FromBits(0x80000001), NewFloat32FromBits(0x80000001)},
		{NewFloat32FromBits(0x397fffff), NewFloat32FromBits(0x397fffff)},
	}
	for _, tt := range strictTests {
		got := tt.x.Sin()
		if !eq32(got, tt.want) {
			t.Errorf("Sin(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func TestFloat32_Cos(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float32
		want float64
	}{
		{exact32(1), math.Cos(1)},
		{exact32(2), math.Cos(2)},
		{exact32(3), math.Cos(3)},
	}

	for _, tt := range tests {
		got := tt.x.Cos()
		if !close32(got, tt.want) {
			t.Errorf("Cos(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float32
		want Float32
	}{
		// special cases
		{exact32(math.Inf(1)), exact32(math.NaN())},
		{exact32(math.Inf(-1)), exact32(math.NaN())},
		{exact32(math.NaN()), exact32(math.NaN())},
	}
	for _, tt := range strictTests {
		got := tt.x.Cos()
		if !eq32(got, tt.want) {
			t.Errorf("Cos(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func TestFloat32_Sincos(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x   Float32
		sin float64
		cos float64
	}{
		{exact32(1), math.Sin(1), math.Cos(1)},
		{exact32(2), math.Sin(2), math.Cos(2)},
		{exact32(3), math.Sin(3), math.Cos(3)},
	}

	for _, tt := range tests {
		sin, cos := tt.x.Sincos()
		if !close32(sin, tt.sin) {
			t.Errorf("Sincos(%v) sin = %v; want %v", tt.x, sin, tt.sin)
		}
		if !close32(cos, tt.cos) {
			t.Errorf("Sincos(%v) cos = %v; want %v", tt.x, cos, tt.cos)
		}
	}

	strictTests := []struct {
		x   Float32
		sin Float32
		cos Float32
	}{
		// special cases
		{exact32(0), exact32(0), exact32(1)},
		{exact32(math.Copysign(0, -1)), exact32(math.Copysign(0, -1)), exact32(1)},
		{exact32(math.Inf(1)), exact32(math.NaN()), exact32(math.NaN())},
		{exact32(math.Inf(-1)), exact32(math.NaN()), exact32(math.NaN())},
		{exact32(math.NaN()), exact32(math.NaN()), exact32(math.NaN())},
	}

	for _, tt := range strictTests {
		sin, cos := tt.x.Sincos()
		if !eq32(sin, tt.sin) {
			t.Errorf("Sincos(%v) sin = %v; want %v", tt.x, sin, tt.sin)
		}
		if !eq32(cos, tt.cos) {
			t.Errorf("Sincos(%v) cos = %v; want %v", tt.x, cos, tt.cos)
		}
	}
}

func TestFloat32_Tan(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float32
		want float64
	}{
		{exact32(1), math.Tan(1)},
		{exact32(2), math.Tan(2)},
		{exact32(3), math.Tan(3)},
	}

	for _, tt := range tests {
		got := tt.x.Tan()
		if !close32(got, tt.want) {
			t.Errorf("Tan(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float32
		want Float32
	}{
		// special cases
		{exact32(0), exact32(0)},
		{exact32(math.Copysign(0, -1)), exact32(math.Copysign(0, -1))},
		{exact32(math.Inf(1)), exact32(math.NaN())},
		{exact32(math.Inf(-1)), exact32(math.NaN())},
		{exact32(math.NaN()), exact32(math.NaN())},
	}
	for _, tt := range strictTests {
		got := tt.x.Tan()
		if !eq32(got, tt.want) {
			t.Errorf("Tan(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat32_SinCosTanAccuracy checks that the error of Sin, Cos, Sincos, and Tan is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_sin_testdata.py.
func TestFloat32_SinCosTanAccuracy(t *testing.T) {
	t.Parallel()
	total, misrounded := testFloat32SinCosTan(t, "testdata/sin32.txt")
	if misrounded*100 > total {
		t.Errorf("%d of %d results are not correctly rounded; want at most 1%%", misrounded, total)
	}
}

// TestFloat32_SinCosTanHardCases checks that the error of Sin, Cos, Sincos, and Tan is less than 1 ulp
// on the inputs whose results are very close to the midpoint of two adjacent Float32 values.
// They may not be correctly rounded.
// The test data is generated by scripts/gen_sin_testdata.py.
func TestFloat32_SinCosTanHardCases(t *testing.T) {
	t.Parallel()
	testFloat32SinCosTan(t, "testdata/sin32_hard.txt")
}

func testFloat32SinCosTan(t *testing.T, name string) (total, misrounded int) {
	t.Helper()
	f, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	parse := func(s string) Float32 {
		v, err := strconv.ParseUint(s, 16, 32)
		if err != nil {
			t.Fatal(err)
		}
		return NewFloat32FromBits(uint32(v))
	}

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, wantSin, wantCos, wantTan := parse(fields[0]), parse(fields[1]), parse(fields[2]), parse(fields[3])

		sin, cos := x.Sincos()
		tan := x.Tan()
		total += 3
		if !eq32(sin, wantSin) {
			misrounded++
		}
		if !eq32(cos, wantCos) {
			misrounded++
		}
		if !eq32(tan, wantTan) {
			misrounded++
		}
		if !within1ulp32(sin, wantSin) {
			t.Errorf("Sincos(%v) sin = %v; want %v", x, sin, wantSin)
		}
		if !within1ulp32(cos, wantCos) {
			t.Errorf("Sincos(%v) cos = %v; want %v", x, cos, wantCos)
		}
		if !within1ulp32(tan, wantTan) {
			t.Errorf("Tan(%v) = %v; want %v", x, tan, wantTan)
		}
		if got := x.Sin(); !eq32(got, sin) {
			t.Errorf("Sin(%v) = %v; want %v", x, got, sin)
		}
		if got := x.Cos(); !eq32(got, cos) {
			t.Errorf("Cos(%v) = %v; want %v", x, got, cos)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("%d of %d results are not correctly rounded", misrounded, total)
	return
}

// TestFloat32_SinCosTanRandom compares Sin, Cos, Sincos, and Tan with math.Sin, math.Cos, and math.Tan on random inputs.
// math.Sin, math.Cos, and math.Tan rounded to float32 are correctly rounded except for rare cases,
// so the results should almost always match.
func TestFloat32_SinCosTanRandom(t *testing.T) {
	t.Parallel()
	r := rand.New(rand.NewPCG(1, 2))
	gens := []struct {
		name string
		gen  func() Float32
	}{
		{"bits", func() Float32 { return NewFloat32FromBits(r.Uint32()) }},
		{"uniform", func() Float32 { return NewFloat32(r.Float64()*16 - 8) }},
		{"exponent", func() Float32 {
			// uniformly distributed exponent in [-20, 127]
			return NewFloat32FromBits(r.Uint32()&(signMask32|fracMask32) | uint32(r.IntN(148)+bias32-20)<<shift32)
		}},
	}
	for _, g := range gens {
		var mismatch int
		for range 300000 {
			x := g.gen()
			if x.IsNaN() || x.IsInf(0) {
				continue
			}
			wantSin := NewFloat32(math.Sin(float64(x)))
			wantCos := NewFloat32(math.Cos(float64(x)))
			sin, cos := x.Sincos()
			if !within1ulp32(sin, wantSin) {
				t.Fatalf("Sincos(%v) sin = %v; want %v", x, sin, wantSin)
			}
			if !within1ulp32(cos, wantCos) {
				t.Fatalf("Sincos(%v) cos = %v; want %v", x, cos, wantCos)
			}
			if !eq32(sin, wantSin) {
				mismatch++
			}
			if !eq32(cos, wantCos) {
				mismatch++
			}
			if got := x.Sin(); !eq32(got, sin) {
				t.Fatalf("Sin(%v) = %v; want %v", x, got, sin)
			}
			if got := x.Cos(); !eq32(got, cos) {
				t.Fatalf("Cos(%v) = %v; want %v", x, got, cos)
			}

			wantTan := NewFloat32(math.Tan(float64(x)))
			tan := x.Tan()
			if !within1ulp32(tan, wantTan) {
				t.Fatalf("Tan(%v) = %v; want %v", x, tan, wantTan)
			}
			if !eq32(tan, wantTan) {
				mismatch++
			}
		}
		// Checking all Float32 values, about 200 of 3*2**32 results are different.
		if mismatch > 3 {
			t.Errorf("%s: %d results are different from math.Sin, math.Cos, and math.Tan", g.name, mismatch)
		}
	}
}

// within1ulp32 reports whether got is within 1 ulp of want.
func within1ulp32(got, want Float32) bool {
	inf := NewFloat32Inf(1)
	return eq32(got, want) || eq32(got, want.Nextafter(inf)) || eq32(got, want.Nextafter(inf.Neg()))
}

func BenchmarkFloat32_Sin(b *testing.B) {
	for _, x := range []Float32{0.5, 3, 1e6, 1e30} {
		b.Run(x.String(), func(b *testing.B) {
			for b.Loop() {
				runtime.KeepAlive(x.Sin())
			}
		})
	}
}

func BenchmarkFloat32_Cos(b *testing.B) {
	for _, x := range []Float32{0.5, 3, 1e6, 1e30} {
		b.Run(x.String(), func(b *testing.B) {
			for b.Loop() {
				runtime.KeepAlive(x.Cos())
			}
		})
	}
}

func BenchmarkFloat32_Sincos(b *testing.B) {
	for _, x := range []Float32{0.5, 3, 1e6, 1e30} {
		b.Run(x.String(), func(b *testing.B) {
			for b.Loop() {
				s, c := x.Sincos()
				runtime.KeepAlive(s)
				runtime.KeepAlive(c)
			}
		})
	}
}

func BenchmarkFloat32_Tan(b *testing.B) {
	for _, x := range []Float32{0.5, 3, 1e6, 1e30} {
		b.Run(x.String(), func(b *testing.B) {
			for b.Loop() {
				runtime.KeepAlive(x.Tan())
			}
		})
	}
}
