package floats

import (
	"math"
	"math/rand/v2"
	"testing"

	"github.com/shogo82148/ints"
)

func TestFloat256_Sinh(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.25), "0.2526123168081683079141251505420579055197542874276608074880949653019810769068593791"},
		{exact256(0.5), "0.5210953054937473616224256264114915591059289826114805279460935764528023"},
		{exact256(1), "1.175201193643801456882381850595600815155717981334095870229565413013308"},
		{exact256(2), "3.62686040784701876766821398280126170488634201232113572130948447493425"},
		{exact256(3), "10.01787492740990189897459361946582806017810412318286346440565325104639"},
		{exact256(4), "27.28991719712775244890827159079381858028941248553029656552849701555721"},
		{exact256(85), "4111506357311456755152164008203887347.743143094238137019761966924872080517377059248"},
	}

	for _, tt := range tests {
		got := tt.x.Sinh()
		if !close256(got, tt.want) {
			t.Errorf("Sinh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(0)},
		{exact256(math.Copysign(0, -1)), exact256(math.Copysign(0, -1))},

		// special cases
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(math.Inf(-1)), exact256(math.Inf(-1))},
		{exact256(math.NaN()), exact256(math.NaN())},

		// tiny values: sinh(x) = x + x**3/6 + ... rounds to x
		{Float256{0, 0, 0, 1}, Float256{0, 0, 0, 1}},
		{exact256(-0x1p-1000), exact256(-0x1p-1000)},
		{exact256(0x1p-119), exact256(0x1p-119)},
		{
			// 2**-118 - 2**-355: x**3/6 = 0.33 ulp
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
		},
		{exact256(-0x1p-118), exact256(-0x1p-118)}, // x**3/6 = 0.17 ulp
		{
			// 2**-117 - 2**-354: x**3/6 = 1.33 ulp
			Float256{
				0x3ff8_9fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			exact256(0x1p-117),
		},

		// overflow
		{
			exact256(181705),
			Float256{
				0x7fff_ede8_283b_8a01, 0xdd49_a891_879c_45b8,
				0xc0b4_b9d1_bea7_31fb, 0x70c9_b724_af21_95fa,
			},
		},
		{
			exact256(-181705),
			Float256{
				0xffff_ede8_283b_8a01, 0xdd49_a891_879c_45b8,
				0xc0b4_b9d1_bea7_31fb, 0x70c9_b724_af21_95fa,
			},
		},
		{exact256(181706), exact256(math.Inf(1))},
		{exact256(-181706), exact256(math.Inf(-1))},
		{exact256(0x1p30), exact256(math.Inf(1))},
		{exact256(-0x1p30), exact256(math.Inf(-1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Sinh()
		if !eq256(got, tt.want) {
			t.Errorf("Sinh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_SinhAccuracy checks that the error of Sinh is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_sinh_testdata.py.
func TestFloat256_SinhAccuracy(t *testing.T) {
	t.Parallel()
	testFloat256Accuracy(t, "testdata/sinh256.txt", "Sinh", Float256.Sinh)
}

func BenchmarkFloat256_Sinh(b *testing.B) {
	benchFloat256(b, Float256.Sinh, []struct {
		name string
		x    Float256
	}{
		{"tiny", exact256(0x1p-120)},  // returns x
		{"small", exact256(0x1p-10)},  // |x| < ln(2)/128
		{"medium", exact256(1.5)},     // e**-x is not negligible
		{"negative", exact256(-10.3)}, // sinh(-x) = -sinh(x)
		{"large", exact256(1000.7)},   // e**-x is negligible
	})
}

func TestFloat256_Cosh(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0), "1"},
		{exact256(1), "1.543080634815243778477905620757061682601529112365863704737402214710769"},
		{exact256(2), "3.762195691083631459562213477773746108293973558230711602777643347588324"},
		{exact256(3), "10.06766199577776584195393603511588983680980371537128667997328097865245"},
		{exact256(4), "27.30823283601648662920198961206705982250132455308377216029809694299646"},
		{exact256(43), "2363919734114673280.737228781372140185515632533070023109815169030476886"},
	}

	for _, tt := range tests {
		got := tt.x.Cosh()
		if !close256(got, tt.want) {
			t.Errorf("Cosh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		// special cases
		{exact256(0), exact256(1)},
		{exact256(math.Copysign(0, -1)), exact256(1)},
		{exact256(math.Inf(1)), exact256(math.Inf(1))},
		{exact256(math.Inf(-1)), exact256(math.Inf(1))},
		{exact256(math.NaN()), exact256(math.NaN())},

		// tiny values: cosh(x) = 1 + x**2/2 + ...
		{Float256{0, 0, 0, 1}, exact256(1)},
		{exact256(-0x1p-1000), exact256(1)},
		{exact256(0x1p-119), exact256(1)},
		{
			// 2**-118 - 2**-355: just below the midpoint 1 + 2**-237
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			exact256(1),
		},
		{
			// just above the midpoint 1 + 2**-237
			exact256(-0x1p-118),
			Float256{
				0x3fff_f000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0001,
			},
		},
		{
			// 2**-117 - 2**-354
			Float256{
				0x3ff8_9fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			Float256{
				0x3fff_f000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0002,
			},
		},
		{
			exact256(0x1p-117),
			Float256{
				0x3fff_f000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0002,
			},
		},

		// overflow
		{
			exact256(181705),
			Float256{
				0x7fff_ede8_283b_8a01, 0xdd49_a891_879c_45b8,
				0xc0b4_b9d1_bea7_31fb, 0x70c9_b724_af21_95fa,
			},
		},
		{
			exact256(-181705),
			Float256{
				0x7fff_ede8_283b_8a01, 0xdd49_a891_879c_45b8,
				0xc0b4_b9d1_bea7_31fb, 0x70c9_b724_af21_95fa,
			},
		},
		{exact256(181706), exact256(math.Inf(1))},
		{exact256(-181706), exact256(math.Inf(1))},
		{exact256(0x1p30), exact256(math.Inf(1))},
		{exact256(-0x1p30), exact256(math.Inf(1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Cosh()
		if !eq256(got, tt.want) {
			t.Errorf("Cosh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_CoshAccuracy checks that the error of Cosh is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_sinh_testdata.py.
func TestFloat256_CoshAccuracy(t *testing.T) {
	t.Parallel()
	testFloat256Accuracy(t, "testdata/cosh256.txt", "Cosh", Float256.Cosh)
}

func BenchmarkFloat256_Cosh(b *testing.B) {
	benchFloat256(b, Float256.Cosh, []struct {
		name string
		x    Float256
	}{
		{"tiny", exact256(0x1p-120)},  // returns 1
		{"small", exact256(0x1p-10)},  // |x| < ln(2)/128
		{"medium", exact256(1.5)},     // e**-x is not negligible
		{"negative", exact256(-10.3)}, // cosh(-x) = cosh(x)
		{"large", exact256(1000.7)},   // e**-x is negligible
	})
}

func TestFloat256_Tanh(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0), "0"},
		{exact256(0x1p-20), "9.536743164059608794206706373323853753492884138265436942109400747002263410862969192E-7"},
		{exact256(0.5), "0.4621171572600097585023184836436725487302892803301130385527318158380809061404092788"},
		{exact256(1), "0.7615941559557648881194582826047935904127685972579365515968105001219532445766384835"},
		{exact256(2), "0.9640275800758168839464137241009231502550299762409347760482632174131079463176102026"},
		{exact256(3), "0.9950547536867304513318801852554884750978138547002824918238788151306647027825591767"},
		{exact256(4), "0.9993292997390670437922433443417249620053398528944096480078068964566788861183201802"},
		{exact256(43), "0.9999999999999999999999999999999999999105244138763775853074468832166051200464931478"},
		{exact256(100000), "1"},

		{exact256(math.Copysign(0, -1)), "-0"},
		{exact256(-0x1p-20), "-9.536743164059608794206706373323853753492884138265436942109400747002263410862969192E-7"},
		{exact256(-0.5), "-0.4621171572600097585023184836436725487302892803301130385527318158380809061404092788"},
		{exact256(-1), "-0.7615941559557648881194582826047935904127685972579365515968105001219532445766384835"},
		{exact256(-2), "-0.9640275800758168839464137241009231502550299762409347760482632174131079463176102026"},
		{exact256(-3), "-0.9950547536867304513318801852554884750978138547002824918238788151306647027825591767"},
		{exact256(-4), "-0.9993292997390670437922433443417249620053398528944096480078068964566788861183201802"},
		{exact256(-43), "-0.9999999999999999999999999999999999999105244138763775853074468832166051200464931478"},
		{exact256(-100000), "-1"},
	}

	for _, tt := range tests {
		got := tt.x.Tanh()
		if !close256(got, tt.want) {
			t.Errorf("Tanh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		// special cases
		{exact256(0), exact256(0)},
		{exact256(math.Copysign(0, -1)), exact256(math.Copysign(0, -1))},
		{exact256(math.Inf(1)), exact256(1)},
		{exact256(math.Inf(-1)), exact256(-1)},
		{exact256(math.NaN()), exact256(math.NaN())},

		// tiny values: tanh(x) = x - x**3/3 + ...
		{Float256{0, 0, 0, 1}, Float256{0, 0, 0, 1}},
		{exact256(-0x1p-1000), exact256(-0x1p-1000)},
		{
			// 2**-119 - 2**-356
			Float256{
				0x3ff8_7fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			Float256{
				0x3ff8_7fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
		},
		{
			// 2**-118 - 2**-355
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_fffe,
			},
		},
		{
			// 2**-118
			Float256{
				0x3ff8_9000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0000,
			},
			Float256{
				0x3ff8_8fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
		},
		{
			// 2**-117
			Float256{
				0x3ff8_a000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0000,
			},
			Float256{
				0x3ff8_9fff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_fffd,
			},
		},

		// around the threshold where tanh(x) rounds to ±1
		{
			// 82
			Float256{
				0x4000_5480_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0000,
			},
			Float256{
				0x3fff_efff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_fffd,
			},
		},
		{
			// just below 239×ln(2)/2: rounds down below 1
			Float256{
				0x4000_54b5_308c_0b9c, 0x1652_ec2f_7295_5d75,
				0xfa89_b3b4_6376_1c9f, 0x9242_907c_4719_ceec,
			},
			Float256{
				0x3fff_efff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
		},
		{
			// -(just below 239×ln(2)/2)
			Float256{
				0xc000_54b5_308c_0b9c, 0x1652_ec2f_7295_5d75,
				0xfa89_b3b4_6376_1c9f, 0x9242_907c_4719_ceec,
			},
			Float256{
				0xbfff_efff_ffff_ffff, 0xffff_ffff_ffff_ffff,
				0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff,
			},
		},
		{
			// just above 239×ln(2)/2: rounds to 1
			Float256{
				0x4000_54b5_308c_0b9c, 0x1652_ec2f_7295_5d75,
				0xfa89_b3b4_6376_1c9f, 0x9242_907c_4719_ceed,
			},
			Float256{
				0x3fff_f000_0000_0000, 0x0000_0000_0000_0000,
				0x0000_0000_0000_0000, 0x0000_0000_0000_0000,
			},
		},
		{exact256(83), exact256(1)},
		{exact256(-128), exact256(-1)},
		{exact256(0x1p30), exact256(1)},
	}

	for _, tt := range strictTests {
		got := tt.x.Tanh()
		if !eq256(got, tt.want) {
			t.Errorf("Tanh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_TanhAccuracy checks that the error of Tanh is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_sinh_testdata.py.
func TestFloat256_TanhAccuracy(t *testing.T) {
	t.Parallel()
	testFloat256Accuracy(t, "testdata/tanh256.txt", "Tanh", Float256.Tanh)
}

func BenchmarkFloat256_Tanh(b *testing.B) {
	benchFloat256(b, Float256.Tanh, []struct {
		name string
		x    Float256
	}{
		{"tiny", exact256(0x1p-120)},  // returns x
		{"small", exact256(0x1p-10)},  // |x| < ln(2)/128
		{"moderate", exact256(0.1)},   // tanh(x) < 1/3
		{"medium", exact256(1.5)},     // tanh(x) = 1 - ε
		{"negative", exact256(-10.3)}, // tanh(-x) = -tanh(x)
		{"near1", exact256(80.5)},     // 1 - ε with a small ε
		{"large", exact256(1000.7)},   // returns 1
	})
}

func TestMulHi256(t *testing.T) {
	t.Parallel()
	const ones = 0xffff_ffff_ffff_ffff
	r := rand.New(rand.NewPCG(256, 512))
	inputs := []ints.Uint256{
		{0, 0, 0, 0},
		{ones, ones, ones, ones},
		{1 << 63, 0, 0, 0},
		{0, 0, 0, 1},
	}
	for range 1000 {
		inputs = append(inputs, ints.Uint256{r.Uint64(), r.Uint64(), r.Uint64(), r.Uint64()})
	}
	for _, a := range inputs {
		for _, b := range inputs[:20] {
			p := a.Mul512(b)
			want := ints.Uint256{p[0], p[1], p[2], p[3]}
			got := mulHi256(a, b)
			// got <= want <= got + 7
			if want.Cmp(got) < 0 || want.Sub(got).Cmp(ints.Uint256{0, 0, 0, 7}) > 0 {
				t.Errorf("mulHi256(%x, %x) = %x; want %x", a, b, got, want)
			}
		}
	}
}
