package floats

import (
	"math"
	"runtime"
	"testing"
)

func TestFloat128_Sinh(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0x1p-100), "7.888609052210118054117285652827862296732064351090230047702790124822869E-31"},
		{exact128(0.25), "0.2526123168081683079141251505420579055197542874276608074880949653019811"},
		{exact128(0.5), "0.5210953054937473616224256264114915591059289826114805279460935764528023"},
		{exact128(1), "1.175201193643801456882381850595600815155717981334095870229565413013308"},
		{exact128(2), "3.62686040784701876766821398280126170488634201232113572130948447493425"},
		{exact128(3), "10.01787492740990189897459361946582806017810412318286346440565325104639"},
		{exact128(4), "27.28991719712775244890827159079381858028941248553029656552849701555721"},
		{exact128(43), "2363919734114673280.737228781372140185304119429310915061152028929774621"},
	}

	for _, tt := range tests {
		got := tt.x.Sinh()
		if !close128(got, tt.want) {
			t.Errorf("Sinh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		{exact128(0), exact128(0)},
		{exact128(math.Copysign(0, -1)), exact128(math.Copysign(0, -1))},

		// special cases
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(math.Inf(-1))},
		{exact128(math.NaN()), exact128(math.NaN())},

		// tiny values: sinh(x) = x + x**3/6 + ... rounds to x
		{Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}, Float128{0x0000_0000_0000_0000, 0x0000_0000_0000_0001}},
		{exact128(-0x1p-16382), exact128(-0x1p-16382)},
		{exact128(0x1p-57), exact128(0x1p-57)},
		{Float128{0x3fc6_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}, Float128{0x3fc6_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}}, // 2**-56 - 2**-169: x**3/6 = 0.33 ulp
		{exact128(-0x1p-56), exact128(-0x1p-56)},                                                                         // x**3/6 = 0.17 ulp
		{Float128{0x3fc7_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff}, Float128{0x3fc8_0000_0000_0000, 0x0000_0000_0000_0000}}, // 2**-55 - 2**-168: x**3/6 = 1.33 ulp

		// overflow
		{exact128(11357), Float128{0x7ffe_9c4e_e6cc_d991, 0x98cf_ae8c_a4db_64a7}},
		{exact128(-11357), Float128{0xfffe_9c4e_e6cc_d991, 0x98cf_ae8c_a4db_64a7}},
		{exact128(11358), exact128(math.Inf(1))},
		{exact128(-11358), exact128(math.Inf(-1))},
		{exact128(0x1p20), exact128(math.Inf(1))},
		{exact128(-0x1p20), exact128(math.Inf(-1))},
	}

	for _, tt := range strictTests {
		got := tt.x.Sinh()
		if !eq128(got, tt.want) {
			t.Errorf("Sinh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat128_SinhAccuracy checks that the error of Sinh is less than 1 ulp,
// and that almost all results are correctly rounded.
// The test data is generated by scripts/gen_sinh_testdata.py.
func TestFloat128_SinhAccuracy(t *testing.T) {
	testFloat128Accuracy(t, "testdata/sinh128.txt", "Sinh", Float128.Sinh)
}

func BenchmarkFloat128_Sinh(b *testing.B) {
	benchFloat128(b, Float128.Sinh, []struct {
		name string
		x    Float128
	}{
		{"tiny", exact128(0x1p-60)},   // returns x
		{"small", exact128(0x1p-10)},  // |x| < ln(2)/128
		{"medium", exact128(1.5)},     // e**-x is not negligible
		{"negative", exact128(-10.3)}, // sinh(-x) = -sinh(x)
		{"large", exact128(1000.7)},   // e**-x is negligible
	})
}

func TestFloat128_Cosh(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0), "1"},
		{exact128(1), "1.543080634815243778477905620757061682601529112365863704737402214710769"},
		{exact128(2), "3.762195691083631459562213477773746108293973558230711602777643347588324"},
		{exact128(3), "10.06766199577776584195393603511588983680980371537128667997328097865245"},
		{exact128(4), "27.30823283601648662920198961206705982250132455308377216029809694299646"},
		{exact128(43), "2363919734114673280.737228781372140185515632533070023109815169030476886"},
	}

	for _, tt := range tests {
		got := tt.x.Cosh()
		if !close128(got, tt.want) {
			t.Errorf("Cosh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		// special cases
		{exact128(0), exact128(1)},
		{exact128(math.Copysign(0, -1)), exact128(1)},
		{exact128(math.Inf(1)), exact128(math.Inf(1))},
		{exact128(math.Inf(-1)), exact128(math.Inf(1))},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Cosh()
		if !eq128(got, tt.want) {
			t.Errorf("Cosh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat128_Cosh(b *testing.B) {
	x := exact128(1.5)
	for b.Loop() {
		runtime.KeepAlive(x.Cosh())
	}
}

func TestFloat128_Tanh(t *testing.T) {
	tests := []struct {
		x    Float128
		want string
	}{
		{exact128(0), "0"},
		{exact128(0.5), "0.4621171572600097585023184836436725487302892803301130385527318158380809"},
		{exact128(1), "0.7615941559557648881194582826047935904127685972579365515968105001219532"},
		{exact128(2), "0.964027580075816883946413724100923150255029976240934776048263217413108"},
		{exact128(3), "0.9950547536867304513318801852554884750978138547002824918238788151306647"},
		{exact128(4), "0.9993292997390670437922433443417249620053398528944096480078068964566789"},
		{exact128(43), "1"},

		{exact128(math.Copysign(0, -1)), "-0"},
		{exact128(-0.5), "-0.4621171572600097585023184836436725487302892803301130385527318158380809"},
		{exact128(-1), "-0.7615941559557648881194582826047935904127685972579365515968105001219532"},
		{exact128(-2), "-0.964027580075816883946413724100923150255029976240934776048263217413108"},
		{exact128(-3), "-0.9950547536867304513318801852554884750978138547002824918238788151306647"},
		{exact128(-4), "-0.9993292997390670437922433443417249620053398528944096480078068964566789"},
		{exact128(-43), "-1"},
	}

	for _, tt := range tests {
		got := tt.x.Tanh()
		if !close128(got, tt.want) {
			t.Errorf("Tanh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float128
		want Float128
	}{
		// special cases
		{exact128(0), exact128(0)},
		{exact128(math.Copysign(0, -1)), exact128(math.Copysign(0, -1))},
		{exact128(math.Inf(1)), exact128(1)},
		{exact128(math.Inf(-1)), exact128(-1)},
		{exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Tanh()
		if !eq128(got, tt.want) {
			t.Errorf("Tanh(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

func BenchmarkFloat128_Tanh(b *testing.B) {
	x := exact128(1.5)
	for b.Loop() {
		runtime.KeepAlive(x.Tanh())
	}
}
