package floats

import (
	"bufio"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestFloat256_Y0(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.001), "-4.4714166113759232557279276675494113171590730468609498648177305588485046592336927"},
		{exact256(0.5), "-0.44451873350670655714839847506833191037356512440151102041489117938823968793141729"},
		{exact256(1), "0.088256964215676957982926766023515162827817523090675546711043847611999789323513371"},
		{exact256(1.5), "0.38244892379775884395506855497808986236771000924182464517797513014755039974558862"},

		// straddling the Temme-series / CF2 boundary (2)
		{exact256(1.999), "0.51026835823865447557070292643556832778336382674848124422971594946785730809487083"},
		{exact256(2), "0.5103756726497451195966065927271578732681392270858461355718392719327313950418218"},
		{exact256(2.001), "0.5104824231689602061977832443854258241607918669049689082643820533654243723593463"},
		{exact256(2.5), "0.49807035961523188782747235036208980611506253265681530429974629407406321557566996"},
		{exact256(5), "-0.30851762524903378007364898421204661138634706162734404379585141589825791564288085"},
		{exact256(10), "0.055671167283599391424459877410190048145128114516905044082297913621922654163521798"},
		{exact256(50), "-0.098064995470077079029211453440370432007912776033783935263768598329777276716501615"},
		{exact256(100), "-0.077244313365083152254228221367198770505698983656635654771942777607654157501137232"},
		{exact256(300), "-0.031831889730003398014844175649005686398193181662568730769387989383460156847584391"},

		// straddling the CF2 / asymptotic boundary (500)
		{exact256(499), "0.03440585598313211012633720827425837088075221477421013858720444451602804906741561"},
		{exact256(499.9), "0.013859981772939215800697423949409403750459421446685020361049043035613807615476519"},
		{exact256(500), "0.010506708739831374099740660626553125825873868927222316347004348599031887576749718"},
		{exact256(500.1), "0.0070491372301601888198967329629044582417273374044759454317320271638157266394728577"},

		{exact256(1000), "0.0047159179776228133997732614656652550098590048968019771852800026829151397602999922"},
		{exact256(5000), "-0.0091167407696439626280591900810422020519599412680762774672728450467982917315632253"},
	}

	for _, tt := range tests {
		got := tt.x.Y0()
		if !close256(got, tt.want) {
			t.Errorf("Y0(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(math.Inf(-1))},
		{exact256(math.Copysign(0, -1)), exact256(math.Inf(-1))},
		{exact256(-1), exact256(math.NaN())},
		{exact256(math.Inf(1)), exact256(0)},
		{exact256(math.Inf(-1)), exact256(math.NaN())},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Y0()
		if !eq256(got, tt.want) {
			t.Errorf("Y0(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_Y0Accuracy checks that the error of Y0 is at most 4 ulps of the
// amplitude of the function: max(|Y0(x)|, 0.2) for x <= 1, and
// max(|Y0(x)|, sqrt(2/(pi x))) for x > 1. Y0 has simple zeros, around which the
// relative error is not bounded by the working precision.
// The test data is generated by scripts/gen_y0_256_testdata.py.
func TestFloat256_Y0Accuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/y0_256.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}

	one := Float256(uvone256)
	pi := Float256{
		0x4000_0921_fb54_442d, 0x1846_9898_cc51_701b,
		0x839a_2520_49c1_114c, 0xf98e_8041_77d4_c762,
	}
	var total int
	var maxErr float64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		amp := exact256(0.2)
		if x.Gt(one) {
			amp = Float256(uvone256).Quo(pi.Mul(x).Quo(exact256(2))).Sqrt()
		}
		if w := want.Abs(); w.Gt(amp) {
			amp = w
		}
		limit := amp.Ldexp(-234)

		got := x.Y0()
		total++
		if r := got.Sub(want).Abs().Quo(amp).Ldexp(236).Float64().BuiltIn(); r > maxErr {
			maxErr = r
		}
		if d := got.Sub(want).Abs(); !d.Lt(limit) && !d.Eq(limit) {
			t.Errorf("Y0(%v) = %v; want %v", x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("max error: %.2f ulps of the amplitude", maxErr)
	if total == 0 {
		t.Fatal("testdata/y0_256.txt has no test cases")
	}
}

func BenchmarkFloat256_Y0(b *testing.B) {
	benchFloat256(b, Float256.Y0, []struct {
		name string
		x    Float256
	}{
		{"series", exact256(1.5)},      // 0 < x < 2
		{"taylor", exact256(10.3)},     // 2 <= x < 128
		{"asymptotic", exact256(1000)}, // x >= 128
	})
}
