package floats

import (
	"bufio"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestFloat256_Y1(t *testing.T) {
	t.Parallel()
	tests := []struct {
		x    Float256
		want string
	}{
		{exact256(0.001), "-636.62216723113941482210526019889109449409544720348295727316419518002998870723973"},
		{exact256(0.5), "-1.4714723926702430691885846353232974532410880554357483229559223834066940909523571"},
		{exact256(1), "-0.78121282130028871654715000004796482054990639071644460784383324612778439153856022"},
		{exact256(1.5), "-0.4123086269739112959528298206334453228850505655834628436270698874122235687588324"},

		// straddling the Temme-series / CF2 boundary (2)
		{exact256(1.999), "-0.10759642423945662741382468923511646100323827097496739232448893451722137126470797"},
		{exact256(2), "-0.10703243154093754688837077227747663668748089823505386052579455723131997749949067"},
		{exact256(2.001), "-0.1064686405140669759119122534417033621518722258153475188590516460709169391371785"},
		{exact256(2.5), "0.14591813796678579887875994053587757127608019654670099984510336876847982786986827"},
		{exact256(5), "0.14786314339122684480105067548803720537346521841047561330069765950868826592621711"},
		{exact256(10), "0.24901542420695388392328347466322280326041654306965846124694374102428875812470242"},
		{exact256(50), "-0.05679566856201476794181954923776336013440662539738030989643580941666844879626385"},
		{exact256(100), "-0.02037231200275979330470393266641455974201865568903699045979928263155680899959383"},
		{exact256(300), "0.033245548121310216055963850587394989576751478357111401256589654985634828686887215"},

		// straddling the CF2 / asymptotic boundary (500)
		{exact256(499), "0.0096275792217240845648119802250710531129132541740351093213462130714185195523992758"},
		{exact256(499.9), "0.032898442617060197700212562770795144489993903880327473607271878827055640705172525"},
		{exact256(500), "0.034111080629137135894793879829631993266090209028926378041899393682782025191675035"},
		{exact256(500.1), "0.03498268493599006204942003020865253161551979605360829140923441598292173076692348"},

		{exact256(1000), "-0.024784331292351778914862356097141290938631854864870528758349019940178780233621799"},
		{exact256(5000), "0.0066480726106254194163431538036595782932417383106815557422920866623726176493977783"},
	}

	for _, tt := range tests {
		got := tt.x.Y1()
		if !close256(got, tt.want) {
			t.Errorf("Y1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		x    Float256
		want Float256
	}{
		{exact256(0), exact256(math.Inf(-1))},
		{exact256(math.Copysign(0, -1)), exact256(math.Inf(-1))},
		{exact256(-1), exact256(math.NaN())},
		{exact256(math.Inf(1)), exact256(0)},
		{exact256(math.Inf(-1)), exact256(math.NaN())},
		{exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Y1()
		if !eq256(got, tt.want) {
			t.Errorf("Y1(%v) = %v; want %v", tt.x, got, tt.want)
		}
	}
}

// TestFloat256_Y1Accuracy checks that the error of Y1 is at most 4 ulps of the
// amplitude of the function: |Y1(x)| for x <= 1, and
// max(|Y1(x)|, sqrt(2/(pi x))) for x > 1. Y1 has simple zeros, around which the
// relative error is not bounded by the working precision.
// The test data is generated by scripts/gen_y1_256_testdata.py.
func TestFloat256_Y1Accuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/y1_256.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}

	one := Float256(uvone256)
	pi := Float256{
		0x4000_0921_fb54_442d, 0x1846_9898_cc51_701b,
		0x839a_2520_49c1_114c, 0xf98e_8041_77d4_c762,
	}
	var total int
	var maxErr float64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		x, want := parse(fields[0]), parse(fields[1])

		amp := want.Abs()
		if x.Gt(one) {
			if a := Float256(uvone256).Quo(pi.Mul(x).Quo(exact256(2))).Sqrt(); a.Gt(amp) {
				amp = a
			}
		}
		limit := amp.Ldexp(-234)

		got := x.Y1()
		total++
		if r := got.Sub(want).Abs().Quo(amp).Ldexp(236).Float64().BuiltIn(); r > maxErr {
			maxErr = r
		}
		if d := got.Sub(want).Abs(); !d.Lt(limit) && !d.Eq(limit) {
			t.Errorf("Y1(%v) = %v; want %v", x, got, want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("max error: %.2f ulps of the amplitude", maxErr)
	if total == 0 {
		t.Fatal("testdata/y1_256.txt has no test cases")
	}
}

func BenchmarkFloat256_Y1(b *testing.B) {
	benchFloat256(b, Float256.Y1, []struct {
		name string
		x    Float256
	}{
		{"series", exact256(1.5)},      // 0 < x < 2
		{"taylor", exact256(10.3)},     // 2 <= x < 128
		{"asymptotic", exact256(1000)}, // x >= 128
	})
}
