package floats

import (
	"bufio"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat128_Yn(t *testing.T) {
	t.Parallel()
	tests := []struct {
		n    int
		x    Float128
		want string
	}{
		{2, exact128(1), "-1.65068260681625439107722676611944480392763030452356476239871"},
		{2, exact128(5), "0.36766288260552451799406925440726149353573314899153428911613"},
		{3, exact128(10), "-0.251362657183837329779204747654240998257634465430847801980107"},
		{5, exact128(50), "-0.0785484139130816533860593716460254382417172847531204243563978"},
		{10, exact128(100), "0.0583315742364149287538281003698965314831449515159684920154777"},
		{2, exact128(0.001), "-1273239.8630456674272162327407159469520946641131068918152382"},
		{2, exact128(300), "0.0320535267174787994552172679862549863287048581849494734444319"},
		{50, exact128(100), "0.0765052639448030404436906505949578081583785578933732082148069"},
		{50, exact128(5000), "0.0104785790803223211492476444352771905965683657175764424987119"},
		{100, exact128(20000), "0.000483277981132536927521177789659793433760125713873992411365294"},
		{1000, exact128(2000001), "-0.000139870600842778303873958406119014935866972430230357041133258"},

		// negative order: Y[-n](x) = (-1)^n Y[n](x)
		{-2, exact128(5), "0.36766288260552451799406925440726149353573314899153428911613"},
		{-3, exact128(10), "0.251362657183837329779204747654240998257634465430847801980107"},
	}

	for _, tt := range tests {
		got := tt.x.Yn(tt.n)
		if !close128(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		n    int
		x    Float128
		want Float128
	}{
		{2, exact128(math.Inf(1)), exact128(0)},
		{2, exact128(0), exact128(math.Inf(-1))},
		{3, exact128(0), exact128(math.Inf(-1))},
		{-2, exact128(0), exact128(math.Inf(-1))},
		{-3, exact128(0), exact128(math.Inf(1))},
		{2, exact128(-1), exact128(math.NaN())},
		{2, exact128(math.NaN()), exact128(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Yn(tt.n)
		if !eq128(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}
}

// TestFloat128_YnAccuracy checks that the error of Yn is at most 4 ulps of the amplitude of the function:
// max(|Yn(x)|, sqrt(2/(pi x))) for x > n, and |Yn(x)| for x <= n. Yn has simple zeros, around which the
// relative error is not bounded by the working precision.
// The test data is generated by scripts/gen_yn_128_testdata.py.
func TestFloat128_YnAccuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/yn_128.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float128 {
		var x Float128
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}

	pi := Float128{0x4000_921f_b544_42d1, 0x8469_898c_c517_01b8}
	var total int
	var maxErr float64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		n, err := strconv.Atoi(fields[0])
		if err != nil {
			t.Fatal(err)
		}
		x, want := parse(fields[1]), parse(fields[2])

		amp := want.Abs()
		if x.Gt(NewFloat128(float64(n))) {
			if a := Float128(uvone128).Quo(pi.Mul(x).Quo(exact128(2))).Sqrt(); a.Gt(amp) {
				amp = a
			}
		}

		got := x.Yn(n)
		total++
		r := got.Sub(want).Abs().Quo(amp).Ldexp(112).Float64().BuiltIn()
		if r > maxErr {
			maxErr = r
		}
		if r > 4 {
			t.Errorf("Yn(%d, %v) = %v; want %v (%.1f ulps)", n, x, got, want, r)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("max error: %.2f ulps of the amplitude", maxErr)
	if total == 0 {
		t.Fatal("testdata/yn_128.txt has no test cases")
	}
}

// BenchmarkFloat128_Yn measures the recurrence, the asymptotic expansion, and the series of Y0 and Y1 for small x.
func BenchmarkFloat128_Yn(b *testing.B) {
	for _, tt := range []struct {
		name string
		n    int
		x    Float128
	}{
		{"n=2,x=0.5", 2, exact128(0.5)},
		{"n=2,x=10.3", 2, exact128(10.3)},
		{"n=10,x=10.3", 10, exact128(10.3)},
		{"n=100,x=10.3", 100, exact128(10.3)},
		{"n=100,x=300", 100, exact128(300)},
		{"n=10,x=1000", 10, exact128(1000)},
		{"n=100,x=20000", 100, exact128(20000)},
		{"n=1000,x=2000001", 1000, exact128(2000001)},
		{"n=1000,x=0.5", 1000, exact128(0.5)},
	} {
		b.Run(tt.name, func(b *testing.B) {
			for b.Loop() {
				runtime.KeepAlive(tt.x.Yn(tt.n))
			}
		})
	}
}

// TestFloat128_YnOverflow checks that Yn overflows to the infinity, not to NaN.
func TestFloat128_YnOverflow(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct {
		n    int
		x    Float128
		want Float128
	}{
		{100000, exact128(0.5), exact128(math.Inf(-1))},
		{-100001, exact128(0.5), exact128(math.Inf(1))},
		{math.MaxInt, exact128(1), exact128(math.Inf(-1))},
		{2, exact128(1).Ldexp(-16400), exact128(math.Inf(-1))}, // Y1(x) overflows
	} {
		if got := tt.x.Yn(tt.n); !eq128(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}
}

// TestFloat128_YnLowOrders checks that Yn(0, x) and Yn(1, x) are Y0 and Y1, and the symmetry of the orders.
func TestFloat128_YnLowOrders(t *testing.T) {
	t.Parallel()
	for _, x := range []Float128{exact128(0.5), exact128(5), exact128(300)} {
		if got, want := x.Yn(0), x.Y0(); !eq128(got, want) {
			t.Errorf("Yn(0, %v) = %v; want %v", x, got, want)
		}
		if got, want := x.Yn(1), x.Y1(); !eq128(got, want) {
			t.Errorf("Yn(1, %v) = %v; want %v", x, got, want)
		}
		if got, want := x.Yn(-1), x.Y1().Neg(); !eq128(got, want) {
			t.Errorf("Yn(-1, %v) = %v; want %v", x, got, want)
		}
	}
}
