package floats

import (
	"bufio"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func TestFloat256_Yn(t *testing.T) {
	t.Parallel()
	tests := []struct {
		n    int
		x    Float256
		want string
	}{
		{2, exact256(1), "-1.6506826068162543910772267661194448039276303045235647623987103398675685724006338"},
		{2, exact256(5), "0.36766288260552451799406925440726149353573314899153428911613047970173322201336769"},
		{3, exact256(10), "-0.25136265718383732977920474765424099825763446543084780198010740719111471914013495"},
		{5, exact256(50), "-0.078548413913081653386059371646025438241717284753120424356397810153710966095349335"},
		{10, exact256(100), "0.058331574236414928753828100369896531483144951515968492015477677074780839108860316"},
		{2, exact256(0.001), "-1273239.86304566742721623274071594695209466411310689181523819918618330619264973"},
		{2, exact256(300), "0.032053526717478799455217267986254986328704858184949473444431920416697722372163639"},
		{50, exact256(100), "0.076505263944803040443690650594957808158378557893373208214806902269705991820455106"},
		{50, exact256(5000), "0.010478579080322321149247644435277190596568365717576442498711858138760433799519299"},
		{100, exact256(20000), "0.00048327798113253692752117778965979343376012571387399241136529376725834304455186727"},
		{1000, exact256(2000001), "-0.00013987060084277830387395840611901493586697243023035704113325841851642069421007276"},

		// negative order: Y[-n](x) = (-1)^n Y[n](x)
		{-2, exact256(5), "0.36766288260552451799406925440726149353573314899153428911613047970173322201336769"},
		{-3, exact256(10), "0.25136265718383732977920474765424099825763446543084780198010740719111471914013495"},
	}

	for _, tt := range tests {
		got := tt.x.Yn(tt.n)
		if !close256(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}

	strictTests := []struct {
		n    int
		x    Float256
		want Float256
	}{
		{2, exact256(math.Inf(1)), exact256(0)},
		{2, exact256(0), exact256(math.Inf(-1))},
		{3, exact256(0), exact256(math.Inf(-1))},
		{-2, exact256(0), exact256(math.Inf(-1))},
		{-3, exact256(0), exact256(math.Inf(1))},
		{2, exact256(-1), exact256(math.NaN())},
		{2, exact256(math.NaN()), exact256(math.NaN())},
	}

	for _, tt := range strictTests {
		got := tt.x.Yn(tt.n)
		if !eq256(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}
}

// TestFloat256_YnAccuracy checks that the error of Yn is at most 4 ulps of the amplitude of the function:
// max(|Yn(x)|, sqrt(2/(pi x))) for x > n, and |Yn(x)| for x <= n. Yn has simple zeros, around which the
// relative error is not bounded by the working precision.
// The test data is generated by scripts/gen_yn_256_testdata.py.
func TestFloat256_YnAccuracy(t *testing.T) {
	t.Parallel()
	f, err := os.Open("testdata/yn_256.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	parse := func(s string) Float256 {
		var x Float256
		for i := range x {
			v, err := strconv.ParseUint(s[16*i:16*(i+1)], 16, 64)
			if err != nil {
				t.Fatal(err)
			}
			x[i] = v
		}
		return x
	}

	pi := Float256{
		0x4000_0921_fb54_442d, 0x1846_9898_cc51_701b,
		0x839a_2520_49c1_114c, 0xf98e_8041_77d4_c762,
	}
	var total int
	var maxErr float64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		n, err := strconv.Atoi(fields[0])
		if err != nil {
			t.Fatal(err)
		}
		x, want := parse(fields[1]), parse(fields[2])

		amp := want.Abs()
		if x.Gt(NewFloat256(float64(n))) {
			if a := Float256(uvone256).Quo(pi.Mul(x).Quo(exact256(2))).Sqrt(); a.Gt(amp) {
				amp = a
			}
		}

		got := x.Yn(n)
		total++
		r := got.Sub(want).Abs().Quo(amp).Ldexp(236).Float64().BuiltIn()
		if r > maxErr {
			maxErr = r
		}
		if r > 4 {
			t.Errorf("Yn(%d, %v) = %v; want %v (%.1f ulps)", n, x, got, want, r)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("max error: %.2f ulps of the amplitude", maxErr)
	if total == 0 {
		t.Fatal("testdata/yn_256.txt has no test cases")
	}
}

// BenchmarkFloat256_Yn measures the recurrence, the asymptotic expansion, and the series of Y0 and Y1 for small x.
func BenchmarkFloat256_Yn(b *testing.B) {
	for _, tt := range []struct {
		name string
		n    int
		x    Float256
	}{
		{"n=2,x=0.5", 2, exact256(0.5)},
		{"n=2,x=10.3", 2, exact256(10.3)},
		{"n=10,x=10.3", 10, exact256(10.3)},
		{"n=100,x=10.3", 100, exact256(10.3)},
		{"n=100,x=300", 100, exact256(300)},
		{"n=10,x=1000", 10, exact256(1000)},
		{"n=100,x=20000", 100, exact256(20000)},
		{"n=1000,x=2000001", 1000, exact256(2000001)},
		{"n=1000,x=0.5", 1000, exact256(0.5)},
	} {
		b.Run(tt.name, func(b *testing.B) {
			for b.Loop() {
				runtime.KeepAlive(tt.x.Yn(tt.n))
			}
		})
	}
}

// TestFloat256_YnOverflow checks that Yn overflows to the infinity, not to NaN.
func TestFloat256_YnOverflow(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct {
		n    int
		x    Float256
		want Float256
	}{
		{100000, exact256(0.5), exact256(math.Inf(-1))},
		{-100001, exact256(0.5), exact256(math.Inf(1))},
		{math.MaxInt, exact256(1), exact256(math.Inf(-1))},
		{2, exact256(1).Ldexp(-262300), exact256(math.Inf(-1))}, // Y1(x) overflows
	} {
		if got := tt.x.Yn(tt.n); !eq256(got, tt.want) {
			t.Errorf("Yn(%d, %v) = %v; want %v", tt.n, tt.x, got, tt.want)
		}
	}
}

// TestFloat256_YnLowOrders checks that Yn(0, x) and Yn(1, x) are Y0 and Y1, and the symmetry of the orders.
func TestFloat256_YnLowOrders(t *testing.T) {
	t.Parallel()
	for _, x := range []Float256{exact256(0.5), exact256(5), exact256(300)} {
		if got, want := x.Yn(0), x.Y0(); !eq256(got, want) {
			t.Errorf("Yn(0, %v) = %v; want %v", x, got, want)
		}
		if got, want := x.Yn(1), x.Y1(); !eq256(got, want) {
			t.Errorf("Yn(1, %v) = %v; want %v", x, got, want)
		}
		if got, want := x.Yn(-1), x.Y1().Neg(); !eq256(got, want) {
			t.Errorf("Yn(-1, %v) = %v; want %v", x, got, want)
		}
	}
}
