#!/usr/bin/env python3
# Generates erf256_table.go, the constants used by Float256 Erf.
# The numbers are in fixed point with 320 fractional bits in six 64-bit words, the first of which is the integer part,
# unless otherwise noted.
#
# Usage: python3 scripts/gen_erf256_table.py > erf256_table.go

import mpmath

mpmath.mp.prec = 1500

F = 320
# erf(x) for x in [k/16, (k+1)/16) is calculated by the Taylor series around the center x0 = (k + 1/2)/16:
# erf(x0+h) = erf(x0) + 2/sqrt(pi) exp(-x0**2) sum_n b_n h**(n+1)/(n+1), where exp(-2 x0 h - h**2) = sum b_n h**n.
CELLS = 204  # erf(x) is rounded to 1 for x >= 12.722
TAIL_BITS = 330  # the tail of the series is less than 2**-TAIL_BITS
SMALL_TERMS = 22  # the number of the terms of the series for |x| < 2**-8
# For the cells k >= LARGE_CELL, erf(x) is rounded from 1 - erfc(x), and erfc(x) is calculated in a relative accuracy.
LARGE_CELL = 112


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def e0_of(k):
    x0 = mpmath.mpf(2 * k + 1) / 32
    return 2 / mpmath.sqrt(mpmath.pi) * mpmath.exp(-x0 * x0)


def terms(k):
    """returns the number of the terms of the Taylor series for the cell k."""
    x0 = mpmath.mpf(2 * k + 1) / 32
    h = mpmath.mpf(1) / 32
    e0 = e0_of(k)
    if k >= LARGE_CELL:
        # erfc(x) is calculated in a relative accuracy
        e0 = e0 / mpmath.erfc(x0)
    b = [mpmath.mpf(1), -2 * x0]
    n = 1
    while True:
        while len(b) <= n + 1:
            m = len(b) - 1
            b.append(-(2 * x0 * b[m] + 2 * b[m - 1]) / (m + 1))
        if e0 * abs(b[n]) * h ** (n + 1) / (n + 1) < mpmath.mpf(2) ** -TAIL_BITS and e0 * abs(b[n + 1]) * h ** (n + 2) / (n + 2) < mpmath.mpf(2) ** -TAIL_BITS:
            return n
        n += 1


def mant_exp(x):
    e = int(mpmath.floor(mpmath.log(x, 2)))
    return x / mpmath.mpf(2) ** e, e


def main():
    print("// Code generated by scripts/gen_erf256_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print("// erf256TwoOverSqrtPi is 2/sqrt(pi).")
    print(f"var erf256TwoOverSqrtPi = [6]uint64{{{limbs(fix(2 / mpmath.sqrt(mpmath.pi)))}}}")
    print()

    print("// erf256Small[n] is 1/(n! (2n+1)), the coefficient of erf(x) = 2/sqrt(pi) x sum (-x**2)**n/(n! (2n+1)).")
    print("var erf256Small = [...][6]uint64{")
    for n in range(SMALL_TERMS):
        print(f"\t{{{limbs(fix(1 / (mpmath.factorial(n) * (2 * n + 1))))}}}, // n = {n}")
    print("}")
    print()

    print(f"// erf256Erf[k] is erf(x0) for the cells k < {LARGE_CELL}, where x0 = (k + 1/2)/16.")
    print("var erf256Erf = [...][6]uint64{")
    for k in range(LARGE_CELL):
        print(f"\t{{{limbs(fix(mpmath.erf(mpmath.mpf(2 * k + 1) / 32)))}}},")
    print("}")
    print()
    print("// erf256E0[k] is the mantissa m of 2/sqrt(pi) exp(-x0**2) = m × 2**erf256E0Exp[k], where m is in [1, 2),")
    print(f"// for the cells k < {LARGE_CELL}.")
    print("var erf256E0 = [...][6]uint64{")
    exps = []
    for k in range(LARGE_CELL):
        m, e = mant_exp(e0_of(k))
        exps.append(e)
        print(f"\t{{{limbs(fix(m))}}},")
    print("}")
    print()
    print("// erf256E0Exp[k] is the exponent of 2/sqrt(pi) exp(-x0**2).")
    print("var erf256E0Exp = [...]int16{")
    print("\t" + ", ".join(str(e) for e in exps) + ",")
    print("}")
    print()

    print(f"// erf256Es[k-{LARGE_CELL}] is the mantissa m of erfc(x0) × 2**237 = m × 2**erf256EsExp[k-{LARGE_CELL}], where m is in [1, 2),")
    print(f"// for the cells k >= {LARGE_CELL}.")
    print("var erf256Es = [...][6]uint64{")
    exps = []
    for k in range(LARGE_CELL, CELLS):
        m, e = mant_exp(mpmath.erfc(mpmath.mpf(2 * k + 1) / 32) * mpmath.mpf(2) ** 237)
        exps.append(e)
        print(f"\t{{{limbs(fix(m))}}},")
    print("}")
    print()
    print("// erf256EsExp is the exponents of erf256Es.")
    print("var erf256EsExp = [...]int16{")
    print("\t" + ", ".join(str(e) for e in exps) + ",")
    print("}")
    print()
    print(f"// erf256R[k-{LARGE_CELL}] is 2/sqrt(pi) exp(-x0**2) / erfc(x0) for the cells k >= {LARGE_CELL}.")
    print("var erf256R = [...][6]uint64{")
    for k in range(LARGE_CELL, CELLS):
        x0 = mpmath.mpf(2 * k + 1) / 32
        print(f"\t{{{limbs(fix(e0_of(k) / mpmath.erfc(x0)))}}},")
    print("}")
    print()

    print("// erf256Terms[k] is the number of the terms of the Taylor series of the cell k.")
    print("var erf256Terms = [...]uint8{")
    print("\t" + ", ".join(str(terms(k)) for k in range(CELLS)) + ",")
    print("}")


main()
