#!/usr/bin/env python3
# Generates pi4_table.go, the binary expansion of 4/pi used for
# Payne-Hanek argument reduction of trigonometric functions.
#
# Usage: python3 scripts/gen_pi4_table.py > pi4_table.go

import mpmath

# Float256 has 19-bit exponent: the largest finite value is < 2^262144.
# Payne-Hanek reduction reads about 832 bits beyond the exponent,
# so 4110 words (= 1 integer word + 4109 * 64 fractional bits) are enough.
WORDS = 4110

mpmath.mp.prec = 64 * WORDS + 128
v = int(mpmath.floor(4 / mpmath.pi * mpmath.mpf(2) ** (64 * (WORDS - 1))))

print("// Code generated by scripts/gen_pi4_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// mPi4Long is the binary expansion of 4/pi.")
print("// mPi4Long[0] holds the integer part, and the fractional bits follow")
print("// from the most significant bit of mPi4Long[1].")
print("var mPi4Long = [...]uint64{")
for i in range(WORDS):
    w = (v >> (64 * (WORDS - 1 - i))) & (2**64 - 1)
    print(f"\t0x{w:016x},")
print("}")
