#!/usr/bin/env python3
# Generates gamma16_table.go, the coefficients of the polynomials used by Float16 Gamma:
# the piecewise polynomials of Gamma(x), and the polynomial of sin(pi r)/(pi r).
#
# Usage: python3 scripts/gen_gamma16_table.py > gamma16_table.go

import mpmath

mpmath.mp.prec = 300

# Gamma(x) is approximated for x in [FIRST/16, (LAST+1)/16) by the polynomials of degree DEGREE
# in t = x - (s + 1/2)/16, for each segment s = x*16 in [FIRST, LAST].
FIRST = 16
LAST = 208
DEGREE = 5


def fit(s):
    """returns the coefficients of the polynomial in t for the segment s, which interpolates at the Chebyshev nodes."""
    h = mpmath.mpf(1) / 16
    c = (mpmath.mpf(s) + mpmath.mpf(1) / 2) * h
    n = DEGREE + 1
    nodes = [h / 2 * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = mpmath.gamma(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return c, [coeffs[j] for j in range(n)]


SINC_TERMS = 7


def fit_sinc():
    """returns the coefficients of the polynomial in u = r**2 of sin(pi r)/(pi r) for |r| <= 1/2."""
    n = SINC_TERMS
    nodes = [mpmath.mpf(1) / 4 * (1 + mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n))) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, u in enumerate(nodes):
        r = mpmath.sqrt(u)
        for j in range(n):
            a[i, j] = u**j
        b[i] = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
    coeffs = mpmath.lu_solve(a, b)
    return [coeffs[j] for j in range(n)]


def sinc_max_error(coeffs):
    worst = mpmath.mpf(0)
    for k in range(1, 401):
        r = mpmath.mpf(k) / 800
        p = sum(mpmath.mpf(float(coeffs[j])) * r ** (2 * j) for j in range(SINC_TERMS))
        g = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
        worst = max(worst, abs(p - g) / g)
    return worst


def max_error(c, coeffs):
    h = mpmath.mpf(1) / 16
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        t = h / 2 * mpmath.mpf(k) / 32
        p = sum(mpmath.mpf(float(coeffs[j])) * t**j for j in range(DEGREE + 1))
        g = mpmath.gamma(c + t)
        worst = max(worst, abs(p - g) / g)
    return worst


if __name__ == "__main__":
    worst = 0
    rows = []
    for s in range(FIRST, LAST + 1):
        c, coeffs = fit(s)
        err = max_error(c, [float(v) for v in coeffs])
        worst = max(worst, err)
        rows.append([float(v) for v in coeffs])
    print("// Code generated by scripts/gen_gamma16_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print("// gamma16Coeffs[s-16] are the coefficients c0, c1, ..., c5 of the polynomial c0 + c1 t + ... + c5 t**5,")
    print(f"// which approximates Gamma(x) for x in [s/16, (s+1)/16), where t = x - (s + 1/2)/16 and s = {FIRST}, ..., {LAST}.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print("var gamma16Coeffs = [...][6]float64{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
    sinc = fit_sinc()
    print()
    print("// gamma16SincCoeffs are the coefficients of the polynomial of u = r**2, which approximates sin(pi r)/(pi r) for |r| <= 1/2.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(sinc_max_error(sinc), 2))}.")
    print("var gamma16SincCoeffs = [...]float64{")
    print("\t" + ", ".join(float(v).hex() for v in sinc) + ",")
    print("}")
