#!/usr/bin/env python3
# Generates gamma256_mul.go, the truncated multiplications used by Float256 Gamma.
#
# Usage: python3 scripts/gen_gamma256_mul.py | gofmt > gamma256_mul.go


def gen(n):
    lines = []
    w = lines.append
    w(f"// gammaMul256n{n} returns about a × b from the upper {n} words of a and b, that is, with {64 * (n - 1)} fractional bits.")
    w(f"func gammaMul256n{n}(a, b *gammaFix256) gammaFix256 {{")
    w("\tvar r gammaFix256")
    w("\tvar c0, c1, c2, cy uint64")
    # The position p has the weight 2**(-64p). The product of a[i] and b[j] is hi × 2**(-64(i+j-1)) + lo × 2**(-64(i+j)).
    # The columns are processed from the least significant one, and the accumulator is (c2:c1:c0) at the column p.
    # The lower part of the pairs with i+j = n+1 is dropped.
    first = True
    for i in range(1, n):
        j = n + 1 - i
        if j >= n:
            continue
        w(f"\th{i}{j}, _ := bits.Mul64(a[{i}], b[{j}])")
        w(f"\tc0, cy = bits.Add64(c0, h{i}{j}, 0)")
        w("\tc1 += cy")
    for p in range(n, -1, -1):
        w(f"\t// the position {p}")
        for i in range(n):
            j = p - i
            if 0 <= j < n:
                w(f"\th{i}{j}, l{i}{j} := bits.Mul64(a[{i}], b[{j}])")
                w(f"\tc0, cy = bits.Add64(c0, l{i}{j}, 0)")
                w(f"\tc1, cy = bits.Add64(c1, h{i}{j}, cy)")
                w("\tc2 += cy")
        if p < n:
            w(f"\tr[{p}] = c0")
        w("\tc0, c1, c2 = c1, c2, 0")
    w("\treturn r")
    w("}")
    return "\n".join(lines)


print("// Code generated by scripts/gen_gamma256_mul.py; DO NOT EDIT.")
print()
print("package floats")
print()
print('import "math/bits"')
print()
for n in range(2, 7):
    print(gen(n))
    print()
