#!/usr/bin/env python3
# Generates erfinv16_table.go, the coefficients of the polynomials used by Float16 Erfinv:
# the polynomial of erfinv(x)/x in u = x**2 for x < 1/8, the piecewise polynomials of erfinv(x) for 1/8 <= x < 1/2,
# and the piecewise polynomials of erfinv(1-t) in t for 1/2 <= x < 1, where t = 1 - x.
#
# Usage: python3 scripts/gen_erfinv16_table.py > erfinv16_table.go

import importlib.util
import os

import mpmath

mpmath.mp.prec = 300

spec = importlib.util.spec_from_file_location("erf16", os.path.join(os.path.dirname(__file__), "gen_erf16_table.py"))
erf16 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(erf16)

DEGREE = 6
SMALL_DEGREE = 5
# 1 - x for the largest Float16 value less than 1 is 2**-11.
MIN_T_EXP = -11


def seg_of(x):
    return erf16.seg_of(x)


def table(f, first, last):
    rows = []
    worst = mpmath.mpf(0)
    for s in range(first, last + 1):
        c, h = erf16.seg_range(s)
        coeffs = erf16.fit(f, c, h, DEGREE)
        worst = max(worst, erf16.max_error(f, c, h, coeffs))
        rows.append(coeffs)
    return rows, worst


def emit(name, doc, rows, worst):
    print(doc)
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var {name} = [...][{DEGREE + 1}]float64{{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
    print()


if __name__ == "__main__":
    mid_first = seg_of(0.125)
    mid_last = seg_of(0.5) - 1
    hi_first = seg_of(2.0 ** MIN_T_EXP)
    hi_last = seg_of(0.5)
    mid, mid_worst = table(mpmath.erfinv, mid_first, mid_last)
    hi, hi_worst = table(lambda t: mpmath.erfinv(1 - t), hi_first, hi_last)

    # erfinv(x)/x = P(u), u = x**2, for 0 <= x < 1/8.
    umax = mpmath.mpf(1) / 64
    n = SMALL_DEGREE + 1
    nodes = [umax / 2 * (1 + mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n))) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, u in enumerate(nodes):
        x = mpmath.sqrt(u)
        for j in range(n):
            a[i, j] = u**j
        b[i] = mpmath.erfinv(x) / x
    small = [float(c) for c in mpmath.lu_solve(a, b)]
    small_worst = mpmath.mpf(0)
    for k in range(1, 201):
        x = mpmath.mpf(1) / 8 * k / 200
        p = sum(mpmath.mpf(small[j]) * x ** (2 * j) for j in range(n))
        small_worst = max(small_worst, abs(p - mpmath.erfinv(x) / x) / (mpmath.erfinv(x) / x))

    print("// Code generated by scripts/gen_erfinv16_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    emit(
        "erfinv16MidCoeffs",
        f"// erfinv16MidCoeffs[s-{mid_first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},\n"
        "// which approximates erfinv(x) for x in the segment s, where t = x - the center of the segment.\n"
        "// The segment s of x is the exponent and the upper three bits of the fraction of the float64 representation of x,\n"
        f"// s = {mid_first}, ..., {mid_last} (1/8 <= x < 1/2).",
        mid,
        mid_worst,
    )
    emit(
        "erfinv16HiCoeffs",
        f"// erfinv16HiCoeffs[s-{hi_first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 s + ... + c{DEGREE} s**{DEGREE},\n"
        "// which approximates erfinv(1-t) for t in the segment s, where s = t - the center of the segment.\n"
        "// The segment of t is the exponent and the upper three bits of the fraction of the float64 representation of t,\n"
        f"// {hi_first}, ..., {hi_last} (1/2 <= x < 1).",
        hi,
        hi_worst,
    )
    print("// erfinv16SmallCoeffs are the coefficients of the polynomial of u = x**2, which approximates erfinv(x)/x for 0 <= x < 1/8.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(small_worst, 2))}.")
    print("var erfinv16SmallCoeffs = [...]float64{")
    print("\t" + ", ".join(v.hex() for v in small) + ",")
    print("}")
