#!/usr/bin/env python3
# Generates j0256_table.go, the constants used by Float256 J0.
# The numbers are in fixed point with 320 fractional bits in six 64-bit words, the first of which is the integer part.
#
# Usage: python3 scripts/gen_j0256_table.py > j0256_table.go

import mpmath

mpmath.mp.prec = 1000

F = 320


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_j0256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// j0256TwoOverPi is 2/pi.")
print(f"var j0256TwoOverPi = [6]uint64{{{limbs(fix(2 / mpmath.pi))}}}")
print()
print("// j0256HalfSqrt2 is sqrt(2)/2.")
print(f"var j0256HalfSqrt2 = [6]uint64{{{limbs(fix(mpmath.sqrt(2) / 2))}}}")
print()
# The zeros of J0 below ZERO_LIMIT, where J0 is calculated by the Taylor series around the nearest zero if |J0| is small.
ZERO_LIMIT = 256
zeros = []
k = 1
while True:
    z = mpmath.besseljzero(0, k)
    if z >= ZERO_LIMIT:
        break
    zeros.append(z)
    k += 1

print("// j0256Zeros[k-1] is the k-th positive zero of J0 in fixed point with 504 fractional bits in eight 64-bit words,")
print("// the first of which has the integer part in the highest 8 bits.")
print(f"var j0256Zeros = [...][8]uint64{{")
for z in zeros:
    print(f"\t{{{limbs(fix(z, 504), 8)}}},")
print("}")
print()
print("// j0256ZeroJ1[k-1] is |J1(z)| for the k-th zero z of J0, in fixed point with 320 fractional bits. The sign of J1(z) is (-1)**(k+1).")
print("var j0256ZeroJ1 = [...][6]uint64{")
for z in zeros:
    print(f"\t{{{limbs(fix(abs(mpmath.besselj(1, z))))}}},")
print("}")
