#!/usr/bin/env python3
# Generates erfc32_table.go, the coefficients of the piecewise polynomials of erfc(x) for 0 <= x < 10.06 used by Float32 Erfc.
# The segments have the same width 1/32.
#
# Usage: python3 scripts/gen_erfc32_table.py > erfc32_table.go

import mpmath

mpmath.mp.prec = 300

DEGREE = 8
# the width of the segments is 1/WIDTH.
WIDTH = 32
# erfc(x) is rounded to 0 in Float32 for x >= LAST.
LAST = 10.054195404052734375


def fit(f, c, h, degree):
    """returns the coefficients of the polynomial in t = x - c for f, which interpolates at the Chebyshev nodes."""
    n = degree + 1
    nodes = [h * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = f(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def max_error(f, c, h, coeffs):
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        t = h * mpmath.mpf(k) / 33
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(len(coeffs)))
        g = f(c + t)
        worst = max(worst, abs(p - g) / abs(g))
    return worst


if __name__ == "__main__":
    last = int(LAST * WIDTH)
    rows = []
    worst = mpmath.mpf(0)
    h = mpmath.mpf(1) / WIDTH / 2
    for s in range(last + 1):
        c = (s + mpmath.mpf(1) / 2) / WIDTH
        coeffs = fit(mpmath.erfc, c, h, DEGREE)
        worst = max(worst, max_error(mpmath.erfc, c, h, coeffs))
        rows.append(coeffs)

    print("// Code generated by scripts/gen_erfc32_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// erfc32Coeffs[s] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
    print("// which approximates erfc(x) for x in the segment s, where t = x - the center of the segment.")
    print(f"// The segment s of x is floor(x × {WIDTH}), s = 0, ..., {last}.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var erfc32Coeffs = [...][{DEGREE + 1}]float64{{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
