#!/usr/bin/env python3
# Generates lgamma256_table.go, the coefficients of the Taylor series used by Float256 Lgamma.
# The numbers are in fixed point with 320 fractional bits in six 64-bit words, the first of which is the integer part.
#
# Usage: python3 scripts/gen_lgamma256_table.py > lgamma256_table.go

import mpmath

mpmath.mp.prec = 1000

F = 320
# The Taylor series are used for |t| < 2**-NEAR_BITS, and the tails are less than 2**-TAIL_BITS.
NEAR_BITS = 18
TAIL_BITS = 306


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def terms(coeff):
    """returns the number of the terms of the series sum coeff(k) t**(k-1) for |t| < 2**-NEAR_BITS."""
    k = 1
    while coeff(k + 1) * mpmath.mpf(2) ** (-NEAR_BITS * k) >= mpmath.mpf(2) ** -TAIL_BITS:
        k += 1
    return k


def main():
    c = lambda k: mpmath.euler if k == 1 else mpmath.zeta(k) / k
    d = lambda k: 1 - mpmath.euler if k == 1 else (mpmath.zeta(k) - 1) / k
    n1, n2 = terms(c), terms(d)

    print("// Code generated by scripts/gen_lgamma256_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print("// lgamma256Taylor1[k-1] is c_k, the coefficient of the Taylor series Lgamma(1+t) = sum (-1)**k c_k t**k, c_1 = gamma and")
    print("// c_k = zeta(k)/k. The series is used for |t| < 2**-18.")
    print(f"var lgamma256Taylor1 = [{n1}][6]uint64{{")
    for k in range(1, n1 + 1):
        print(f"\t{{{limbs(fix(c(k)))}}}, // k = {k}")
    print("}")
    print()
    print("// lgamma256Taylor2[k-1] is d_k, the coefficient of the Taylor series Lgamma(2+t) = d_1 t + sum (-1)**k d_k t**k for k >= 2,")
    print("// d_1 = 1-gamma and d_k = (zeta(k)-1)/k. The series is used for |t| < 2**-18.")
    print(f"var lgamma256Taylor2 = [{n2}][6]uint64{{")
    for k in range(1, n2 + 1):
        print(f"\t{{{limbs(fix(d(k)))}}}, // k = {k}")
    print("}")


main()
