#!/usr/bin/env python3
# Generates log128_table.go, the table-driven reduction constants used by Float128 Log.
#
# Usage: python3 scripts/gen_log_table.py > log128_table.go

import mpmath

mpmath.mp.prec = 400

N = 256
P = 112
BIAS = 16383


def limbs192(v):
    return [(v >> (64 * (2 - i))) & (2**64 - 1) for i in range(3)]


def round_bits(y):
    s = 1 if y < 0 else 0
    y = abs(y)
    if y == 0:
        return (s << 63, 0)
    e = int(mpmath.floor(mpmath.log(y, 2)))
    m = int(mpmath.nint(y * mpmath.mpf(2) ** (P - e)))
    if m >> (P + 1):
        m >>= 1
        e += 1
    hi = (s << 63) | ((e + BIAS) << 48) | ((m >> 64) & 0xFFFFFFFFFFFF)
    lo = m & 0xFFFFFFFFFFFFFFFF
    return (hi, lo)


def decode(hi):
    s = hi[0] >> 63
    e = ((hi[0] >> 48) & 0x7FFF) - BIAS - P
    m = ((hi[0] & 0xFFFFFFFFFFFF) | (1 << 48)) * (1 << 64) | hi[1]
    v = mpmath.mpf(m) * mpmath.mpf(2) ** e
    return -v if s else v


def to_float128_pair(x):
    # a double-Float128 (hi, lo) representation of x, accurate to ~226 bits.
    if x == 0:
        return (0, 0), (0, 0)
    hi = round_bits(x)
    residual = x - decode(hi)
    lo = round_bits(residual) if residual != 0 else (0, 0)
    return hi, lo


print("// Code generated by scripts/gen_log_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// logTable128 entries for idx in [0,256): breakpoint c_i = 1 + (idx+0.5)/256.")
print("// Log handles idx 0 and 255 itself, without a table lookup, so their entries")
print("// here (for the usual midpoint c_i, not the power of two Log uses instead)")
print("// are unused.")
print("// invC is 1/c_i in fixed point with 192 fractional bits.")
print("// logCHi/logCLo are a double-Float128 (hi+lo) representation of log(c_i).")
print("var logInvC128 = [256][3]uint64{")
logcs = []
for idx in range(N):
    c = 1 + mpmath.mpf(idx + mpmath.mpf("0.5")) / N
    invc = 1 / c
    invc_raw = int(mpmath.nint(invc * mpmath.mpf(2) ** 192))
    if invc_raw >= (1 << 192):
        invc_raw = (1 << 192) - 1
    l = limbs192(invc_raw)
    print(f"\t{{0x{l[0]:016x}, 0x{l[1]:016x}, 0x{l[2]:016x}}},")
    logcs.append(mpmath.log(c))
print("}")
print()
print("var logCHi128 = [256]Float128{")
his = []
los = []
for c in logcs:
    hi, lo = to_float128_pair(c)
    his.append(hi)
    los.append(lo)
    print(f"\t{{0x{hi[0]:016x}, 0x{hi[1]:016x}}},")
print("}")
print()
print("var logCLo128 = [256]Float128{")
for lo in los:
    print(f"\t{{0x{lo[0]:016x}, 0x{lo[1]:016x}}},")
print("}")
