#!/usr/bin/env python3
# Generates erfc16_table.go, the coefficients of the piecewise polynomials of erfc(x) used by Float16 Erfc
# for 1/8 <= x < 3.92. (erfc(x) for x < 1/8 uses the polynomial of erf in erf16_table.go.)
#
# Usage: python3 scripts/gen_erfc16_table.py > erfc16_table.go

import struct

import mpmath

mpmath.mp.prec = 300

DEGREE = 10
SMALL_DEGREE = 5
# erfc(x) is rounded to 0 in Float16 for x >= LAST.
LAST = 3.919921875


def seg_of(x):
    """returns the segment of x, which is the exponent and the upper three bits of the fraction of the float64 representation."""
    return struct.unpack(">Q", struct.pack(">d", x))[0] >> 49


def seg_range(s):
    """returns the center and the half width of the segment s."""
    e = (s >> 3) - 1023
    lo = (1 + mpmath.mpf(s & 7) / 8) * mpmath.mpf(2) ** e
    h = mpmath.mpf(2) ** e / 16
    return lo + h, h


def fit(f, c, h, degree):
    """returns the coefficients of the polynomial in t = x - c for f, which interpolates at the Chebyshev nodes."""
    n = degree + 1
    nodes = [h * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = f(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def max_error(f, c, h, coeffs):
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        t = h * mpmath.mpf(k) / 33
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(len(coeffs)))
        g = f(c + t)
        worst = max(worst, abs(p - g) / abs(g))
    return worst


if __name__ == "__main__":
    first = seg_of(0.125)
    last = seg_of(LAST)
    rows = []
    worst = mpmath.mpf(0)
    for s in range(first, last + 1):
        c, h = seg_range(s)
        coeffs = fit(mpmath.erfc, c, h, DEGREE)
        worst = max(worst, max_error(mpmath.erfc, c, h, coeffs))
        rows.append(coeffs)

    print("// Code generated by scripts/gen_erfc16_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// erfc16Coeffs[s-{first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
    print("// which approximates erfc(x) for x in the segment s, where t = x - the center of the segment.")
    print("// The segment s of x is the exponent and the upper three bits of the fraction of the float64 representation of x,")
    print(f"// s = {first}, ..., {last}.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var erfc16Coeffs = [...][{DEGREE + 1}]float64{{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
