#!/usr/bin/env python3
# Generates atan128_table.go, the table-driven reduction constants used by Float128 Atan2.
#
# Usage: python3 scripts/gen_atan2_table.py > atan128_table.go

import mpmath

mpmath.mp.prec = 400

N = 64
P = 112
BIAS = 16383


def round_bits(y):
    s = 1 if y < 0 else 0
    y = abs(y)
    if y == 0:
        return (s << 63, 0)
    e = int(mpmath.floor(mpmath.log(y, 2)))
    m = int(mpmath.nint(y * mpmath.mpf(2) ** (P - e)))
    if m >> (P + 1):
        m >>= 1
        e += 1
    hi = (s << 63) | ((e + BIAS) << 48) | ((m >> 64) & 0xFFFFFFFFFFFF)
    lo = m & 0xFFFFFFFFFFFFFFFF
    return (hi, lo)


def decode(hi):
    s = hi[0] >> 63
    e = ((hi[0] >> 48) & 0x7FFF) - BIAS - P
    m = ((hi[0] & 0xFFFFFFFFFFFF) | (1 << 48)) * (1 << 64) | hi[1]
    v = mpmath.mpf(m) * mpmath.mpf(2) ** e
    return -v if s else v


def to_float128_pair(x):
    # a double-Float128 (hi, lo) representation of x, accurate to ~226 bits.
    if x == 0:
        return (0, 0), (0, 0)
    hi = round_bits(x)
    residual = x - decode(hi)
    lo = round_bits(residual) if residual != 0 else (0, 0)
    return hi, lo


def fmt(v):
    return f"{{0x{v[0]:016x}, 0x{v[1]:016x}}}"


print("// Code generated by scripts/gen_atan2_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// atan2TableHi128[i] + atan2TableLo128[i] is a double-Float128 representation of")
print("// atan(i/64) for i = 0, ..., 64.")
his = []
los = []
for i in range(N + 1):
    hi, lo = to_float128_pair(mpmath.atan(mpmath.mpf(i) / N))
    his.append(hi)
    los.append(lo)
print(f"var atan2TableHi128 = [{N + 1}]Float128{{")
for hi in his:
    print(f"\t{fmt(hi)},")
print("}")
print()
print(f"var atan2TableLo128 = [{N + 1}]Float128{{")
for lo in los:
    print(f"\t{fmt(lo)},")
print("}")
print()
print("// atan2Coeffs128[k] is (-1)**(k+1)/(2k+3) for k = 0, ..., 8, the coefficients of")
print("// (atan(u) - u)/u**3 = -1/3 + z/5 - z**2/7 + ... in terms of z = u**2.")
print("var atan2Coeffs128 = [9]Float128{")
for k in range(9):
    v = mpmath.mpf((-1) ** (k + 1)) / (2 * k + 3)
    print(f"\t{fmt(round_bits(v))}, // {'-' if k % 2 == 0 else ''}1/{2 * k + 3}")
print("}")
print()
pi2 = mpmath.pi / 2
hi, lo = to_float128_pair(pi2)
print("// atan2Pi2Hi128 + atan2Pi2Lo128 is a double-Float128 representation of pi/2.")
print(f"var atan2Pi2Hi128 = Float128{fmt(hi)}")
print(f"var atan2Pi2Lo128 = Float128{fmt(lo)}")
