#!/usr/bin/env python3
# Generates log256_table.go, the table-driven reduction constants used by Float256 Log.
#
# Usage: python3 scripts/gen_log256_table.py > log256_table.go

import mpmath

mpmath.mp.prec = 1024

N = 256
# the number of the coefficients of log(1+r)/r for |r| < 2**-8
TERMS = 33


def fix(x, frac_bits):
    return int(mpmath.nint(x * mpmath.mpf(2) ** frac_bits))


def limbs(v, n):
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_log256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// log256Ln2 is ln(2) * 2**320.")
print(f"var log256Ln2 = [5]uint64{{{limbs(fix(mpmath.log(2), 320), 5)}}}")
print()
print("// log256InvC[idx] is 1/c in fixed point with 256 fractional bits,")
print("// where c is the breakpoint of the bucket idx: c = 1 + (idx+0.5)/256 for 0 < idx < 255.")
print("// Log handles idx 0 (c = 1) itself, so its entry is unused. idx 255 is c = 2.")
print("var log256InvC = [256][4]uint64{")
invcs = []
for idx in range(N):
    if idx == 0:
        invc = 0
    elif idx == N - 1:
        invc = 1 << 255
    else:
        c = 1 + mpmath.mpf(idx + mpmath.mpf("0.5")) / N
        invc = fix(1 / c, 256)
    invcs.append(invc)
    print(f"\t{{{limbs(invc, 4)}}},")
print("}")
print()
print("// log256LogC[idx] is log(c) in fixed point with 320 fractional bits,")
print("// where c = 2**256/log256InvC[idx] is the breakpoint actually used")
print("// (not the ideal one, so that the rounding error of 1/c does not matter).")
print("var log256LogC = [256][5]uint64{")
for idx in range(N):
    if idx == 0:
        v = 0
    else:
        v = fix(-mpmath.log(mpmath.mpf(invcs[idx]) / mpmath.mpf(2) ** 256), 320)
    print(f"\t{{{limbs(v, 5)}}},")
print("}")
print()
print("// log256Coeffs are the coefficients of log(1+r)/r = sum w**i/(i+1) where w = -r,")
print("// in fixed point with 255 fractional bits,")
print(f"// in the order of Horner's method: 1/(i+1) for i = {TERMS - 1}, {TERMS - 2}, ..., 0.")
print("var log256Coeffs = [...][4]uint64{")
for i in range(TERMS - 1, -1, -1):
    print(f"\t{{{limbs(fix(mpmath.mpf(1) / (i + 1), 255), 4)}}}, // 1/{i + 1}")
print("}")
