#!/usr/bin/env python3
# Generates erfcinv32_table.go, the coefficients of the piecewise polynomials of erfcinv(t) for 2**-149 <= t < 2**-24
# used by Float32 Erfcinv. The other ranges use the tables of Float32 Erfinv.
#
# Usage: python3 scripts/gen_erfcinv32_table.py > erfcinv32_table.go

import importlib.util
import os
from multiprocessing import Pool

import mpmath

spec = importlib.util.spec_from_file_location("erfinv16", os.path.join(os.path.dirname(__file__), "gen_erfinv16_table.py"))
erfinv16 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(erfinv16)
erf16 = erfinv16.erf16

PREC = 700
DEGREE = 7
MIN_T_EXP = -149
MAX_T_EXP = -25


def erfcinv(t):
    return mpmath.erfinv(1 - t)


def fit(f, c, h, degree):
    """returns the coefficients of the polynomial in z = (t - c)/h for f, which interpolates at the Chebyshev nodes.
    z is in [-1, 1], so that the coefficients do not overflow even if t is tiny."""
    n = degree + 1
    nodes = [mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, u in enumerate(nodes):
        for j in range(n):
            a[i, j] = u**j
        b[i] = f(c + h * u)
    return [float(v) for v in mpmath.lu_solve(a, b)]


def max_error(f, c, h, coeffs):
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        u = mpmath.mpf(k) / 33
        p = sum(mpmath.mpf(coeffs[j]) * u**j for j in range(len(coeffs)))
        g = f(c + h * u)
        worst = max(worst, abs(p - g) / abs(g))
    return worst


def row(s):
    mpmath.mp.prec = PREC
    c, h = erf16.seg_range(s)
    coeffs = fit(erfcinv, c, h, DEGREE)
    return coeffs, max_error(erfcinv, c, h, coeffs)


if __name__ == "__main__":
    first = erf16.seg_of(2.0 ** MIN_T_EXP)
    last = erf16.seg_of(2.0 ** MAX_T_EXP) + 7
    with Pool() as p:
        results = p.map(row, range(first, last + 1), chunksize=4)
    worst = max(r[1] for r in results)

    print("// Code generated by scripts/gen_erfcinv32_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// erfcinv32Coeffs[s-{first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 z + ... + c{DEGREE} z**{DEGREE},")
    print("// which approximates erfcinv(t) for t in the segment s, where z = 16 (t - the center of the segment)/2**e is in [-1, 1],")
    print("// and 2**e <= t < 2**(e+1).")
    print("// The segment of t is the exponent and the upper three bits of the fraction of the float64 representation of t,")
    print(f"// {first}, ..., {last} (2**-149 <= t < 2**-24).")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var erfcinv32Coeffs = [...][{DEGREE + 1}]float64{{")
    for coeffs, _ in results:
        print("\t{" + ", ".join(v.hex() for v in coeffs) + "},")
    print("}")
