#!/usr/bin/env python3
# Generates gamma32_table.go, the coefficients of the piecewise polynomials of Gamma(x) used by Float32 Gamma.
#
# Usage: python3 scripts/gen_gamma32_table.py > gamma32_table.go

import mpmath
from multiprocessing import Pool

mpmath.mp.prec = 300

# Gamma(x) is approximated for x in [FIRST/PER_UNIT, (LAST+1)/PER_UNIT) by the polynomials of degree DEGREE
# in t = x - (s + 1/2)/PER_UNIT, for each segment s = x*PER_UNIT in [FIRST, LAST].
PER_UNIT = 4
FIRST = 1 * PER_UNIT
LAST = 44 * PER_UNIT - 1
DEGREE = 8


def fit(s):
    """returns the coefficients of the polynomial in t for the segment s, which interpolates at the Chebyshev nodes."""
    h = mpmath.mpf(1) / PER_UNIT
    c = (mpmath.mpf(s) + mpmath.mpf(1) / 2) * h
    n = DEGREE + 1
    nodes = [h / 2 * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = mpmath.gamma(c + t)
    coeffs = mpmath.lu_solve(a, b)
    coeffs = [float(coeffs[j]) for j in range(n)]
    # the maximum relative error in the segment
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        t = h / 2 * mpmath.mpf(k) / 32
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(n))
        g = mpmath.gamma(c + t)
        worst = max(worst, abs(p - g) / g)
    return coeffs, worst


if __name__ == "__main__":
    with Pool() as p:
        res = p.map(fit, range(FIRST, LAST + 1))
    worst = max(w for _, w in res)
    print("// Code generated by scripts/gen_gamma32_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// gamma32Coeffs[s-{FIRST}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
    print(f"// which approximates Gamma(x) for x in [s/{PER_UNIT}, (s+1)/{PER_UNIT}), where t = x - (s + 1/2)/{PER_UNIT} and s = {FIRST}, ..., {LAST}.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var gamma32Coeffs = [...][{DEGREE + 1}]float64{{")
    for coeffs, _ in res:
        print("\t{" + ", ".join(v.hex() for v in coeffs) + "},")
    print("}")
