#!/usr/bin/env python3
# Generates erfinv32_table.go, the coefficients of the piecewise polynomials of erfinv(1-t) in t for 1/2 <= x < 1
# used by Float32 Erfinv, where t = 1 - x >= 2**-24. The other ranges use the tables of Float16 Erfinv.
#
# Usage: python3 scripts/gen_erfinv32_table.py > erfinv32_table.go

import importlib.util
import os

import mpmath

mpmath.mp.prec = 300

spec = importlib.util.spec_from_file_location("erfinv16", os.path.join(os.path.dirname(__file__), "gen_erfinv16_table.py"))
erfinv16 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(erfinv16)
erf16 = erfinv16.erf16

DEGREE = 7
# 1 - x for the largest Float32 value less than 1 is 2**-24.
MIN_T_EXP = -24

if __name__ == "__main__":
    first = erf16.seg_of(2.0 ** MIN_T_EXP)
    last = erf16.seg_of(0.5)
    rows = []
    worst = mpmath.mpf(0)
    for s in range(first, last + 1):
        c, h = erf16.seg_range(s)
        f = lambda t: mpmath.erfinv(1 - t)
        coeffs = erf16.fit(f, c, h, DEGREE)
        worst = max(worst, erf16.max_error(f, c, h, coeffs))
        rows.append(coeffs)

    print("// Code generated by scripts/gen_erfinv32_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// erfinv32HiCoeffs[s-{first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 s + ... + c{DEGREE} s**{DEGREE},")
    print("// which approximates erfinv(1-t) for t in the segment s, where s = t - the center of the segment.")
    print("// The segment of t is the exponent and the upper three bits of the fraction of the float64 representation of t,")
    print(f"// {first}, ..., {last} (1/2 <= x < 1).")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var erfinv32HiCoeffs = [...][{DEGREE + 1}]float64{{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
