#!/usr/bin/env python3
# Generates cbrt16_table.go, the correctly rounded significands used by Float16 Cbrt.
#
# Usage: python3 scripts/gen_cbrt16_table.py > cbrt16_table.go

import mpmath

mpmath.mp.prec = 256

print("// Code generated by scripts/gen_cbrt16_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// cbrt16Table[r<<10|f] is the significand of cbrt(2**r × (1 + f/1024)) for r = 0, 1, 2 and f = 0, ..., 1023,")
print("// rounded to nearest, minus 1024. cbrt(2**r × (1 + f/1024)) is in [1, 2), so the value is in [0, 1024].")
print("// 1024 means that the result is rounded up to 2.")
print("var cbrt16Table = [3 << 10]uint16{")
for r in range(3):
    for row in range(64):
        vals = []
        for f in range(row * 16, row * 16 + 16):
            x = mpmath.mpf(2) ** r * (1 + mpmath.mpf(f) / 1024)
            # the cube of a half-integer is never 2**r × (1024 + f) × 2**20 / 8 × 8, so there is no tie.
            k = int(mpmath.nint(mpmath.cbrt(x) * 1024))
            assert 1024 <= k <= 2048
            vals.append(f"{k - 1024}")
        print("\t" + ", ".join(vals) + ",")
print("}")
