#!/usr/bin/env python3
# Generates y032_table.go, the coefficients of the polynomials used by Float32 Y0:
# the polynomials of Y0(x) for the segments [2, 64) in t = x - center of the segment.
# The segments are narrower near 2 because the convergence of the polynomials is limited by the singularity at 0:
# [2, 4) is divided into the segments of the width 1/4, [4, 6) of 1/2, and [6, 64) of 1.
#
# Usage: python3 scripts/gen_y032_table.py > y032_table.go

import mpmath

mpmath.mp.prec = 200

DEGREE = 11
SEGMENTS = (
    [(mpmath.mpf(8 + i) / 4, mpmath.mpf(9 + i) / 4) for i in range(8)]
    + [(mpmath.mpf(8 + i) / 2, mpmath.mpf(9 + i) / 2) for i in range(4)]
    + [(mpmath.mpf(i), mpmath.mpf(i + 1)) for i in range(6, 64)]
)


def f(x):
    return mpmath.bessely(0, x)


def fit(c, h, degree):
    """returns the coefficients of the polynomial in t = x - c for f, which interpolates at the Chebyshev nodes."""
    n = degree + 1
    nodes = [h * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = f(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def max_error(c, h, coeffs):
    worst = mpmath.mpf(0)
    for k in range(-40, 41):
        t = h * mpmath.mpf(k) / 41
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(len(coeffs)))
        worst = max(worst, abs(p - f(c + t)))
    return worst


centers = []
rows = []
worst = mpmath.mpf(0)
for lo, hi in SEGMENTS:
    c, h = (lo + hi) / 2, (hi - lo) / 2
    coeffs = fit(c, h, DEGREE)
    worst = max(worst, max_error(c, h, coeffs))
    centers.append(float(c))
    rows.append(coeffs)

print("// Code generated by scripts/gen_y032_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// y032Centers are the centers of the segments of the polynomials: the width is 1/4 for [2, 4), 1/2 for [4, 6),")
print("// and 1 for [6, 64).")
print("var y032Centers = [...]float64{")
for c in centers:
    print(f"\t{c.hex()},")
print("}")
print()
print(f"// y032Coeffs[i] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
print("// which approximates Y0(x) for the i-th segment, where t = x - y032Centers[i].")
print(f"// The absolute error is less than 2**-{int(-mpmath.log(worst, 2))}.")
print(f"var y032Coeffs = [...][{DEGREE + 1}]float64{{")
for row in rows:
    print("\t{" + ", ".join(v.hex() for v in row) + "},")
print("}")
