#!/usr/bin/env python3
# Generates atan256_table.go, the table-driven reduction constants used by Float256 Atan2.
#
# Usage: python3 scripts/gen_atan2_256_table.py > atan256_table.go

import mpmath

mpmath.mp.prec = 1200

N = 256
P = 236
EB = 19
BIAS = (1 << (EB - 1)) - 1
# the number of the coefficients of (atan(u) - u)/u**3 for |u| <= 1/(2*N)
TERMS = 14


def round_bits(y):
    # the bits of the Float256 nearest to y, as an integer.
    s = 1 if y < 0 else 0
    y = abs(y)
    if y == 0:
        return s << (P + EB)
    e = int(mpmath.floor(mpmath.log(y, 2)))
    m = int(mpmath.nint(y * mpmath.mpf(2) ** (P - e)))
    if m >> (P + 1):
        m >>= 1
        e += 1
    return (s << (P + EB)) | ((e + BIAS) << P) | (m - (1 << P))


def decode(v):
    s = v >> (P + EB)
    e = ((v >> P) & ((1 << EB) - 1)) - BIAS - P
    m = (v & ((1 << P) - 1)) | (1 << P)
    x = mpmath.mpf(m) * mpmath.mpf(2) ** e
    return -x if s else x


def to_float256_pair(x):
    # a double-Float256 (hi, lo) representation of x, accurate to ~470 bits.
    if x == 0:
        return 0, 0
    hi = round_bits(x)
    residual = x - decode(hi)
    lo = round_bits(residual) if residual != 0 else 0
    return hi, lo


def fmt(v):
    return "{" + ", ".join(f"0x{(v >> (64 * (3 - i))) & (2**64 - 1):016x}" for i in range(4)) + "}"


print("// Code generated by scripts/gen_atan2_256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print(f"// atan2Table256Hi[i] + atan2Table256Lo[i] is a double-Float256 representation of")
print(f"// atan(i/{N}) for i = 0, ..., {N}.")
pairs = [to_float256_pair(mpmath.atan(mpmath.mpf(i) / N)) for i in range(N + 1)]
print(f"var atan2Table256Hi = [{N + 1}]Float256{{")
for hi, _ in pairs:
    print(f"\t{fmt(hi)},")
print("}")
print()
print(f"var atan2Table256Lo = [{N + 1}]Float256{{")
for _, lo in pairs:
    print(f"\t{fmt(lo)},")
print("}")
print()
print(f"// atan2Coeffs256[k] is (-1)**(k+1)/(2k+3) for k = 0, ..., {TERMS - 1}, the coefficients of")
print("// (atan(u) - u)/u**3 = -1/3 + z/5 - z**2/7 + ... in terms of z = u**2.")
print(f"var atan2Coeffs256 = [{TERMS}]Float256{{")
for k in range(TERMS):
    v = mpmath.mpf((-1) ** (k + 1)) / (2 * k + 3)
    print(f"\t{fmt(round_bits(v))}, // {'-' if k % 2 == 0 else ''}1/{2 * k + 3}")
print("}")
print()
hi, lo = to_float256_pair(mpmath.pi / 2)
print("// atan2Pi2Hi256 + atan2Pi2Lo256 is a double-Float256 representation of pi/2.")
print(f"var atan2Pi2Hi256 = Float256{fmt(hi)}")
print(f"var atan2Pi2Lo256 = Float256{fmt(lo)}")
