#!/usr/bin/env python3
# Generates lgamma16_table.go, the coefficients of the polynomials used by Float16 Lgamma:
# the piecewise polynomials of Lgamma(x)/((x-1)(x-2)), and the piecewise polynomials of Lgamma(1+x).
#
# Usage: python3 scripts/gen_lgamma16_table.py > lgamma16_table.go

import struct

import mpmath

mpmath.mp.prec = 300

DEGREE = 7
SMALL_DEGREE = 6
# Lgamma is approximated for x in [2**-1, FIRST_INF) where FIRST_INF is the smallest Float16 whose Lgamma is +Inf.
LAST = 8184


def seg_of(x):
    """returns the segment of x, which is the exponent and the upper three bits of the fraction of the float64 representation."""
    return struct.unpack(">Q", struct.pack(">d", x))[0] >> 49


def seg_range(s):
    """returns the center and the half width of the segment s."""
    e = (s >> 3) - 1023 + 0  # the exponent of the segment: the float64 exponent field is s >> 3
    lo = (1 + mpmath.mpf(s & 7) / 8) * mpmath.mpf(2) ** e
    h = mpmath.mpf(2) ** e / 16
    return lo + h, h


def fit(f, c, h, degree):
    """returns the coefficients of the polynomial in t = x - c for f, which interpolates at the Chebyshev nodes."""
    n = degree + 1
    nodes = [h * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = f(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def max_error(f, c, h, coeffs, relative):
    worst = mpmath.mpf(0)
    for k in range(-32, 33):
        t = h * mpmath.mpf(k) / 33
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(len(coeffs)))
        g = f(c + t)
        err = abs(p - g)
        if relative:
            err /= abs(g)
        worst = max(worst, err)
    return worst


def f_poly(x):
    """lgamma(x)/((x-1)(x-2))."""
    return mpmath.loggamma(x) / ((x - 1) * (x - 2))


def f_small(x):
    return mpmath.loggamma(1 + x)


if __name__ == "__main__":
    first = seg_of(0.5)
    last = seg_of(LAST)
    rows = []
    worst = mpmath.mpf(0)
    for s in range(first, last + 1):
        c, h = seg_range(s)
        coeffs = fit(f_poly, c, h, DEGREE)
        worst = max(worst, max_error(f_poly, c, h, coeffs, True))
        rows.append(coeffs)
    small_rows = []
    small_worst = mpmath.mpf(0)
    for s in range(4):
        c, h = mpmath.mpf(2 * s + 1) / 16, mpmath.mpf(1) / 16
        coeffs = fit(f_small, c, h, SMALL_DEGREE)
        small_worst = max(small_worst, max_error(f_small, c, h, coeffs, False))
        small_rows.append(coeffs)

    print("// Code generated by scripts/gen_lgamma16_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print(f"// lgamma16Coeffs[s-{first}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
    print("// which approximates Lgamma(x)/((x-1)(x-2)) for x in the segment s, where t = x - the center of the segment.")
    print("// The segment s of x is the exponent and the upper three bits of the fraction of the float64 representation of x,")
    print(f"// s = {first}, ..., {last}. That is, x in [2**-1, {LAST + 8}).")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(worst, 2))}.")
    print(f"var lgamma16Coeffs = [...][{DEGREE + 1}]float64{{")
    for row in rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
    print()
    print(f"// lgamma16SmallCoeffs[s] are the coefficients c0, c1, ..., c{SMALL_DEGREE} of the polynomial c0 + c1 t + ... + c{SMALL_DEGREE} t**{SMALL_DEGREE},")
    print("// which approximates Lgamma(1+x) for x in [s/8, (s+1)/8), where t = x - (2s+1)/16 and s = 0, ..., 3.")
    print(f"// The absolute error is less than 2**-{int(-mpmath.log(small_worst, 2))}.")
    print(f"var lgamma16SmallCoeffs = [...][{SMALL_DEGREE + 1}]float64{{")
    for row in small_rows:
        print("\t{" + ", ".join(v.hex() for v in row) + "},")
    print("}")
    # Lgamma(1+x) = -gamma x + zeta(2)/2 x**2 - zeta(3)/3 x**3 + zeta(4)/4 x**4 - ... for |x| < 1.
    print()
    print("// lgamma16TinyCoeffs[k] is the coefficient of x**(k+1) of the Taylor series of Lgamma(1+x), which approximates it")
    print("// for 0 <= x < 2**-8 with the absolute error less than 2**-42.")
    print("var lgamma16TinyCoeffs = [...]float64{")
    print("\t" + ", ".join(float(c).hex() for c in [-mpmath.euler, mpmath.zeta(2) / 2, -mpmath.zeta(3) / 3, mpmath.zeta(4) / 4]) + ",")
    print("}")
