#!/usr/bin/env python3
# Generates asinh128_table.go, the fixed-point constants used by Float128 Asinh.
#
# Usage: python3 scripts/gen_asinh_table.py > asinh128_table.go

import mpmath

mpmath.mp.prec = 400

N = 256


def fix(x, frac_bits):
    return int(mpmath.nint(x * mpmath.mpf(2) ** frac_bits))


def limbs(v, n):
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_asinh_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// asinhLn2Fix128 is ln(2) in fixed point with 192 fractional bits.")
print(f"var asinhLn2Fix128 = [3]uint64{{{limbs(fix(mpmath.log(2), 192), 3)}}}")
print()
print("// asinhLogC128[idx] is log(c) in fixed point with 192 fractional bits,")
print("// where c = 1 + (idx+0.5)/256 is the breakpoint of the bucket idx used by logInvC128.")
print("// The entry for idx = 0 is unused.")
print("var asinhLogC128 = [256][3]uint64{")
for idx in range(N):
    if idx == 0:
        print("\t{},")
        continue
    c = 1 + mpmath.mpf(idx + mpmath.mpf("0.5")) / N
    print(f"\t{{{limbs(fix(mpmath.log(c), 192), 3)}}},")
print("}")
