#!/usr/bin/env python3
# Generates expm1_128_table.go, the fixed-point constants used by Float128 Exp, Exp2, Expm1, Sinh, Cosh, and Tanh.
#
# Usage: python3 scripts/gen_expm1_128_table.py > expm1_128_table.go

import mpmath

mpmath.mp.prec = 512


def fix(x, frac_bits):
    return int(mpmath.nint(x * mpmath.mpf(2) ** frac_bits))


def limbs(v, n):
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_expm1_128_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// expm1Ln2By64Fix128 is ln(2)/64 * 2**198 mod 2**192.")
print(f"var expm1Ln2By64Fix128 = [3]uint64{{{limbs(fix(mpmath.log(2) / 64, 198) % 2**192, 3)}}}")
print()
print("// expm1Ln2Fix128 is ln(2) * 2**128.")
print(f"var expm1Ln2Fix128 = [2]uint64{{{limbs(fix(mpmath.log(2), 128), 2)}}}")
print()
print("// expm1Table128[j] is 2**(j/64) in fixed point with 191 fractional bits.")
print("var expm1Table128 = [64][3]uint64{")
for j in range(64):
    print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (mpmath.mpf(j) / 64), 191), 3)}}},")
print("}")
print()
print("// expm1Coeffs128 are the coefficients of (e**r - 1)/r = sum r**i/(i+1)!,")
print("// in fixed point with 127 fractional bits,")
print("// in the order of Horner's method: 1/(i+1)! for i = 11, 10, ..., 0.")
print("var expm1Coeffs128 = [...][2]uint64{")
for i in range(11, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(i + 1), 127), 2)}}}, // 1/{i + 1}!")
print("}")
print()
print("// sinhCoeffs128 are the coefficients of sinh(r)/r = sum z**i/(2i+1)!, where z = r**2,")
print("// in fixed point with 127 fractional bits,")
print("// in the order of Horner's method: 1/(2i+1)! for i = 6, 5, ..., 0.")
print("var sinhCoeffs128 = [...][2]uint64{")
for i in range(6, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(2 * i + 1), 127), 2)}}}, // 1/{2 * i + 1}!")
print("}")
print()
print("// coshCoeffs128 are the coefficients of (cosh(r) - 1)/r**2 = sum z**i/(2i+2)!, where z = r**2,")
print("// in fixed point with 127 fractional bits,")
print("// in the order of Horner's method: 1/(2i+2)! for i = 5, 4, ..., 0.")
print("var coshCoeffs128 = [...][2]uint64{")
for i in range(5, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(2 * i + 2), 127), 2)}}}, // 1/{2 * i + 2}!")
print("}")
print()
print("// tanhCoeffs128 are the absolute values of the coefficients of")
print("// tanh(r)/r = 1 - z/3 + 2z**2/15 - ..., where z = r**2,")
print("// in fixed point with 127 fractional bits, in the order of Horner's method: i = 8, 7, ..., 0.")
print("// The sign of the coefficient of z**i is (-1)**i.")
print("var tanhCoeffs128 = [...][2]uint64{")
t = mpmath.taylor(mpmath.tanh, 0, 17)
for i in range(8, -1, -1):
    print(f"\t{{{limbs(fix(abs(t[2 * i + 1]), 127), 2)}}}, // z**{i}")
print("}")
