#!/usr/bin/env python3
# Generates gamma128_table.go, the constants used by Float128 Gamma.
# The numbers are in fixed point with 192 fractional bits in four 64-bit words, the first of which is the integer part,
# unless otherwise noted.
#
# Usage: python3 scripts/gen_gamma128_table.py > gamma128_table.go

import mpmath

mpmath.mp.prec = 700

F = 192
# the number of the coefficients of the Stirling series: |B(2k)| / (2k (2k-1)) / z**(2k-1), k = 1, ..., STIRLING_TERMS
STIRLING_TERMS = 22
# the number of the coefficients of e**r = sum r**m / m!, for |r| <= ln(2)/512
EXP_TERMS = 14
# the degree of the polynomial of sinc(r) = sin(pi r)/(pi r) in t = r**2, for |r| <= 1/2
SINC_DEGREE = 17
# the number of the coefficients of Gamma(1+x) = sum g_k x**k
GAMMA1_TERMS = 6


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=4):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def fit_sinc(d):
    """returns the coefficients of the polynomial in t = r**2 of sin(pi r)/(pi r) for |r| <= 1/2,
    which interpolates at the Chebyshev nodes."""
    n = d + 1
    nodes = [mpmath.mpf(1) / 8 * (1 + mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n))) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        r = mpmath.sqrt(t)
        for j in range(n):
            a[i, j] = t**j
        b[i] = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
    return [mpmath.mpf(c) for c in mpmath.lu_solve(a, b)]


def sinc_error(coeffs):
    worst = mpmath.mpf(0)
    for k in range(1, 300):
        r = mpmath.mpf(k) / 600
        t = r * r
        p = sum(c * t**j for j, c in enumerate(coeffs))
        g = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
        worst = max(worst, abs(p - g) / g)
    return worst


def main():
    print("// Code generated by scripts/gen_gamma128_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print("// gamma128Stirling[k-1] is |B(2k)| / (2k (2k-1)), the coefficient of the Stirling series of log(Gamma(z)),")
    print("// where the sign of B(2k) is (-1)**(k+1).")
    print("var gamma128Stirling = [...][4]uint64{")
    for k in range(1, STIRLING_TERMS + 1):
        v = fix(abs(mpmath.bernoulli(2 * k)) / (2 * k * (2 * k - 1)))
        print(f"\t{{{limbs(v)}}}, // k = {k}")
    print("}")
    print()

    print("// gamma128HalfLn2Pi is log(2 pi)/2.")
    print(f"var gamma128HalfLn2Pi = [4]uint64{{{limbs(fix(mpmath.log(2 * mpmath.pi) / 2))}}}")
    print()

    print("// gamma128Ln2By256 is log(2)/256 in fixed point with 256 fractional bits.")
    print(f"var gamma128Ln2By256 = [4]uint64{{{limbs(fix(mpmath.log(2) / 256, 256))}}}")
    print()

    print("// gamma128InvLn2By256 is 256/log(2).")
    print(f"var gamma128InvLn2By256 = [4]uint64{{{limbs(fix(256 / mpmath.log(2)))}}}")
    print()

    print("// gamma128Exp2[j] is 2**(j/256).")
    print("var gamma128Exp2 = [256][4]uint64{")
    for j in range(256):
        print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (mpmath.mpf(j) / 256)))}}},")
    print("}")
    print()

    print("// gamma128ExpCoeffs[m] is 1/m!.")
    print("var gamma128ExpCoeffs = [...][4]uint64{")
    for m in range(EXP_TERMS):
        print(f"\t{{{limbs(fix(1 / mpmath.factorial(m)))}}}, // 1/{m}!")
    print("}")
    print()

    print("// gamma128Gamma1[k] is |g_k|, the coefficient of Gamma(1+x) = sum g_k x**k. The sign of g_k is (-1)**k.")
    print("var gamma128Gamma1 = [...][4]uint64{")
    taylor = mpmath.taylor(mpmath.gamma, 1, GAMMA1_TERMS - 1)
    for k, c in enumerate(taylor):
        assert (c < 0) == (k % 2 == 1)
        print(f"\t{{{limbs(fix(abs(c)))}}}, // k = {k}")
    print("}")
    print()

    coeffs = fit_sinc(SINC_DEGREE)
    err = sinc_error(coeffs)
    print("// gamma128Sinc[j] is |a_j|, the coefficient of sin(pi r)/(pi r) = sum a_j t**j, where t = r**2 and |r| <= 1/2.")
    print("// The sign of a_j is (-1)**j.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(err, 2))}.")
    print("var gamma128Sinc = [...][4]uint64{")
    for j, c in enumerate(coeffs):
        assert (c < 0) == (j % 2 == 1), j
        print(f"\t{{{limbs(fix(abs(c)))}}}, // j = {j}")
    print("}")


main()
