#!/usr/bin/env python3
# Generates erf256_table.go, the constants used by Float256 Erf and Erfc.
# The numbers are in fixed point with 320 fractional bits in six 64-bit words, the first of which is the integer part,
# unless otherwise noted.
#
# Usage: python3 scripts/gen_erf256_table.py > erf256_table.go

import mpmath

mpmath.mp.prec = 1500

F = 320
# erf(x) for x in [k/16, (k+1)/16) is calculated by the Taylor series around the center x0 = (k + 1/2)/16:
# erf(x0+h) = erf(x0) + 2/sqrt(pi) exp(-x0**2) sum_n b_n h**(n+1)/(n+1), where exp(-2 x0 h - h**2) = sum b_n h**n.
CELLS = 256  # erfc(x) is calculated by the cells for x < 16
TAIL_BITS = 330  # the tail of the series is less than 2**-TAIL_BITS
SMALL_TERMS = 22  # the number of the terms of the series for |x| < 2**-8
# For the cells k >= LARGE_CELL, erf(x) is rounded from 1 - erfc(x).
LARGE_CELL = 112
# For the cells k >= SCALED_CELL, erfc(x) is calculated in a relative accuracy.
SCALED_CELL = 64
MAX_TERMS = 79  # the maximum number of the terms of the Taylor series


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def e0_of(k):
    x0 = mpmath.mpf(2 * k + 1) / 32
    return 2 / mpmath.sqrt(mpmath.pi) * mpmath.exp(-x0 * x0)


def terms(k, scaled):
    """returns the number of the terms of the Taylor series for the cell k.
    If scaled is true, the series is for erfc(x) in a relative accuracy."""
    x0 = mpmath.mpf(2 * k + 1) / 32
    h = mpmath.mpf(1) / 32
    e0 = e0_of(k)
    if scaled:
        # erfc(x) is calculated in a relative accuracy
        e0 = e0 / mpmath.erfc(x0)
    b = [mpmath.mpf(1), -2 * x0]
    n = 1
    while True:
        while len(b) <= n + 1:
            m = len(b) - 1
            b.append(-(2 * x0 * b[m] + 2 * b[m - 1]) / (m + 1))
        if e0 * abs(b[n]) * h ** (n + 1) / (n + 1) < mpmath.mpf(2) ** -TAIL_BITS and e0 * abs(b[n + 1]) * h ** (n + 2) / (n + 2) < mpmath.mpf(2) ** -TAIL_BITS:
            return n
        n += 1


def check_terms():
    assert max(terms(k, False) for k in range(LARGE_CELL)) <= MAX_TERMS
    assert max(terms(k, True) for k in range(SCALED_CELL, CELLS)) <= MAX_TERMS


def mant_exp(x):
    e = int(mpmath.floor(mpmath.log(x, 2)))
    return x / mpmath.mpf(2) ** e, e


def main():
    check_terms()
    print("// Code generated by scripts/gen_erf256_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print("// erf256TwoOverSqrtPi is 2/sqrt(pi).")
    print(f"var erf256TwoOverSqrtPi = [6]uint64{{{limbs(fix(2 / mpmath.sqrt(mpmath.pi)))}}}")
    print()

    print("// erf256Small[n] is 1/(n! (2n+1)), the coefficient of erf(x) = 2/sqrt(pi) x sum (-x**2)**n/(n! (2n+1)).")
    print("var erf256Small = [...][6]uint64{")
    for n in range(SMALL_TERMS):
        print(f"\t{{{limbs(fix(1 / (mpmath.factorial(n) * (2 * n + 1))))}}}, // n = {n}")
    print("}")
    print()

    print(f"// erf256Erf[k] is erf(x0) for the cells k < {LARGE_CELL}, where x0 = (k + 1/2)/16.")
    print("var erf256Erf = [...][6]uint64{")
    for k in range(LARGE_CELL):
        print(f"\t{{{limbs(fix(mpmath.erf(mpmath.mpf(2 * k + 1) / 32)))}}},")
    print("}")
    print()
    print("// erf256E0[k] is the mantissa m of 2/sqrt(pi) exp(-x0**2) = m × 2**erf256E0Exp[k], where m is in [1, 2),")
    print(f"// for the cells k < {LARGE_CELL}.")
    print("var erf256E0 = [...][6]uint64{")
    exps = []
    for k in range(LARGE_CELL):
        m, e = mant_exp(e0_of(k))
        exps.append(e)
        print(f"\t{{{limbs(fix(m))}}},")
    print("}")
    print()
    print("// erf256E0Exp[k] is the exponent of 2/sqrt(pi) exp(-x0**2).")
    print("var erf256E0Exp = [...]int16{")
    print("\t" + ", ".join(str(e) for e in exps) + ",")
    print("}")
    print()

    mants = []
    for k in range(SCALED_CELL, CELLS):
        mants.append(mant_exp(mpmath.erfc(mpmath.mpf(2 * k + 1) / 32)))
    print(f"// erf256ErfcMant[k-{SCALED_CELL}] is the mantissa m of erfc(x0) = m × 2**erf256ErfcExp[k-{SCALED_CELL}] for the cells k >= {SCALED_CELL},")
    print("// where x0 = (k + 1/2)/16 and m is in [1, 2).")
    print("var erf256ErfcMant = [...][6]uint64{")
    for m, _ in mants:
        print(f"\t{{{limbs(fix(m))}}},")
    print("}")
    print()
    print(f"// erf256ErfcExp[k-{SCALED_CELL}] is the exponent of erfc(x0) for the cells k >= {SCALED_CELL}.")
    print("var erf256ErfcExp = [...]int16{")
    print("\t" + ", ".join(str(e) for _, e in mants) + ",")
    print("}")
    print()
    print(f"// erf256R[k-{SCALED_CELL}] is 2/sqrt(pi) exp(-x0**2) / erfc(x0) for the cells k >= {SCALED_CELL}.")
    print("var erf256R = [...][6]uint64{")
    for k in range(SCALED_CELL, CELLS):
        x0 = mpmath.mpf(2 * k + 1) / 32
        print(f"\t{{{limbs(fix(e0_of(k) / mpmath.erfc(x0)))}}},")
    print("}")
    print()

    print("// erf256InvD[i] is 2**l/d, where d = 16 (i+1) (i+2) and l is the bit length of d-1, so that it is in [1, 2).")
    print("// It divides the numerator of the recurrence of the Taylor series.")
    print("var erf256InvD = [...][6]uint64{")
    for i in range(MAX_TERMS):
        d = 16 * (i + 1) * (i + 2)
        print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (d - 1).bit_length() / d))}}},")
    print("}")
    print()

    print("// erf256InvSqrtPi is 1/sqrt(pi).")
    print(f"var erf256InvSqrtPi = [6]uint64{{{limbs(fix(1 / mpmath.sqrt(mpmath.pi)))}}}")
    print()

    print(f"// erf256Terms[k] is the number of the terms of the Taylor series of the cell k < {LARGE_CELL} for erf(x).")
    print("var erf256Terms = [...]uint8{")
    print("\t" + ", ".join(str(terms(k, False)) for k in range(LARGE_CELL)) + ",")
    print("}")
    print()
    print(f"// erf256ErfcTerms[k-{SCALED_CELL}] is the number of the terms of the Taylor series of the cell k >= {SCALED_CELL} for erfc(x)")
    print("// in a relative accuracy.")
    print("var erf256ErfcTerms = [...]uint8{")
    print("\t" + ", ".join(str(terms(k, True)) for k in range(SCALED_CELL, CELLS)) + ",")
    print("}")


main()
