#!/usr/bin/env python3
# Generates expm1_256_table.go, the fixed-point constants used by Float256 Exp, Exp2, Expm1, Sinh, and Cosh.
#
# Usage: python3 scripts/gen_expm1_256_table.py > expm1_256_table.go

import mpmath

mpmath.mp.prec = 1024

# the number of the coefficients of (e**r - 1)/r for |r| <= ln(2)/128
TERMS = 23


def fix(x, frac_bits):
    return int(mpmath.nint(x * mpmath.mpf(2) ** frac_bits))


def limbs(v, n):
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_expm1_256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// expm1Ln2By64Fix256 is ln(2)/64 * 2**326 mod 2**320.")
print(f"var expm1Ln2By64Fix256 = [5]uint64{{{limbs(fix(mpmath.log(2) / 64, 326) % 2**320, 5)}}}")
print()
print("// expm1Ln2Fix256 is ln(2) * 2**256.")
print(f"var expm1Ln2Fix256 = [4]uint64{{{limbs(fix(mpmath.log(2), 256), 4)}}}")
print()
print("// expm1Table256[j] is 2**(j/64) in fixed point with 383 fractional bits.")
print("var expm1Table256 = [64][6]uint64{")
for j in range(64):
    print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (mpmath.mpf(j) / 64), 383), 6)}}},")
print("}")
print()
print("// expm1Coeffs256 are the coefficients of (e**r - 1)/r = sum r**i/(i+1)!,")
print("// in fixed point with 255 fractional bits,")
print(f"// in the order of Horner's method: 1/(i+1)! for i = {TERMS - 1}, {TERMS - 2}, ..., 0.")
print("var expm1Coeffs256 = [...][4]uint64{")
for i in range(TERMS - 1, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(i + 1), 255), 4)}}}, // 1/{i + 1}!")
print("}")

# the number of the coefficients of sinh(r)/r and (cosh(r) - 1)/r**2 in z = r**2 for |r| <= ln(2)/128
SINH_TERMS = 12

print()
print("// sinhCoeffs256 are the coefficients of sinh(r)/r = sum z**i/(2i+1)!, where z = r**2,")
print("// in fixed point with 255 fractional bits,")
print(f"// in the order of Horner's method: 1/(2i+1)! for i = {SINH_TERMS - 1}, {SINH_TERMS - 2}, ..., 0.")
print("var sinhCoeffs256 = [...][4]uint64{")
for i in range(SINH_TERMS - 1, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(2 * i + 1), 255), 4)}}}, // 1/{2 * i + 1}!")
print("}")
print()
print("// coshCoeffs256 are the coefficients of (cosh(r) - 1)/r**2 = sum z**i/(2i+2)!, where z = r**2,")
print("// in fixed point with 255 fractional bits,")
print(f"// in the order of Horner's method: 1/(2i+2)! for i = {SINH_TERMS - 1}, {SINH_TERMS - 2}, ..., 0.")
print("var coshCoeffs256 = [...][4]uint64{")
for i in range(SINH_TERMS - 1, -1, -1):
    print(f"\t{{{limbs(fix(1 / mpmath.factorial(2 * i + 2), 255), 4)}}}, // 1/{2 * i + 2}!")
print("}")
