#!/usr/bin/env python3
# Generates lgamma128_table.go, the constants used by Float128 Lgamma.
#
# Usage: python3 scripts/gen_lgamma128_table.py > lgamma128_table.go

import mpmath

mpmath.mp.prec = 700

F = 192


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=4):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def float256(x):
    """returns the bits of the Float256 value nearest to x > 0."""
    P, B = 236, 262143
    e = int(mpmath.floor(mpmath.log(x, 2)))
    m = int(mpmath.nint(x * mpmath.mpf(2) ** (P - e)))
    if m >> (P + 1):
        m >>= 1
        e += 1
    return ((e + B) << P) | (m - (1 << P))


def main():
    print("// Code generated by scripts/gen_lgamma128_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print("// lgamma128Taylor[k-1] is |c_k|, the coefficient of the Taylor series of Lgamma(1+x) = sum c_k x**k,")
    print("// in fixed point with 192 fractional bits. c_1 = -gamma, c_k = (-1)**k zeta(k)/k.")
    print("var lgamma128Taylor = [...][4]uint64{")
    cs = [mpmath.euler] + [mpmath.zeta(k) / k for k in range(2, 4)]
    for k, c in enumerate(cs, 1):
        print(f"\t{{{limbs(fix(c))}}}, // k = {k}")
    print("}")
    print()

    print("// lgamma128Ln1p5 is log(3/2) in fixed point with 192 fractional bits.")
    print(f"var lgamma128Ln1p5 = [4]uint64{{{limbs(fix(mpmath.log(mpmath.mpf(3) / 2)))}}}")
    print()

    consts = [
        ("lgamma128HalfLn2Pi256", "log(2 pi)/2", mpmath.log(2 * mpmath.pi) / 2),
        ("lgamma128LnPi256", "log(pi)", mpmath.log(mpmath.pi)),
        ("lgamma128Pi256", "pi", mpmath.pi),
    ]
    for name, desc, v in consts:
        print(f"// {name} is {desc} in Float256.")
        print(f"var {name} = Float256{{{limbs(float256(v))}}}")
        print()

    print("// lgamma128Stirling256[k-1] is |B(2k)| / (2k (2k-1)) in Float256, the coefficient of the Stirling series.")
    print("var lgamma128Stirling256 = [...]Float256{")
    for k in range(1, 5):
        v = abs(mpmath.bernoulli(2 * k)) / (2 * k * (2 * k - 1))
        print(f"\t{{{limbs(float256(v))}}}, // k = {k}")
    print("}")


main()
