#!/usr/bin/env python3
# Generates j1256_table.go, the constants used by Float256 J1.
# The zeros of J1 below ZERO_LIMIT, where J1 is calculated by the Taylor series around the nearest zero if |J1| is small.
#
# Usage: python3 scripts/gen_j1256_table.py > j1256_table.go

import mpmath

mpmath.mp.prec = 1000

F = 320
ZERO_LIMIT = 256


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


zeros = []
k = 1
while True:
    z = mpmath.besseljzero(1, k)
    if z >= ZERO_LIMIT:
        break
    zeros.append(z)
    k += 1

print("// Code generated by scripts/gen_j1256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// j1256Zeros[k-1] is the k-th positive zero of J1 in fixed point with 504 fractional bits in eight 64-bit words,")
print("// the first of which has the integer part in the highest 8 bits.")
print("var j1256Zeros = [...][8]uint64{")
for z in zeros:
    print(f"\t{{{limbs(fix(z, 504), 8)}}},")
print("}")
print()
print("// j1256ZeroJ0[k-1] is |J0(z)| for the k-th zero z of J1, in fixed point with 320 fractional bits.")
print("// The sign of J0(z) is (-1)**k, which is the sign of the derivative of J1 at z.")
print("var j1256ZeroJ0 = [...][6]uint64{")
for z in zeros:
    print(f"\t{{{limbs(fix(abs(mpmath.besselj(0, z))))}}},")
print("}")
