#!/usr/bin/env python3
# Generates atanh256_table.go, the series coefficients used by Float256 Atanh.
#
# Usage: python3 scripts/gen_atanh256_table.py > atanh256_table.go

import mpmath

mpmath.mp.prec = 1024

# the number of the coefficients of H(z) = sum z**(i-1)/(2i+1) for 0 < z < 2**-18
TERMS = 15


def fix(x, frac_bits):
    return int(mpmath.nint(x * mpmath.mpf(2) ** frac_bits))


def limbs(v, n):
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


print("// Code generated by scripts/gen_atanh256_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print("// atanhCoeffs256 are the coefficients of atanh(a) = a + a × z × H(z) where z = a**2 and")
print("// H(z) = sum z**(i-1)/(2i+1) = 1/3 + z/5 + z**2/7 + ...,")
print("// in fixed point with 257 fractional bits,")
print(f"// in the order of Horner's method: 1/(2i+1) for i = {TERMS}, {TERMS - 1}, ..., 1.")
print("var atanhCoeffs256 = [...][4]uint64{")
for i in range(TERMS, 0, -1):
    print(f"\t{{{limbs(fix(mpmath.mpf(1) / (2 * i + 1), 257), 4)}}}, // 1/{2 * i + 1}")
print("}")
