#!/usr/bin/env python3
# Generates y0256_table.go, the constants used by Float256 Y0.
# All the numbers are the bits of Float256 in four 64-bit words.
#
# Usage: python3 scripts/gen_y0256_table.py > y0256_table.go

import mpmath

mpmath.mp.prec = 1000

# the number of the coefficients of the power series in z = x**2/4, for 0 < x < 2
SERIES_TERMS = 36
# the number of the coefficients of the Hankel expansions in 1/x**2, for x >= 128
HANKEL_TERMS = 38
# the Taylor centers: (first center, last center, step)
TAYLOR = [(2.25, 7.75, 0.5), (8.5, 127.5, 1.0)]


def enc(v):
    """returns the Float256 bits of v rounded to nearest even."""
    v = mpmath.mpf(v)
    if v == 0:
        return 0
    with mpmath.workprec(237):
        r = +v
    sign, man, exp, bc = r._mpf_
    man = int(man)
    m = man << (237 - bc)
    e = exp + bc - 1
    assert -262142 <= e <= 262143
    return (sign << 255) | ((e + 262143) << 236) | (m - (1 << 236))


def lit(v):
    b = enc(v)
    return "{" + ", ".join(f"0x{(b >> (64 * (3 - i))) & (2**64 - 1):016x}" for i in range(4)) + "}"


def hankel_abs(k):
    """returns |a_k(0)| = (1*3*...*(2k-1))**2 / (k! 8**k)."""
    n = mpmath.mpf(1)
    for j in range(1, k + 1):
        n *= (2 * j - 1) ** 2
    return n / (mpmath.factorial(k) * 8**k)


def taylor_terms(x0, hmax):
    """returns the smallest N such that the terms c_n hmax**n of the Taylor series of Y0 at x0 are
    less than 2**-250 for all n > N."""
    c = [mpmath.bessely(0, x0), -mpmath.bessely(1, x0)]
    c.append(-(c[1] / x0 + c[0]) / 2)
    for n in range(1, 200):
        t = ((n + 1) ** 2 * c[n + 1] + c[n - 1]) / x0 + c[n]
        c.append(-t / ((n + 2) * (n + 1)))
    last = 0
    for n, v in enumerate(c):
        if abs(v) * hmax**n >= mpmath.mpf(2) ** -250:
            last = n
    assert last + 2 < len(c) - 20
    return last + 1


def main():
    print("// Code generated by scripts/gen_y0256_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print("// y0256TwoOverPi is 2/pi.")
    print(f"var y0256TwoOverPi = Float256{lit(2 / mpmath.pi)}")
    print()
    print("// y0256SeriesJ[k] is (-1)**k / (k!)**2, the coefficient of J0(x) = sum y0256SeriesJ[k] z**k, z = x**2/4.")
    print("var y0256SeriesJ = [...]Float256{")
    for k in range(SERIES_TERMS):
        print(f"\t{lit((-1) ** k / mpmath.factorial(k) ** 2)}, // k = {k}")
    print("}")
    print()
    print("// y0256SeriesS[k] is (-1)**(k+1) H(k) / (k!)**2, where H(k) is the k-th harmonic number, so that")
    print("// Y0(x) = 2/pi * ((ln(x/2) + EulerGamma) * J0(x) + sum y0256SeriesS[k] z**k), z = x**2/4.")
    print("var y0256SeriesS = [...]Float256{")
    for k in range(SERIES_TERMS):
        h = sum(mpmath.mpf(1) / j for j in range(1, k + 1))
        print(f"\t{lit((-1) ** (k + 1) * h / mpmath.factorial(k) ** 2)}, // k = {k}")
    print("}")
    print()
    print("// y0256HankelP[k] and y0256HankelQ[k] are the coefficients of the Hankel expansions")
    print("// P(x) = sum y0256HankelP[k] / x**(2k) and Q(x) = sum y0256HankelQ[k] / x**(2k+1).")
    print("var y0256HankelP = [...]Float256{")
    for k in range(HANKEL_TERMS):
        print(f"\t{lit((-1) ** k * hankel_abs(2 * k))}, // k = {k}")
    print("}")
    print()
    print("var y0256HankelQ = [...]Float256{")
    for k in range(HANKEL_TERMS):
        print(f"\t{lit((-1) ** (k + 1) * hankel_abs(2 * k + 1))}, // k = {k}")
    print("}")
    print()
    terms = []
    for first, last, step in TAYLOR:
        n = int(round((last - first) / step)) + 1
        for i in range(n):
            x0 = mpmath.mpf(first) + i * mpmath.mpf(step)
            terms.append((float(x0), taylor_terms(x0, mpmath.mpf(step) / 2)))
    print("// y0256MaxTaylorTerms is the maximum of y0256TaylorTerms.")
    print(f"const y0256MaxTaylorTerms = {max(t for _, t in terms)}")
    print()
    print("// y0256TaylorTerms[i] is the degree of the Taylor polynomial at the center of the i-th interval.")
    print("var y0256TaylorTerms = [...]uint8{")
    for x0, t in terms:
        print(f"\t{t}, // x0 = {x0}")
    print("}")
    print()
    print("// y0256Taylor[i] is {Y0(x0), Y0'(x0)} = {Y0(x0), -Y1(x0)} at the center x0 of the i-th interval.")
    print("var y0256Taylor = [...][2]Float256{")
    for first, last, step in TAYLOR:
        n = int(round((last - first) / step)) + 1
        for i in range(n):
            x0 = mpmath.mpf(first) + i * mpmath.mpf(step)
            print(f"\t{{{lit(mpmath.bessely(0, x0))}, {lit(-mpmath.bessely(1, x0))}}}, // x0 = {float(x0)}")
    print("}")


main()
