#!/usr/bin/env python3
# Generates gamma256_table.go, the constants used by Float256 Gamma.
# The numbers are in fixed point with 320 fractional bits in six 64-bit words, the first of which is the integer part,
# unless otherwise noted.
#
# Usage: python3 scripts/gen_gamma256_table.py > gamma256_table.go

import mpmath

mpmath.mp.prec = 1500

F = 320
# The Stirling series is calculated for z >= STIRLING_Z0, and the tail is less than 2**-STIRLING_BITS.
STIRLING_Z0 = 48
STIRLING_BITS = 290
# The Stirling series is scaled: |B(2k)| / (2k (2k-1)) / z**(2k-1) = b_k u**(k-1) / z, where u = (STIRLING_SCALE/z)**2.
STIRLING_SCALE = 8
# the number of the coefficients of e**r = sum r**m / m!, for 0 <= r < ln(2)/65536, and the tail is less than 2**-EXP_BITS.
EXP_BITS = 310
# the number of the coefficients of log(1+r) = r sum (-r)**k / (k+1), for |r| < 2**(2/65536) - 1, and the tail is less than 2**-LOG_BITS.
LOG_BITS = 310
# the degree of the polynomial of sinc(r) = sin(pi r)/(pi r) in t = r**2, for |r| <= 1/2
SINC_DEGREE = 29
# the number of the coefficients of Gamma(1+x) = sum g_k x**k, for |x| < 2**-GAMMA1_EXP.
GAMMA1_EXP = 40
GAMMA1_BITS = 312


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=6):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def fit_sinc(d):
    """returns the coefficients of the polynomial in t = r**2 of sin(pi r)/(pi r) for |r| <= 1/2,
    which interpolates at the Chebyshev nodes."""
    n = d + 1
    nodes = [mpmath.mpf(1) / 8 * (1 + mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n))) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        r = mpmath.sqrt(t)
        for j in range(n):
            a[i, j] = t**j
        b[i] = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
    return [mpmath.mpf(c) for c in mpmath.lu_solve(a, b)]


def sinc_error(coeffs):
    worst = mpmath.mpf(0)
    for k in range(1, 400):
        r = mpmath.mpf(k) / 800
        t = r * r
        p = sum(c * t**j for j, c in enumerate(coeffs))
        g = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
        worst = max(worst, abs(p - g) / g)
    return worst


def stirling_coeff(k):
    return abs(mpmath.bernoulli(2 * k)) / (2 * k * (2 * k - 1))


def stirling_terms_for(z0):
    """returns the number of the terms of the Stirling series for z >= z0."""
    n = 1
    while stirling_coeff(n + 1) / mpmath.mpf(z0) ** (2 * n + 1) >= mpmath.mpf(2) ** -STIRLING_BITS:
        n += 1
    return n


def main():
    stirling_terms = stirling_terms_for(STIRLING_Z0)
    exp_terms = 1
    rmax = mpmath.log(2) / 65536
    while rmax**exp_terms / mpmath.factorial(exp_terms) >= mpmath.mpf(2) ** -EXP_BITS:
        exp_terms += 1
    log_terms = 1
    rmax = mpmath.mpf(2) ** (mpmath.mpf(2) / 65536) - 1
    while rmax ** (log_terms + 1) / (log_terms + 1) >= mpmath.mpf(2) ** -LOG_BITS:
        log_terms += 1
    gamma1_terms = 1
    while mpmath.mpf(2) ** (-GAMMA1_EXP * gamma1_terms) >= mpmath.mpf(2) ** -GAMMA1_BITS:
        gamma1_terms += 1

    print("// Code generated by scripts/gen_gamma256_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print(f"// gamma256Stirling[k-1] is b_k = |B(2k)| / (2k (2k-1)) / {STIRLING_SCALE}**(2k-2), the coefficient of the Stirling series")
    print("// of log(Gamma(z)) scaled by u = (8/z)**2. The sign of B(2k) is (-1)**(k+1).")
    print(f"// The series is accurate to 2**-{STIRLING_BITS} for z >= {STIRLING_Z0}.")
    print(f"var gamma256Stirling = [{stirling_terms}][6]uint64{{")
    for k in range(1, stirling_terms + 1):
        x = stirling_coeff(k) / mpmath.mpf(STIRLING_SCALE) ** (2 * k - 2)
        assert x < 2**63
        print(f"\t{{{limbs(fix(x))}}}, // k = {k}")
    print("}")
    print()

    print("// gamma256StirlingTerms[k] is the number of the terms of the Stirling series for 2**(k+5) <= z < 2**(k+6),")
    print("// where z >= 48 for k = 0.")
    print("var gamma256StirlingTerms = [...]int{")
    for lg in range(5, 15):
        print(f"\t{stirling_terms_for(STIRLING_Z0 if lg == 5 else 2 ** lg)}, // z < 2**{lg + 1}")
    print("}")
    print()

    print("// gamma256HalfLn2Pi is log(2 pi)/2.")
    print(f"var gamma256HalfLn2Pi = [6]uint64{{{limbs(fix(mpmath.log(2 * mpmath.pi) / 2))}}}")
    print()

    print("// gamma256Ln2By256 is log(2)/256 in fixed point with 384 fractional bits in seven words.")
    print(f"var gamma256Ln2By256 = [7]uint64{{{limbs(fix(mpmath.log(2) / 256, 384), 7)}}}")
    print()

    print("// gamma256Ln2By65536 is log(2)/65536 in fixed point with 384 fractional bits in seven words.")
    print(f"var gamma256Ln2By65536 = [7]uint64{{{limbs(fix(mpmath.log(2) / 65536, 384), 7)}}}")
    print()

    print("// gamma256InvLn2By256 is 256/log(2).")
    print(f"var gamma256InvLn2By256 = [6]uint64{{{limbs(fix(256 / mpmath.log(2)))}}}")
    print()

    print("// gamma256InvLn2By65536 is 65536/log(2).")
    print(f"var gamma256InvLn2By65536 = [6]uint64{{{limbs(fix(65536 / mpmath.log(2)))}}}")
    print()

    print("// gamma256Exp2[j] is 2**(j/256).")
    print("var gamma256Exp2 = [257][6]uint64{")
    for j in range(257):
        print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (mpmath.mpf(j) / 256)))}}},")
    print("}")
    print()

    print("// gamma256Exp2Inv[i] is 2**(-i/65536).")
    print("var gamma256Exp2Inv = [257][6]uint64{")
    for i in range(257):
        print(f"\t{{{limbs(fix(mpmath.mpf(2) ** (-mpmath.mpf(i) / 65536)))}}},")
    print("}")
    print()

    print("// gamma256ExpCoeffs[m] is 1/m!.")
    print(f"var gamma256ExpCoeffs = [{exp_terms}][6]uint64{{")
    for m in range(exp_terms):
        print(f"\t{{{limbs(fix(1 / mpmath.factorial(m)))}}}, // 1/{m}!")
    print("}")
    print()

    print("// gamma256LogCoeffs[k] is 1/(k+1).")
    print(f"var gamma256LogCoeffs = [{log_terms}][6]uint64{{")
    for k in range(log_terms):
        print(f"\t{{{limbs(fix(mpmath.mpf(1) / (k + 1)))}}}, // 1/{k + 1}")
    print("}")
    print()

    print("// gamma256Gamma1[k] is |g_k|, the coefficient of Gamma(1+x) = sum g_k x**k. The sign of g_k is (-1)**k.")
    print(f"var gamma256Gamma1 = [{gamma1_terms}][6]uint64{{")
    taylor = mpmath.taylor(mpmath.gamma, 1, gamma1_terms - 1)
    for k, c in enumerate(taylor):
        assert (c < 0) == (k % 2 == 1)
        print(f"\t{{{limbs(fix(abs(c)))}}}, // k = {k}")
    print("}")
    print()

    coeffs = fit_sinc(SINC_DEGREE)
    err = sinc_error(coeffs)
    print("// gamma256Sinc[j] is |a_j|, the coefficient of sin(pi r)/(pi r) = sum a_j t**j, where t = r**2 and |r| <= 1/2.")
    print("// The sign of a_j is (-1)**j.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(err, 2))}.")
    print(f"var gamma256Sinc = [{len(coeffs)}][6]uint64{{")
    for j, c in enumerate(coeffs):
        assert (c < 0) == (j % 2 == 1), j
        print(f"\t{{{limbs(fix(abs(c)))}}}, // j = {j}")
    print("}")


main()
