#!/usr/bin/env python3
# Generates j032_table.go, the coefficients of the polynomials used by Float32 J0:
# the polynomials of J0(x) for the segments [i, i+1), i = 2, ..., 63, in t = x - i - 1/2.
#
# Usage: python3 scripts/gen_j032_table.py > j032_table.go

import mpmath

mpmath.mp.prec = 200

FIRST, LAST = 2, 63
DEGREE = 11


def fit(f, c, h, degree):
    """returns the coefficients of the polynomial in t = x - c for f, which interpolates at the Chebyshev nodes."""
    n = degree + 1
    nodes = [h * mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n)) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, t in enumerate(nodes):
        for j in range(n):
            a[i, j] = t**j
        b[i] = f(c + t)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def max_error(f, c, h, coeffs):
    worst = mpmath.mpf(0)
    for k in range(-40, 41):
        t = h * mpmath.mpf(k) / 41
        p = sum(mpmath.mpf(coeffs[j]) * t**j for j in range(len(coeffs)))
        worst = max(worst, abs(p - f(c + t)))
    return worst


rows = []
worst = mpmath.mpf(0)
for i in range(FIRST, LAST + 1):
    c, h = mpmath.mpf(i) + mpmath.mpf(1) / 2, mpmath.mpf(1) / 2
    coeffs = fit(lambda x: mpmath.besselj(0, x), c, h, DEGREE)
    worst = max(worst, max_error(lambda x: mpmath.besselj(0, x), c, h, coeffs))
    rows.append(coeffs)

print("// Code generated by scripts/gen_j032_table.py; DO NOT EDIT.")
print()
print("package floats")
print()
print(f"// j032Coeffs[i-{FIRST}] are the coefficients c0, c1, ..., c{DEGREE} of the polynomial c0 + c1 t + ... + c{DEGREE} t**{DEGREE},")
print("// which approximates J0(x) for the segment [i, i+1), where t = x - i - 1/2.")
print(f"// The absolute error is less than 2**-{int(-mpmath.log(worst, 2))}.")
print(f"var j032Coeffs = [...][{DEGREE + 1}]float64{{")
for row in rows:
    print("\t{" + ", ".join(v.hex() for v in row) + "},")
print("}")
