#!/usr/bin/env python3
# Generates erf128_table.go, the constants used by Float128 Erf.
# The numbers are in fixed point with 192 fractional bits in four 64-bit words, the first of which is the integer part,
# unless otherwise noted.
#
# Usage: python3 scripts/gen_erf128_table.py > erf128_table.go

import mpmath

mpmath.mp.prec = 700

F = 192
# erf(x) for x in [k/16, (k+1)/16) is calculated by the Taylor series around the center x0 = (k + 1/2)/16:
# erf(x0+h) = erf(x0) + 2/sqrt(pi) exp(-x0**2) sum_n b_n h**(n+1)/(n+1), where exp(-2 x0 h - h**2) = sum b_n h**n.
CELLS = 140  # erf(x) is rounded to 1 for x >= 8.7334
TAIL_BITS = 170  # the tail of the series is less than 2**-TAIL_BITS
SMALL_TERMS = 10  # the number of the terms of the series for |x| < 2**-8
# For the cells k >= LARGE_CELL, erf(x) is rounded from 1 - erfc(x), and erfc(x) is calculated in a relative accuracy.
LARGE_CELL = 112


def fix(x, frac_bits=F):
    return int(mpmath.floor(x * mpmath.mpf(2) ** frac_bits + mpmath.mpf(1) / 2))


def limbs(v, n=4):
    assert 0 <= v < 1 << (64 * n)
    return ", ".join(f"0x{(v >> (64 * (n - 1 - i))) & (2**64 - 1):016x}" for i in range(n))


def terms(k):
    """returns the number of the terms of the Taylor series for the cell k."""
    x0 = mpmath.mpf(2 * k + 1) / 32
    h = mpmath.mpf(1) / 32
    e0 = 2 / mpmath.sqrt(mpmath.pi) * mpmath.exp(-x0 * x0)
    if k >= LARGE_CELL:
        # erfc(x) is calculated in a relative accuracy
        e0 = e0 / mpmath.erfc(x0)
    b = [mpmath.mpf(1), -2 * x0]
    n = 1
    while True:
        # the bound of the term: |b_n| h**(n+1)/(n+1) e0
        while len(b) <= n + 1:
            m = len(b) - 1
            b.append(-(2 * x0 * b[m] + 2 * b[m - 1]) / (m + 1))
        if e0 * abs(b[n]) * h ** (n + 1) / (n + 1) < mpmath.mpf(2) ** -TAIL_BITS and e0 * abs(b[n + 1]) * h ** (n + 2) / (n + 2) < mpmath.mpf(2) ** -TAIL_BITS:
            return n
        n += 1


def main():
    print("// Code generated by scripts/gen_erf128_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()

    print("// erf128TwoOverSqrtPi is 2/sqrt(pi).")
    print(f"var erf128TwoOverSqrtPi = [4]uint64{{{limbs(fix(2 / mpmath.sqrt(mpmath.pi)))}}}")
    print()

    print("// erf128Small[n] is 1/(n! (2n+1)), the coefficient of erf(x) = 2/sqrt(pi) x sum (-x**2)**n/(n! (2n+1)).")
    print("var erf128Small = [...][4]uint64{")
    for n in range(SMALL_TERMS):
        print(f"\t{{{limbs(fix(1 / (mpmath.factorial(n) * (2 * n + 1))))}}}, // n = {n}")
    print("}")
    print()

    rows = []
    for k in range(CELLS):
        x0 = mpmath.mpf(2 * k + 1) / 32
        e0 = 2 / mpmath.sqrt(mpmath.pi) * mpmath.exp(-x0 * x0)
        e = int(mpmath.floor(mpmath.log(e0, 2)))
        m = e0 / mpmath.mpf(2) ** e
        rows.append((fix(mpmath.erf(x0)), fix(m), e, terms(k)))

    print("// erf128Erf[k] is erf(x0), where x0 = (k + 1/2)/16.")
    print("var erf128Erf = [...][4]uint64{")
    for r in rows:
        print(f"\t{{{limbs(r[0])}}},")
    print("}")
    print()
    print("// erf128E0[k] is the mantissa m of 2/sqrt(pi) exp(-x0**2) = m × 2**erf128E0Exp[k], where m is in [1, 2).")
    print("var erf128E0 = [...][4]uint64{")
    for r in rows:
        print(f"\t{{{limbs(r[1])}}},")
    print("}")
    print()
    print("// erf128E0Exp[k] is the exponent of 2/sqrt(pi) exp(-x0**2).")
    print("var erf128E0Exp = [...]int16{")
    print("\t" + ", ".join(str(r[2]) for r in rows) + ",")
    print("}")
    print()
    print("// erf128ErfcScaled[k-112] is erfc(x0) × 2**113 for the cells k >= 112, where x0 = (k + 1/2)/16.")
    print("var erf128ErfcScaled = [...][4]uint64{")
    for k in range(LARGE_CELL, CELLS):
        x0 = mpmath.mpf(2 * k + 1) / 32
        print(f"\t{{{limbs(fix(mpmath.erfc(x0) * mpmath.mpf(2) ** 113))}}},")
    print("}")
    print()
    print("// erf128R[k-112] is 2/sqrt(pi) exp(-x0**2) / erfc(x0) for the cells k >= 112.")
    print("var erf128R = [...][4]uint64{")
    for k in range(LARGE_CELL, CELLS):
        x0 = mpmath.mpf(2 * k + 1) / 32
        print(f"\t{{{limbs(fix(2 / mpmath.sqrt(mpmath.pi) * mpmath.exp(-x0 * x0) / mpmath.erfc(x0)))}}},")
    print("}")
    print()
    print("// erf128Terms[k] is the number of the terms of the Taylor series of the cell k.")
    print("var erf128Terms = [...]uint8{")
    print("\t" + ", ".join(str(r[3]) for r in rows) + ",")
    print("}")


main()
