#!/usr/bin/env python3
# Generates y1128_table.go, the constants used by Float128 Y1.
# All the numbers are the bits of Float128 in two 64-bit words.
#
# Usage: python3 scripts/gen_y1128_table.py > y1128_table.go

import mpmath

mpmath.mp.prec = 600

# the number of the coefficients of the power series in z = x**2/4, for 0 < x < 2
SERIES_TERMS = 24
# the number of the coefficients of the Hankel expansions in 1/x**2, for x >= 64
HANKEL_TERMS = 20
# the Taylor centers: (first center, last center, step)
TAYLOR = [(2.25, 7.75, 0.5), (8.5, 63.5, 1.0)]


def enc(v):
    """returns the Float128 bits of v rounded to nearest even."""
    v = mpmath.mpf(v)
    if v == 0:
        return 0
    with mpmath.workprec(113):
        r = +v
    sign, man, exp, bc = r._mpf_
    man = int(man)
    m = man << (113 - bc)
    e = exp + bc - 1
    assert -16382 <= e <= 16383
    return (sign << 127) | ((e + 16383) << 112) | (m - (1 << 112))


def lit(v):
    b = enc(v)
    return f"{{0x{b >> 64:016x}, 0x{b & (2**64 - 1):016x}}}"


def hankel(k):
    """returns a_k(1) = prod(4 - (2j-1)**2, j = 1, ..., k) / (k! 8**k)."""
    n = mpmath.mpf(1)
    for j in range(1, k + 1):
        n *= 4 - (2 * j - 1) ** 2
    return n / (mpmath.factorial(k) * 8**k)


def harmonic(k):
    return sum(mpmath.mpf(1) / j for j in range(1, k + 1))


def y1(x):
    return mpmath.bessely(1, x)


def y1_prime(x):
    return mpmath.bessely(0, x) - mpmath.bessely(1, x) / x


def taylor_terms(x0, hmax, c0, c1):
    """returns the smallest N such that the terms c_n hmax**n of the Taylor series of Y1 at x0 are
    less than 2**-125 for all n > N, where c0 = Y1(x0) and c1 = Y1'(x0).
    The coefficients are given by the recurrence derived from x**2 y'' + x y' + (x**2 - 1) y = 0."""
    c = {-2: mpmath.mpf(0), -1: mpmath.mpf(0), 0: c0, 1: c1}
    for n in range(0, 200):
        t = (n + 1) * (2 * n + 1) * c[n + 1] / x0 + (n * n + x0 * x0 - 1) * c[n] / x0**2 + 2 * c[n - 1] / x0 + c[n - 2] / x0**2
        c[n + 2] = -t / ((n + 2) * (n + 1))
    last = 0
    for n in range(len(c) - 2):
        if abs(c[n]) * hmax**n >= mpmath.mpf(2) ** -125:
            last = n
    assert last + 2 < 180
    return last + 1


def main():
    print("// Code generated by scripts/gen_y1128_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print("// y1128OneOverPi is 1/pi, and y1128TwoOverPi is 2/pi.")
    print(f"var y1128OneOverPi = Float128{lit(1 / mpmath.pi)}")
    print(f"var y1128TwoOverPi = Float128{lit(2 / mpmath.pi)}")
    print()
    print("// y1128SeriesJ[k] is (-1)**k / (k! (k+1)!), so that J1(x) = x/2 * sum y1128SeriesJ[k] z**k, z = x**2/4.")
    print("var y1128SeriesJ = [...]Float128{")
    for k in range(SERIES_TERMS):
        print(f"\t{lit((-1) ** k / (mpmath.factorial(k) * mpmath.factorial(k + 1)))}, // k = {k}")
    print("}")
    print()
    print("// y1128SeriesS[k] is -(-1)**k (H(k) + H(k+1)) / (2 k! (k+1)!), where H(k) is the k-th harmonic number, so that")
    print("// Y1(x) = x/pi * ((ln(x/2) + EulerGamma) * sum y1128SeriesJ[k] z**k + sum y1128SeriesS[k] z**k) - 2/(pi x),")
    print("// z = x**2/4.")
    print("var y1128SeriesS = [...]Float128{")
    for k in range(SERIES_TERMS):
        v = -(-1) ** k * (harmonic(k) + harmonic(k + 1)) / (2 * mpmath.factorial(k) * mpmath.factorial(k + 1))
        print(f"\t{lit(v)}, // k = {k}")
    print("}")
    print()
    print("// y1128HankelP[k] and y1128HankelQ[k] are the coefficients of the Hankel expansions")
    print("// P(x) = sum y1128HankelP[k] / x**(2k) and Q(x) = sum y1128HankelQ[k] / x**(2k+1).")
    print("var y1128HankelP = [...]Float128{")
    for k in range(HANKEL_TERMS):
        print(f"\t{lit((-1) ** k * hankel(2 * k))}, // k = {k}")
    print("}")
    print()
    print("var y1128HankelQ = [...]Float128{")
    for k in range(HANKEL_TERMS):
        print(f"\t{lit((-1) ** k * hankel(2 * k + 1))}, // k = {k}")
    print("}")
    print()
    rows = []
    for first, last, step in TAYLOR:
        n = int(round((last - first) / step)) + 1
        for i in range(n):
            x0 = mpmath.mpf(first) + i * mpmath.mpf(step)
            c0, c1 = y1(x0), y1_prime(x0)
            rows.append((float(x0), taylor_terms(x0, mpmath.mpf(step) / 2, c0, c1), c0, c1))
    print("// y1128MaxTaylorTerms is the maximum of y1128TaylorTerms.")
    print(f"const y1128MaxTaylorTerms = {max(r[1] for r in rows)}")
    print()
    print("// y1128TaylorTerms[i] is the degree of the Taylor polynomial at the center of the i-th interval.")
    print("var y1128TaylorTerms = [...]uint8{")
    for x0, t, _, _ in rows:
        print(f"\t{t}, // x0 = {x0}")
    print("}")
    print()
    print("// y1128Taylor[i] is {Y1(x0), Y1'(x0)} = {Y1(x0), Y0(x0) - Y1(x0)/x0} at the center x0 of the i-th interval.")
    print("var y1128Taylor = [...][2]Float128{")
    for x0, _, c0, c1 in rows:
        print(f"\t{{{lit(c0)}, {lit(c1)}}}, // x0 = {x0}")
    print("}")


main()
