#!/usr/bin/env python3
# Generates lgamma32_table.go, the coefficients of the polynomial of sin(pi r)/(pi r) used by Float32 Lgamma.
#
# Usage: python3 scripts/gen_lgamma32_table.py > lgamma32_table.go

import mpmath

mpmath.mp.prec = 300

SINC_TERMS = 8


def fit_sinc():
    """returns the coefficients of the polynomial in u = r**2 of sin(pi r)/(pi r) for |r| <= 1/2."""
    n = SINC_TERMS
    nodes = [mpmath.mpf(1) / 4 * (1 + mpmath.cos(mpmath.pi * (2 * k + 1) / (2 * n))) for k in range(n)]
    a = mpmath.matrix(n, n)
    b = mpmath.matrix(n, 1)
    for i, u in enumerate(nodes):
        r = mpmath.sqrt(u)
        for j in range(n):
            a[i, j] = u**j
        b[i] = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
    coeffs = mpmath.lu_solve(a, b)
    return [float(coeffs[j]) for j in range(n)]


def sinc_max_error(coeffs):
    worst = mpmath.mpf(0)
    for k in range(1, 401):
        r = mpmath.mpf(k) / 800
        p = sum(mpmath.mpf(coeffs[j]) * r ** (2 * j) for j in range(SINC_TERMS))
        g = mpmath.sin(mpmath.pi * r) / (mpmath.pi * r)
        worst = max(worst, abs(p - g) / g)
    return worst


if __name__ == "__main__":
    sinc = fit_sinc()
    print("// Code generated by scripts/gen_lgamma32_table.py; DO NOT EDIT.")
    print()
    print("package floats")
    print()
    print("// lgamma32SincCoeffs are the coefficients of the polynomial of u = r**2, which approximates sin(pi r)/(pi r) for |r| <= 1/2.")
    print(f"// The relative error is less than 2**-{int(-mpmath.log(sinc_max_error(sinc), 2))}.")
    print("var lgamma32SincCoeffs = [...]float64{")
    print("\t" + ", ".join(v.hex() for v in sinc) + ",")
    print("}")
